// SPDX-License-Identifier: Apache-2.0
import { readFile, readdir } from 'node:fs/promises';
import path from 'node:path';
import { parseHTML } from 'linkedom';
import { describe, expect, it } from 'vitest';

const projectRoot = path.resolve(import.meta.dirname, '../..');
const siteOrigin = 'https://cuda-learning-site.hmzhangxiang.workers.dev';

async function readRoute(route: string) {
  const relativePath = route === '/' ? 'index.html' : `${route.slice(1)}index.html`;
  const html = await readFile(path.join(projectRoot, 'dist', relativePath), 'utf8');
  return parseHTML(html).document;
}

type PublicationPair = {
  pairId: string;
  factCheckDate?: string;
  structure: string;
  resourceKind?: string;
  unitId?: string;
  prerequisites?: string;
  relatedUnits?: string;
  exampleIds?: string;
  canonicalExample?: string;
  canonicalRanges?: string;
  hardwareGate?: string;
  toolGate?: string;
  evidenceCompilation?: string;
  evidenceRuntime?: string;
  expectedObservations?: string;
  recordedObservations?: string;
  estimatedMinutes?: string;
  difficulty?: string;
  toolkitLanes?: string;
  minimumComputeCapability?: string;
  maximumProblemMemoryBytes?: string;
  gpuCount?: string;
  permissions?: string;
  sourceCount?: string;
  sourceVersions?: string;
  zh: string;
  en: string;
};

const publicationPairs: readonly PublicationPair[] = [
  {
    pairId: 'home',
    factCheckDate: '2026-08-28',
    structure: 'purpose,current-route,boundaries,destinations',
    zh: '/',
    en: '/en/',
  },
  {
    pairId: 'o01',
    factCheckDate: '2026-08-28',
    structure: 'outcome,resource-types,published-route,themes,workflow,boundaries,check',
    resourceKind: 'learning-unit',
    unitId: 'O01',
    prerequisites: 'none',
    relatedUnits: 'O02,O03,O04,O05,O06,O07,O08',
    zh: '/start/using-the-learning-site/',
    en: '/en/start/using-the-learning-site/',
  },
  {
    pairId: 'o02',
    structure: 'outcome,prerequisites,model,statuses,decision,examples,retrieval,practice,sources',
    resourceKind: 'learning-unit',
    unitId: 'O02',
    prerequisites: 'O01',
    relatedUnits: 'O01',
    exampleIds: 'O02-CASE-A,O02-CASE-B,O02-CASE-C,O02-CASE-D,O02-CASE-E,O02-CASE-F',
    sourceCount: '1',
    sourceVersions: '13.3.1',
    zh: '/start/evidence-status/',
    en: '/en/start/evidence-status/',
  },
  {
    pairId: 'o02-exercises',
    structure: 'prerequisites,instructions,exercise-1,exercise-2,exercise-3,next',
    resourceKind: 'exercise-set',
    unitId: 'O02-EXERCISES',
    prerequisites: 'O02',
    relatedUnits: 'O02',
    zh: '/start/evidence-status/exercises/',
    en: '/en/start/evidence-status/exercises/',
  },
  {
    pairId: 'o02-solutions',
    structure: 'review,solution-1,solution-2,solution-3,common-errors',
    resourceKind: 'solution-set',
    unitId: 'O02-SOLUTIONS',
    prerequisites: 'O02-EXERCISES',
    relatedUnits: 'O02',
    zh: '/start/evidence-status/solutions/',
    en: '/en/start/evidence-status/solutions/',
  },
  {
    pairId: 'o03',
    factCheckDate: '2026-08-26',
    structure: 'outcome,prerequisites,manifest,relationships,support,tiers,lanes,reference-boundary,retrieval,practice,sources',
    resourceKind: 'learning-unit',
    unitId: 'O03',
    prerequisites: 'O01',
    relatedUnits: 'O02,EX01,O08,LAB01,F01,LAB02',
    exampleIds: 'O03-MANIFEST-TEMPLATE,O03-INCOMPLETE-A',
    sourceCount: '8',
    sourceVersions: '11.8.0,12.9.2,13.3.1',
    zh: '/start/environment-manifest/',
    en: '/en/start/environment-manifest/',
  },
  {
    pairId: 'o03-exercises',
    structure: 'prerequisites,instructions,exercise-1,exercise-2,exercise-3,next',
    resourceKind: 'exercise-set',
    unitId: 'O03-EXERCISES',
    prerequisites: 'O03',
    relatedUnits: 'O03',
    zh: '/start/environment-manifest/exercises/',
    en: '/en/start/environment-manifest/exercises/',
  },
  {
    pairId: 'o03-solutions',
    structure: 'review,solution-1,solution-2,solution-3,common-errors',
    resourceKind: 'solution-set',
    unitId: 'O03-SOLUTIONS',
    prerequisites: 'O03-EXERCISES',
    relatedUnits: 'O03',
    zh: '/start/environment-manifest/solutions/',
    en: '/en/start/environment-manifest/solutions/',
  },
  {
    pairId: 'o04',
    factCheckDate: '2026-08-26',
    structure: 'outcome,prerequisites,pointers,ownership,templates,errors,build-boundaries,undefined-behavior,visual,retrieval,practice,sources',
    resourceKind: 'learning-unit',
    unitId: 'O04',
    prerequisites: 'O01',
    relatedUnits: 'F01,EX02',
    hardwareGate: 'none',
    sourceCount: '8',
    sourceVersions: 'N4659,N4661,GCC 13.3.0,CUDA 13.3,CUDA 13.3.1,Compute Sanitizer 2026.2.1',
    zh: '/start/cpp17-for-cuda/',
    en: '/en/start/cpp17-for-cuda/',
  },
  {
    pairId: 'o04-exercises',
    factCheckDate: '2026-08-26',
    structure: 'prerequisites,instructions,exercise-1,exercise-2,next',
    resourceKind: 'exercise-set',
    unitId: 'O04-EXERCISES',
    prerequisites: 'O04',
    relatedUnits: 'O04',
    hardwareGate: 'none',
    zh: '/start/cpp17-for-cuda/exercises/',
    en: '/en/start/cpp17-for-cuda/exercises/',
  },
  {
    pairId: 'o04-solutions',
    factCheckDate: '2026-08-26',
    structure: 'review,solution-1,solution-2,valid-alternatives,common-errors',
    resourceKind: 'solution-set',
    unitId: 'O04-SOLUTIONS',
    prerequisites: 'O04-EXERCISES',
    relatedUnits: 'O04',
    hardwareGate: 'none',
    zh: '/start/cpp17-for-cuda/solutions/',
    en: '/en/start/cpp17-for-cuda/solutions/',
  },
  {
    pairId: 'o05',
    factCheckDate: '2026-08-26',
    structure: 'outcome,prerequisites,paths,builds,processes,logs,reproducibility,visual,retrieval,practice,sources',
    resourceKind: 'learning-unit',
    unitId: 'O05',
    prerequisites: 'O01',
    relatedUnits: 'O03,O08,LAB01',
    hardwareGate: 'none',
    sourceCount: '5',
    sourceVersions: '5.3,9.11,4.4.1,4.0.6,6.8',
    zh: '/start/linux-command-line/',
    en: '/en/start/linux-command-line/',
  },
  {
    pairId: 'o05-exercises',
    factCheckDate: '2026-08-26',
    structure: 'prerequisites,instructions,exercise-1,exercise-2,next',
    resourceKind: 'exercise-set',
    unitId: 'O05-EXERCISES',
    prerequisites: 'O05',
    relatedUnits: 'O05',
    hardwareGate: 'none',
    zh: '/start/linux-command-line/exercises/',
    en: '/en/start/linux-command-line/exercises/',
  },
  {
    pairId: 'o05-solutions',
    factCheckDate: '2026-08-26',
    structure: 'review,solution-1,solution-2,valid-alternatives,common-errors',
    resourceKind: 'solution-set',
    unitId: 'O05-SOLUTIONS',
    prerequisites: 'O05-EXERCISES',
    relatedUnits: 'O05',
    hardwareGate: 'none',
    zh: '/start/linux-command-line/solutions/',
    en: '/en/start/linux-command-line/solutions/',
  },
  {
    pairId: 'o06',
    factCheckDate: '2026-08-26',
    structure: 'outcome,prerequisites,latency-throughput,memory,bandwidth,concurrency,intensity,comparison,visual,retrieval,practice,sources',
    resourceKind: 'learning-unit',
    unitId: 'O06',
    prerequisites: 'O01',
    relatedUnits: 'O07,F01,VIS01',
    hardwareGate: 'none',
    sourceCount: '7',
    sourceVersions: '13.3,2009,2026.2.1',
    zh: '/start/architecture-refresher/',
    en: '/en/start/architecture-refresher/',
  },
  {
    pairId: 'o06-exercises',
    factCheckDate: '2026-08-26',
    structure: 'prerequisites,instructions,exercise-1,exercise-2,next',
    resourceKind: 'exercise-set',
    unitId: 'O06-EXERCISES',
    prerequisites: 'O06',
    relatedUnits: 'O06',
    hardwareGate: 'none',
    zh: '/start/architecture-refresher/exercises/',
    en: '/en/start/architecture-refresher/exercises/',
  },
  {
    pairId: 'o06-solutions',
    factCheckDate: '2026-08-26',
    structure: 'review,solution-1,solution-2,valid-alternatives,common-errors',
    resourceKind: 'solution-set',
    unitId: 'O06-SOLUTIONS',
    prerequisites: 'O06-EXERCISES',
    relatedUnits: 'O06',
    hardwareGate: 'none',
    zh: '/start/architecture-refresher/solutions/',
    en: '/en/start/architecture-refresher/solutions/',
  },
  {
    pairId: 'o07',
    factCheckDate: '2026-08-26',
    structure: 'outcome,prerequisites,motivation,programmable-stages,gpgpu,cuda-shift,timeline,boundaries,retrieval,practice,sources',
    resourceKind: 'learning-unit',
    unitId: 'O07',
    prerequisites: 'O06',
    relatedUnits: 'F01,O06',
    hardwareGate: 'none',
    sourceCount: '7',
    sourceVersions: '13.3,2001,2002,2003,2004,2008',
    zh: '/start/programmable-gpus/',
    en: '/en/start/programmable-gpus/',
  },
  {
    pairId: 'o07-exercises',
    factCheckDate: '2026-08-26',
    structure: 'prerequisites,instructions,exercise-1,exercise-2,next',
    resourceKind: 'exercise-set',
    unitId: 'O07-EXERCISES',
    prerequisites: 'O07',
    relatedUnits: 'O07',
    hardwareGate: 'none',
    zh: '/start/programmable-gpus/exercises/',
    en: '/en/start/programmable-gpus/exercises/',
  },
  {
    pairId: 'o07-solutions',
    factCheckDate: '2026-08-26',
    structure: 'review,solution-1,solution-2,valid-alternatives,common-errors',
    resourceKind: 'solution-set',
    unitId: 'O07-SOLUTIONS',
    prerequisites: 'O07-EXERCISES',
    relatedUnits: 'O07',
    hardwareGate: 'none',
    zh: '/start/programmable-gpus/solutions/',
    en: '/en/start/programmable-gpus/solutions/',
  },
  {
    pairId: 'o08',
    factCheckDate: '2026-08-26',
    structure: 'outcome,prerequisites,candidate,manifest,tier,compatibility,control,baseline,decision,retrieval,practice,sources',
    resourceKind: 'learning-unit',
    unitId: 'O08',
    prerequisites: 'O02,O03,O05',
    relatedUnits: 'EX01,LAB01',
    exampleIds: 'EX01',
    hardwareGate: 'none',
    sourceCount: '8',
    sourceVersions: '11.8.0,12.9.2,13.3.1,13.3',
    zh: '/start/reference-environment-candidate/',
    en: '/en/start/reference-environment-candidate/',
  },
  {
    pairId: 'o08-exercises',
    factCheckDate: '2026-08-26',
    structure: 'prerequisites,instructions,exercise-1,exercise-2,next',
    resourceKind: 'exercise-set',
    unitId: 'O08-EXERCISES',
    prerequisites: 'O08',
    relatedUnits: 'O08,EX01,LAB01',
    exampleIds: 'EX01',
    hardwareGate: 'none',
    zh: '/start/reference-environment-candidate/exercises/',
    en: '/en/start/reference-environment-candidate/exercises/',
  },
  {
    pairId: 'o08-solutions',
    factCheckDate: '2026-08-26',
    structure: 'review,solution-1,solution-2,valid-alternatives,common-errors',
    resourceKind: 'solution-set',
    unitId: 'O08-SOLUTIONS',
    prerequisites: 'O08-EXERCISES',
    relatedUnits: 'O08,EX01,LAB01',
    exampleIds: 'EX01',
    hardwareGate: 'none',
    zh: '/start/reference-environment-candidate/solutions/',
    en: '/en/start/reference-environment-candidate/solutions/',
  },
  {
    pairId: 'f01',
    structure: 'outcome,prerequisites,motivation,prediction,implementation,correctness,measurement,optimization-boundaries,explanation,retrieval,practice,sources',
    resourceKind: 'learning-unit',
    unitId: 'F01',
    prerequisites: 'O03',
    relatedUnits: 'O02,VIS01,VIS02,LAB02',
    exampleIds: 'EX02',
    canonicalExample: 'EX02',
    canonicalRanges: 'kernel,error-checking,cpu-reference',
    hardwareGate: 'None for this Learning Unit; LAB02 requires native Linux and one qualifying CUDA GPU',
    sourceCount: '4',
    sourceVersions: '13.3,13.3.1',
    zh: '/foundations/first-cuda-kernel/',
    en: '/en/foundations/first-cuda-kernel/',
  },
  {
    pairId: 'f01-exercises',
    structure: 'prerequisites,instructions,exercise-1,exercise-2,exercise-3,next',
    resourceKind: 'exercise-set',
    unitId: 'F01-EXERCISES',
    prerequisites: 'F01',
    relatedUnits: 'F01,LAB02',
    exampleIds: 'EX02',
    hardwareGate: 'None; implementation may be prepared without executing CUDA',
    zh: '/foundations/first-cuda-kernel/exercises/',
    en: '/en/foundations/first-cuda-kernel/exercises/',
  },
  {
    pairId: 'f01-solutions',
    structure: 'review,solution-1,solution-2,solution-3,valid-alternatives,common-errors',
    resourceKind: 'solution-set',
    unitId: 'F01-SOLUTIONS',
    prerequisites: 'F01-EXERCISES',
    relatedUnits: 'F01,LAB02',
    exampleIds: 'EX02',
    zh: '/foundations/first-cuda-kernel/solutions/',
    en: '/en/foundations/first-cuda-kernel/solutions/',
  },
  {
    pairId: 'f02',
    factCheckDate: '2026-08-26',
    structure: 'outcome,prerequisites,hierarchy,kernel,grid,block,warp-lane,scheduling,prediction,retrieval,practice,sources',
    resourceKind: 'learning-unit',
    unitId: 'F02',
    prerequisites: 'F01',
    relatedUnits: 'VIS01,VIS02,F03',
    exampleIds: 'EX03',
    hardwareGate: 'none',
    sourceCount: '2',
    sourceVersions: '13.3',
    zh: '/foundations/execution-hierarchy/',
    en: '/en/foundations/execution-hierarchy/',
  },
  {
    pairId: 'f02-exercises',
    factCheckDate: '2026-08-26',
    structure: 'prerequisites,instructions,exercise-1,exercise-2,exercise-3,next',
    resourceKind: 'exercise-set',
    unitId: 'F02-EXERCISES',
    prerequisites: 'F02',
    relatedUnits: 'F02,VIS01,VIS02,F03',
    exampleIds: 'EX03',
    hardwareGate: 'none',
    zh: '/foundations/execution-hierarchy/exercises/',
    en: '/en/foundations/execution-hierarchy/exercises/',
  },
  {
    pairId: 'f02-solutions',
    factCheckDate: '2026-08-26',
    structure: 'review,solution-1,solution-2,solution-3,valid-alternatives,common-errors',
    resourceKind: 'solution-set',
    unitId: 'F02-SOLUTIONS',
    prerequisites: 'F02-EXERCISES',
    relatedUnits: 'F02,VIS01,VIS02,F03',
    exampleIds: 'EX03',
    hardwareGate: 'none',
    zh: '/foundations/execution-hierarchy/solutions/',
    en: '/en/foundations/execution-hierarchy/solutions/',
  },
  {
    pairId: 'f03',
    factCheckDate: '2026-08-26',
    structure: 'outcome,prerequisites,coordinate-contract,one-dimension,two-dimensions,three-dimensions,bounds,flattening,canonical-example,visual,correctness,retrieval,practice,sources',
    resourceKind: 'learning-unit',
    unitId: 'F03',
    prerequisites: 'F02',
    relatedUnits: 'VIS02,EX03,F04',
    exampleIds: 'EX03',
    canonicalExample: 'EX03',
    canonicalRanges: 'indexing-kernel,host-reference',
    hardwareGate: 'none',
    sourceCount: '2',
    sourceVersions: '13.3',
    zh: '/foundations/multidimensional-indexing/',
    en: '/en/foundations/multidimensional-indexing/',
  },
  {
    pairId: 'f03-exercises',
    factCheckDate: '2026-08-26',
    structure: 'prerequisites,instructions,exercise-1,exercise-2,exercise-3,next',
    resourceKind: 'exercise-set',
    unitId: 'F03-EXERCISES',
    prerequisites: 'F03',
    relatedUnits: 'F03,VIS02,EX03,F04',
    exampleIds: 'EX03',
    hardwareGate: 'none',
    zh: '/foundations/multidimensional-indexing/exercises/',
    en: '/en/foundations/multidimensional-indexing/exercises/',
  },
  {
    pairId: 'f03-solutions',
    factCheckDate: '2026-08-26',
    structure: 'review,solution-1,solution-2,solution-3,valid-alternatives,common-errors',
    resourceKind: 'solution-set',
    unitId: 'F03-SOLUTIONS',
    prerequisites: 'F03-EXERCISES',
    relatedUnits: 'F03,VIS02,EX03,F04',
    exampleIds: 'EX03',
    hardwareGate: 'none',
    zh: '/foundations/multidimensional-indexing/solutions/',
    en: '/en/foundations/multidimensional-indexing/solutions/',
  },
  {
    pairId: 'f04',
    factCheckDate: '2026-08-26',
    structure: 'outcome,prerequisites,ownership,initialization,allocation,transfer-in,launch,synchronization,transfer-out,verification,release,lifecycle-map,canonical-example,retrieval,practice,sources',
    resourceKind: 'learning-unit',
    unitId: 'F04',
    prerequisites: 'F01',
    relatedUnits: 'O04,EX03',
    exampleIds: 'EX03',
    canonicalExample: 'EX03',
    canonicalRanges: 'lifecycle',
    hardwareGate: 'none',
    sourceCount: '4',
    sourceVersions: '13.3,13.3.1',
    zh: '/foundations/host-device-lifecycle/',
    en: '/en/foundations/host-device-lifecycle/',
  },
  {
    pairId: 'f04-exercises',
    factCheckDate: '2026-08-26',
    structure: 'prerequisites,instructions,exercise-1,exercise-2,exercise-3,next',
    resourceKind: 'exercise-set',
    unitId: 'F04-EXERCISES',
    prerequisites: 'F04',
    relatedUnits: 'F04,O04,EX03',
    exampleIds: 'EX03',
    hardwareGate: 'none',
    zh: '/foundations/host-device-lifecycle/exercises/',
    en: '/en/foundations/host-device-lifecycle/exercises/',
  },
  {
    pairId: 'f04-solutions',
    factCheckDate: '2026-08-26',
    structure: 'review,solution-1,solution-2,solution-3,valid-alternatives,common-errors',
    resourceKind: 'solution-set',
    unitId: 'F04-SOLUTIONS',
    prerequisites: 'F04-EXERCISES',
    relatedUnits: 'F04,O04,EX03',
    exampleIds: 'EX03',
    hardwareGate: 'none',
    zh: '/foundations/host-device-lifecycle/solutions/',
    en: '/en/foundations/host-device-lifecycle/solutions/',
  },
  {
    pairId: 'f05',
    factCheckDate: '2026-08-26',
    structure: 'outcome,prerequisites,error-state,immediate,deferred,synchronization,canonical-example,timeline,correctness,retrieval,practice,sources',
    resourceKind: 'learning-unit',
    unitId: 'F05',
    prerequisites: 'F04',
    relatedUnits: 'F03,EX04,LAB03,F07,VIS19',
    exampleIds: 'EX04',
    canonicalExample: 'EX04',
    canonicalRanges: 'error-lifecycle',
    hardwareGate: 'none',
    sourceCount: '9',
    sourceVersions: '11.8.0,12.9.1,12.9.2,13.3.1',
    zh: '/foundations/asynchronous-errors/',
    en: '/en/foundations/asynchronous-errors/',
  },
  {
    pairId: 'f05-exercises',
    factCheckDate: '2026-08-26',
    structure: 'prerequisites,instructions,exercise-1,exercise-2,exercise-3,next',
    resourceKind: 'exercise-set',
    unitId: 'F05-EXERCISES',
    prerequisites: 'F05',
    relatedUnits: 'F05,F03,EX04,LAB03,F07,VIS19',
    exampleIds: 'EX04',
    hardwareGate: 'none',
    zh: '/foundations/asynchronous-errors/exercises/',
    en: '/en/foundations/asynchronous-errors/exercises/',
  },
  {
    pairId: 'f05-solutions',
    factCheckDate: '2026-08-26',
    structure: 'review,solution-1,solution-2,solution-3,valid-alternatives,common-errors',
    resourceKind: 'solution-set',
    unitId: 'F05-SOLUTIONS',
    prerequisites: 'F05-EXERCISES',
    relatedUnits: 'F05,F03,EX04,LAB03,F07,VIS19',
    exampleIds: 'EX04',
    hardwareGate: 'none',
    zh: '/foundations/asynchronous-errors/solutions/',
    en: '/en/foundations/asynchronous-errors/solutions/',
  },
  {
    pairId: 'f06',
    factCheckDate: '2026-08-26',
    structure: 'outcome,prerequisites,coordinates,feature-contract,limits,compiler-targets,filter,decisions,retrieval,practice,sources',
    resourceKind: 'learning-unit',
    unitId: 'F06',
    prerequisites: 'F02,O03',
    relatedUnits: 'F08,VIS20',
    hardwareGate: 'none',
    sourceCount: '5',
    sourceVersions: '11.8.0,12.9.2,13.3,13.3.1',
    zh: '/foundations/compute-capability/',
    en: '/en/foundations/compute-capability/',
  },
  {
    pairId: 'f06-exercises',
    factCheckDate: '2026-08-26',
    structure: 'prerequisites,instructions,exercise-1,exercise-2,exercise-3,next',
    resourceKind: 'exercise-set',
    unitId: 'F06-EXERCISES',
    prerequisites: 'F06',
    relatedUnits: 'F06,F08,VIS20',
    hardwareGate: 'none',
    zh: '/foundations/compute-capability/exercises/',
    en: '/en/foundations/compute-capability/exercises/',
  },
  {
    pairId: 'f06-solutions',
    factCheckDate: '2026-08-26',
    structure: 'review,solution-1,solution-2,solution-3,valid-alternatives,common-errors',
    resourceKind: 'solution-set',
    unitId: 'F06-SOLUTIONS',
    prerequisites: 'F06-EXERCISES',
    relatedUnits: 'F06,F08,VIS20',
    hardwareGate: 'none',
    zh: '/foundations/compute-capability/solutions/',
    en: '/en/foundations/compute-capability/solutions/',
  },
  {
    pairId: 'f07',
    factCheckDate: '2026-08-26',
    structure: 'outcome,prerequisites,shared-stack,runtime-role,driver-role,ownership,interoperability,error-model,boundary,decisions,retrieval,practice,sources',
    resourceKind: 'learning-unit',
    unitId: 'F07',
    prerequisites: 'F04,F05',
    relatedUnits: 'EX04,VIS21',
    exampleIds: 'EX04',
    hardwareGate: 'none',
    sourceCount: '10',
    sourceVersions: '11.8.0,12.9.1,12.9.2,13.3.1',
    zh: '/foundations/runtime-driver-api/',
    en: '/en/foundations/runtime-driver-api/',
  },
  {
    pairId: 'f07-exercises',
    factCheckDate: '2026-08-26',
    structure: 'prerequisites,instructions,exercise-1,exercise-2,exercise-3,next',
    resourceKind: 'exercise-set',
    unitId: 'F07-EXERCISES',
    prerequisites: 'F07',
    relatedUnits: 'F07,EX04,VIS21',
    exampleIds: 'EX04',
    hardwareGate: 'none',
    zh: '/foundations/runtime-driver-api/exercises/',
    en: '/en/foundations/runtime-driver-api/exercises/',
  },
  {
    pairId: 'f07-solutions',
    factCheckDate: '2026-08-26',
    structure: 'review,solution-1,solution-2,solution-3,valid-alternatives,common-errors',
    resourceKind: 'solution-set',
    unitId: 'F07-SOLUTIONS',
    prerequisites: 'F07-EXERCISES',
    relatedUnits: 'F07,EX04,VIS21',
    exampleIds: 'EX04',
    hardwareGate: 'none',
    zh: '/foundations/runtime-driver-api/solutions/',
    en: '/en/foundations/runtime-driver-api/solutions/',
  },
  {
    pairId: 'f08',
    factCheckDate: '2026-08-26',
    structure: 'outcome,prerequisites,invariants,legality,coverage,resources,block-shape,explorer,measurement-boundary,retrieval,practice,sources',
    resourceKind: 'learning-unit',
    unitId: 'F08',
    prerequisites: 'F02,F03,F06',
    relatedUnits: 'LAB03,VIS22',
    hardwareGate: 'none',
    sourceCount: '3',
    sourceVersions: '13.3,13.3.1',
    zh: '/foundations/launch-geometry/',
    en: '/en/foundations/launch-geometry/',
  },
  {
    pairId: 'f08-exercises',
    factCheckDate: '2026-08-26',
    structure: 'prerequisites,instructions,exercise-1,exercise-2,exercise-3,next',
    resourceKind: 'exercise-set',
    unitId: 'F08-EXERCISES',
    prerequisites: 'F08',
    relatedUnits: 'F08,LAB03,VIS22',
    hardwareGate: 'none',
    zh: '/foundations/launch-geometry/exercises/',
    en: '/en/foundations/launch-geometry/exercises/',
  },
  {
    pairId: 'f08-solutions',
    factCheckDate: '2026-08-26',
    structure: 'review,solution-1,solution-2,solution-3,valid-alternatives,common-errors',
    resourceKind: 'solution-set',
    unitId: 'F08-SOLUTIONS',
    prerequisites: 'F08-EXERCISES',
    relatedUnits: 'F08,LAB03,VIS22',
    hardwareGate: 'none',
    zh: '/foundations/launch-geometry/solutions/',
    en: '/en/foundations/launch-geometry/solutions/',
  },
  {
    pairId: 'm01',
    factCheckDate: '2026-08-27',
    structure: 'outcome,prerequisites,classification-model,host-global-constant,shared-local-register,cache-boundary,release-ledger,retrieval,practice,sources',
    resourceKind: 'learning-unit',
    unitId: 'M01',
    prerequisites: 'F04,F06',
    relatedUnits: 'VIS06',
    hardwareGate: 'none',
    sourceCount: '6',
    sourceVersions: '11.8.0,12.9.1,13.3,13.3.1',
    zh: '/memory/address-spaces/',
    en: '/en/memory/address-spaces/',
  },
  {
    pairId: 'm01-exercises',
    factCheckDate: '2026-08-27',
    structure: 'prerequisites,instructions,exercise-1,exercise-2,exercise-3,next',
    resourceKind: 'exercise-set',
    unitId: 'M01-EXERCISES',
    prerequisites: 'M01',
    relatedUnits: 'M01,VIS06',
    hardwareGate: 'none',
    zh: '/memory/address-spaces/exercises/',
    en: '/en/memory/address-spaces/exercises/',
  },
  {
    pairId: 'm01-solutions',
    factCheckDate: '2026-08-27',
    structure: 'review,solution-1,solution-2,solution-3,valid-alternatives,common-errors',
    resourceKind: 'solution-set',
    unitId: 'M01-SOLUTIONS',
    prerequisites: 'M01-EXERCISES',
    relatedUnits: 'M01,VIS06',
    hardwareGate: 'none',
    zh: '/memory/address-spaces/solutions/',
    en: '/en/memory/address-spaces/solutions/',
  },
  {
    pairId: 'm02',
    factCheckDate: '2026-08-27',
    structure: 'outcome,prerequisites,model,aligned,offset,stride,active-lanes,canonical-example,measurement-boundary,retrieval,practice,sources',
    resourceKind: 'learning-unit',
    unitId: 'M02',
    prerequisites: 'M01,F03',
    relatedUnits: 'EX05,VIS04',
    exampleIds: 'EX05',
    canonicalExample: 'EX05',
    canonicalRanges: 'access-kernel',
    hardwareGate: 'none',
    sourceCount: '4',
    sourceVersions: '11.8.0,12.9.1,13.3',
    zh: '/memory/coalescing-transactions/',
    en: '/en/memory/coalescing-transactions/',
  },
  {
    pairId: 'm02-exercises',
    factCheckDate: '2026-08-27',
    structure: 'prerequisites,instructions,exercise-1,exercise-2,exercise-3,next',
    resourceKind: 'exercise-set',
    unitId: 'M02-EXERCISES',
    prerequisites: 'M02',
    relatedUnits: 'M02,EX05,VIS04',
    hardwareGate: 'none',
    zh: '/memory/coalescing-transactions/exercises/',
    en: '/en/memory/coalescing-transactions/exercises/',
  },
  {
    pairId: 'm02-solutions',
    factCheckDate: '2026-08-27',
    structure: 'review,solution-1,solution-2,solution-3,valid-alternatives,common-errors',
    resourceKind: 'solution-set',
    unitId: 'M02-SOLUTIONS',
    prerequisites: 'M02-EXERCISES',
    relatedUnits: 'M02,EX05,VIS04',
    hardwareGate: 'none',
    zh: '/memory/coalescing-transactions/solutions/',
    en: '/en/memory/coalescing-transactions/solutions/',
  },
  {
    pairId: 'm03',
    factCheckDate: '2026-08-27',
    structure: 'outcome,prerequisites,tile-contract,load,first-barrier,use,second-barrier,bounds,canonical-example,evidence-boundary,retrieval,practice,sources',
    resourceKind: 'learning-unit',
    unitId: 'M03',
    prerequisites: 'M01,M02',
    relatedUnits: 'EX06',
    exampleIds: 'EX06',
    canonicalExample: 'EX06',
    canonicalRanges: 'tiled-kernels',
    hardwareGate: 'none',
    sourceCount: '4',
    sourceVersions: '11.8.0,12.9.1,13.3',
    zh: '/memory/shared-memory-tiling/',
    en: '/en/memory/shared-memory-tiling/',
  },
  {
    pairId: 'm03-exercises',
    factCheckDate: '2026-08-27',
    structure: 'prerequisites,instructions,exercise-1,exercise-2,exercise-3,next',
    resourceKind: 'exercise-set',
    unitId: 'M03-EXERCISES',
    prerequisites: 'M03',
    relatedUnits: 'M03,EX06',
    hardwareGate: 'none',
    zh: '/memory/shared-memory-tiling/exercises/',
    en: '/en/memory/shared-memory-tiling/exercises/',
  },
  {
    pairId: 'm03-solutions',
    factCheckDate: '2026-08-27',
    structure: 'review,solution-1,solution-2,solution-3,valid-alternatives,common-errors',
    resourceKind: 'solution-set',
    unitId: 'M03-SOLUTIONS',
    prerequisites: 'M03-EXERCISES',
    relatedUnits: 'M03,EX06',
    hardwareGate: 'none',
    zh: '/memory/shared-memory-tiling/solutions/',
    en: '/en/memory/shared-memory-tiling/solutions/',
  },
  {
    pairId: 'm04',
    factCheckDate: '2026-08-27',
    structure: 'outcome,prerequisites,fixture,conflict-broadcast,strides,tile-layout,padding,canonical-example,measurement-boundary,retrieval,practice,sources',
    resourceKind: 'learning-unit',
    unitId: 'M04',
    prerequisites: 'M03',
    relatedUnits: 'EX06,VIS05',
    exampleIds: 'EX06',
    canonicalExample: 'EX06',
    canonicalRanges: 'shared-layouts',
    hardwareGate: 'none',
    sourceCount: '4',
    sourceVersions: '11.8.0,12.9.1,13.3',
    zh: '/memory/bank-conflicts-layouts/',
    en: '/en/memory/bank-conflicts-layouts/',
  },
  {
    pairId: 'm04-exercises',
    factCheckDate: '2026-08-27',
    structure: 'prerequisites,instructions,exercise-1,exercise-2,exercise-3,next',
    resourceKind: 'exercise-set',
    unitId: 'M04-EXERCISES',
    prerequisites: 'M04',
    relatedUnits: 'M04,EX06,VIS05',
    hardwareGate: 'none',
    zh: '/memory/bank-conflicts-layouts/exercises/',
    en: '/en/memory/bank-conflicts-layouts/exercises/',
  },
  {
    pairId: 'm04-solutions',
    factCheckDate: '2026-08-27',
    structure: 'review,solution-1,solution-2,solution-3,valid-alternatives,common-errors',
    resourceKind: 'solution-set',
    unitId: 'M04-SOLUTIONS',
    prerequisites: 'M04-EXERCISES',
    relatedUnits: 'M04,EX06,VIS05',
    hardwareGate: 'none',
    zh: '/memory/bank-conflicts-layouts/solutions/',
    en: '/en/memory/bank-conflicts-layouts/solutions/',
  },
  {
    pairId: 'm05',
    factCheckDate: '2026-08-28',
    structure: 'outcome,prerequisites,scope-ledger,rendezvous,ordering-visibility,atomicity,barriers-fences,selection,evidence-boundary,retrieval,practice,sources',
    resourceKind: 'learning-unit',
    unitId: 'M05',
    prerequisites: 'F02,M01',
    relatedUnits: 'none',
    hardwareGate: 'none',
    sourceCount: '5',
    sourceVersions: '11.8.0,12.9.1,13.3',
    zh: '/memory/synchronization-scopes/',
    en: '/en/memory/synchronization-scopes/',
  },
  {
    pairId: 'm05-exercises',
    factCheckDate: '2026-08-28',
    structure: 'prerequisites,instructions,exercise-1,exercise-2,exercise-3,next',
    resourceKind: 'exercise-set',
    unitId: 'M05-EXERCISES',
    prerequisites: 'M05',
    relatedUnits: 'M05',
    hardwareGate: 'none',
    zh: '/memory/synchronization-scopes/exercises/',
    en: '/en/memory/synchronization-scopes/exercises/',
  },
  {
    pairId: 'm05-solutions',
    factCheckDate: '2026-08-28',
    structure: 'review,solution-1,solution-2,solution-3,valid-alternatives,common-errors',
    resourceKind: 'solution-set',
    unitId: 'M05-SOLUTIONS',
    prerequisites: 'M05-EXERCISES',
    relatedUnits: 'M05',
    hardwareGate: 'none',
    zh: '/memory/synchronization-scopes/solutions/',
    en: '/en/memory/synchronization-scopes/solutions/',
  },
  {
    pairId: 'm06',
    factCheckDate: '2026-08-28',
    structure: 'outcome,prerequisites,active-masks,divergence,reconvergence,independent-thread-scheduling,unsafe-lockstep,source-join,schedule-boundary,visual-model,evidence-boundary,retrieval,practice,sources',
    resourceKind: 'learning-unit',
    unitId: 'M06',
    prerequisites: 'F02,M05',
    relatedUnits: 'VIS03',
    hardwareGate: 'none',
    sourceCount: '5',
    sourceVersions: '11.8.0,12.9.1,13.3',
    zh: '/memory/warp-divergence-reconvergence/',
    en: '/en/memory/warp-divergence-reconvergence/',
  },
  {
    pairId: 'm06-exercises',
    factCheckDate: '2026-08-28',
    structure: 'prerequisites,instructions,exercise-1,exercise-2,exercise-3,next',
    resourceKind: 'exercise-set',
    unitId: 'M06-EXERCISES',
    prerequisites: 'M06',
    relatedUnits: 'M06,VIS03',
    hardwareGate: 'none',
    zh: '/memory/warp-divergence-reconvergence/exercises/',
    en: '/en/memory/warp-divergence-reconvergence/exercises/',
  },
  {
    pairId: 'm06-solutions',
    factCheckDate: '2026-08-28',
    structure: 'review,solution-1,solution-2,solution-3,valid-alternatives,common-errors',
    resourceKind: 'solution-set',
    unitId: 'M06-SOLUTIONS',
    prerequisites: 'M06-EXERCISES',
    relatedUnits: 'M06,VIS03',
    hardwareGate: 'none',
    zh: '/memory/warp-divergence-reconvergence/solutions/',
    en: '/en/memory/warp-divergence-reconvergence/solutions/',
  },
  {
    pairId: 'm07',
    factCheckDate: '2026-08-28',
    structure: 'outcome,prerequisites,named-streams,per-stream-order,cross-stream-order,eligibility,default-stream,dependency-ledger,visual-model,evidence-boundary,retrieval,practice,sources',
    resourceKind: 'learning-unit',
    unitId: 'M07',
    prerequisites: 'F05,M01',
    relatedUnits: 'M08,VIS07',
    hardwareGate: 'none',
    sourceCount: '9',
    sourceVersions: '11.8.0,12.9.1,13.3,13.3.1',
    zh: '/memory/stream-ordering/',
    en: '/en/memory/stream-ordering/',
  },
  {
    pairId: 'm07-exercises',
    factCheckDate: '2026-08-28',
    structure: 'prerequisites,instructions,exercise-1,exercise-2,exercise-3,next',
    resourceKind: 'exercise-set',
    unitId: 'M07-EXERCISES',
    prerequisites: 'M07',
    relatedUnits: 'M07,M08,VIS07',
    hardwareGate: 'none',
    zh: '/memory/stream-ordering/exercises/',
    en: '/en/memory/stream-ordering/exercises/',
  },
  {
    pairId: 'm07-solutions',
    factCheckDate: '2026-08-28',
    structure: 'review,solution-1,solution-2,solution-3,valid-alternatives,common-errors',
    resourceKind: 'solution-set',
    unitId: 'M07-SOLUTIONS',
    prerequisites: 'M07-EXERCISES',
    relatedUnits: 'M07,M08,VIS07',
    hardwareGate: 'none',
    zh: '/memory/stream-ordering/solutions/',
    en: '/en/memory/stream-ordering/solutions/',
  },
  {
    pairId: 'm08',
    factCheckDate: '2026-08-28',
    structure: 'outcome,prerequisites,event-record,stream-wait,query-synchronize,re-record,timing-disabled,elapsed-time,dependency-ledger,visual-model,evidence-boundary,retrieval,practice,sources',
    resourceKind: 'learning-unit',
    unitId: 'M08',
    prerequisites: 'M07',
    relatedUnits: 'VIS07',
    hardwareGate: 'none',
    sourceCount: '9',
    sourceVersions: '11.8.0,12.9.1,13.3,13.3.1',
    zh: '/memory/event-dependencies-timing/',
    en: '/en/memory/event-dependencies-timing/',
  },
  {
    pairId: 'm08-exercises',
    factCheckDate: '2026-08-28',
    structure: 'prerequisites,instructions,exercise-1,exercise-2,exercise-3,next',
    resourceKind: 'exercise-set',
    unitId: 'M08-EXERCISES',
    prerequisites: 'M08',
    relatedUnits: 'M08,VIS07',
    hardwareGate: 'none',
    zh: '/memory/event-dependencies-timing/exercises/',
    en: '/en/memory/event-dependencies-timing/exercises/',
  },
  {
    pairId: 'm08-solutions',
    factCheckDate: '2026-08-28',
    structure: 'review,solution-1,solution-2,solution-3,valid-alternatives,common-errors',
    resourceKind: 'solution-set',
    unitId: 'M08-SOLUTIONS',
    prerequisites: 'M08-EXERCISES',
    relatedUnits: 'M08,VIS07',
    hardwareGate: 'none',
    zh: '/memory/event-dependencies-timing/solutions/',
    en: '/en/memory/event-dependencies-timing/solutions/',
  },
  {
    pairId: 'q01',
    factCheckDate: '2026-08-28',
    structure: 'outcome,prerequisites,correctness-first,cpu-reference,abs-rel-tolerance,scale-aware-policy,exact-discrete,independent-invariants,decision-ledger,evidence-boundary,retrieval,practice,sources',
    resourceKind: 'learning-unit',
    unitId: 'Q01',
    prerequisites: 'F04,O04',
    relatedUnits: 'Q03,Q05',
    hardwareGate: 'none',
    sourceCount: '6',
    sourceVersions: '11.8.0,12.9.1,13.3',
    zh: '/correctness/cpu-references-tolerances-invariants/',
    en: '/en/correctness/cpu-references-tolerances-invariants/',
  },
  {
    pairId: 'q01-exercises',
    factCheckDate: '2026-08-28',
    structure: 'prerequisites,instructions,exercise-1,exercise-2,exercise-3,next',
    resourceKind: 'exercise-set',
    unitId: 'Q01-EXERCISES',
    prerequisites: 'Q01',
    relatedUnits: 'Q01,Q03,Q05',
    hardwareGate: 'none',
    zh: '/correctness/cpu-references-tolerances-invariants/exercises/',
    en: '/en/correctness/cpu-references-tolerances-invariants/exercises/',
  },
  {
    pairId: 'q01-solutions',
    factCheckDate: '2026-08-28',
    structure: 'review,solution-1,solution-2,solution-3,valid-alternatives,common-errors',
    resourceKind: 'solution-set',
    unitId: 'Q01-SOLUTIONS',
    prerequisites: 'Q01-EXERCISES',
    relatedUnits: 'Q01,Q03,Q05',
    hardwareGate: 'none',
    zh: '/correctness/cpu-references-tolerances-invariants/solutions/',
    en: '/en/correctness/cpu-references-tolerances-invariants/solutions/',
  },
  {
    pairId: 'q03',
    factCheckDate: '2026-08-28',
    structure: 'outcome,prerequisites,lane-baseline,precise-accesses,leak-checking,api-errors,coverage-boundary,tool-order,review-ledger,evidence-boundary,retrieval,practice,sources',
    resourceKind: 'learning-unit',
    unitId: 'Q03',
    prerequisites: 'F05,Q01',
    relatedUnits: 'Q04,EX16,LAB07',
    hardwareGate: 'none',
    sourceCount: '6',
    sourceVersions: '11.8.0,12.9.1,2026.2.1',
    zh: '/correctness/memcheck-invalid-memory-access/',
    en: '/en/correctness/memcheck-invalid-memory-access/',
  },
  {
    pairId: 'q03-exercises',
    factCheckDate: '2026-08-28',
    structure: 'prerequisites,instructions,exercise-1,exercise-2,exercise-3,next',
    resourceKind: 'exercise-set',
    unitId: 'Q03-EXERCISES',
    prerequisites: 'Q03',
    relatedUnits: 'Q03,Q04,EX16,LAB07',
    hardwareGate: 'none',
    zh: '/correctness/memcheck-invalid-memory-access/exercises/',
    en: '/en/correctness/memcheck-invalid-memory-access/exercises/',
  },
  {
    pairId: 'q03-solutions',
    factCheckDate: '2026-08-28',
    structure: 'review,solution-1,solution-2,solution-3,valid-alternatives,common-errors',
    resourceKind: 'solution-set',
    unitId: 'Q03-SOLUTIONS',
    prerequisites: 'Q03-EXERCISES',
    relatedUnits: 'Q03,Q04,EX16,LAB07',
    hardwareGate: 'none',
    zh: '/correctness/memcheck-invalid-memory-access/solutions/',
    en: '/en/correctness/memcheck-invalid-memory-access/solutions/',
  },
  {
    pairId: 'q04',
    factCheckDate: '2026-08-28',
    structure: 'outcome,prerequisites,workflow,racecheck,initcheck,synccheck,isolation,coverage-boundary,evidence-boundary,retrieval,practice,sources',
    resourceKind: 'learning-unit',
    unitId: 'Q04',
    prerequisites: 'M05,M06,Q03',
    relatedUnits: 'EX16,LAB07',
    hardwareGate: 'none',
    sourceCount: '3',
    sourceVersions: '11.8.0,2026.2.1',
    zh: '/correctness/racecheck-initcheck-synccheck/',
    en: '/en/correctness/racecheck-initcheck-synccheck/',
  },
  {
    pairId: 'q04-exercises',
    factCheckDate: '2026-08-28',
    structure: 'prerequisites,instructions,exercise-1,exercise-2,exercise-3,next',
    resourceKind: 'exercise-set',
    unitId: 'Q04-EXERCISES',
    prerequisites: 'Q04',
    relatedUnits: 'Q04,EX16,LAB07',
    hardwareGate: 'none',
    zh: '/correctness/racecheck-initcheck-synccheck/exercises/',
    en: '/en/correctness/racecheck-initcheck-synccheck/exercises/',
  },
  {
    pairId: 'q04-solutions',
    factCheckDate: '2026-08-28',
    structure: 'review,solution-1,solution-2,solution-3,valid-alternatives,common-errors',
    resourceKind: 'solution-set',
    unitId: 'Q04-SOLUTIONS',
    prerequisites: 'Q04-EXERCISES',
    relatedUnits: 'Q04,EX16,LAB07',
    hardwareGate: 'none',
    zh: '/correctness/racecheck-initcheck-synccheck/solutions/',
    en: '/en/correctness/racecheck-initcheck-synccheck/solutions/',
  },
  {
    pairId: 'q05',
    factCheckDate: '2026-08-28',
    structure: 'outcome,prerequisites,correctness-gate,warm-up,completion,cuda-events,host-timers,samples-statistics,environment-manifest,claim-boundary,evidence-boundary,retrieval,practice,sources',
    resourceKind: 'learning-unit',
    unitId: 'Q05',
    prerequisites: 'M08,Q01',
    relatedUnits: 'LAB04,LAB05',
    hardwareGate: 'none',
    sourceCount: '6',
    sourceVersions: '11.8.0,12.2,12.9.1,13.3,13.3.1',
    zh: '/correctness/timing-asynchronous-gpu-work/',
    en: '/en/correctness/timing-asynchronous-gpu-work/',
  },
  {
    pairId: 'q05-exercises',
    factCheckDate: '2026-08-28',
    structure: 'prerequisites,instructions,exercise-1,exercise-2,exercise-3,next',
    resourceKind: 'exercise-set',
    unitId: 'Q05-EXERCISES',
    prerequisites: 'Q05',
    relatedUnits: 'Q05,LAB04,LAB05',
    hardwareGate: 'none',
    zh: '/correctness/timing-asynchronous-gpu-work/exercises/',
    en: '/en/correctness/timing-asynchronous-gpu-work/exercises/',
  },
  {
    pairId: 'q05-solutions',
    factCheckDate: '2026-08-28',
    structure: 'review,solution-1,solution-2,solution-3,valid-alternatives,common-errors',
    resourceKind: 'solution-set',
    unitId: 'Q05-SOLUTIONS',
    prerequisites: 'Q05-EXERCISES',
    relatedUnits: 'Q05,LAB04,LAB05',
    hardwareGate: 'none',
    zh: '/correctness/timing-asynchronous-gpu-work/solutions/',
    en: '/en/correctness/timing-asynchronous-gpu-work/solutions/',
  },
  {
    pairId: 'ex01',
    factCheckDate: '2026-08-26',
    structure: 'purpose,project,report-contract,build,hardware,compatibility,evidence,expected-observations,sources',
    resourceKind: 'runnable-example',
    unitId: 'EX01',
    prerequisites: 'none',
    relatedUnits: 'O02,O03,O08,LAB01',
    exampleIds: 'EX01',
    canonicalExample: 'EX01',
    canonicalRanges: 'observation-model,version-query,device-inventory',
    hardwareGate: 'Build: host C++17 compiler for host-test and a CUDA Toolkit for the CUDA executable; runtime inventory: native Linux with CUDA Runtime access, where zero visible devices remains a valid observation',
    evidenceRuntime: 'Pending Hardware Verification',
    expectedObservations: '2 declared expectations',
    sourceCount: '5',
    sourceVersions: '11.8.0,12.9.2,13.3.1',
    zh: '/examples/environment-report/',
    en: '/en/examples/environment-report/',
  },
  {
    pairId: 'ex02',
    structure: 'purpose,project,correctness,build,compatibility,evidence,expected-observations,sources',
    resourceKind: 'runnable-example',
    unitId: 'EX02',
    prerequisites: 'none',
    relatedUnits: 'O02,O03,F01,LAB02',
    exampleIds: 'EX02',
    canonicalExample: 'EX02',
    canonicalRanges: 'kernel,error-checking,cpu-reference',
    evidenceCompilation: 'Compile-Checked',
    evidenceRuntime: 'Pending Hardware Verification',
    expectedObservations: '2 declared expectations',
    sourceCount: '11',
    sourceVersions: '11.8.0,12.9.2,13.3.1',
    zh: '/examples/vector-addition/',
    en: '/en/examples/vector-addition/',
  },
  {
    pairId: 'ex03',
    factCheckDate: '2026-08-26',
    structure: 'purpose,project,indexing-contract,lifecycle,correctness,build,compatibility,evidence,expected-observations,sources',
    resourceKind: 'runnable-example',
    unitId: 'EX03',
    prerequisites: 'F03',
    relatedUnits: 'F02,F03,F04,VIS02',
    exampleIds: 'EX03',
    canonicalExample: 'EX03',
    canonicalRanges: 'indexing-kernel,lifecycle,host-reference',
    hardwareGate: 'Build: x86-64 CPU with a host C++17 compiler for host-test and the selected CUDA Toolkit for CUDA build stages; runtime: native Linux, one CUDA GPU with compute capability 7.5 or newer, with the declared problem using under 8 GB',
    evidenceRuntime: 'Pending Hardware Verification',
    expectedObservations: '2 declared expectations',
    sourceCount: '10',
    sourceVersions: '11.8.0,12.9.2,13.3.1,13.3',
    zh: '/examples/multidimensional-indexing/',
    en: '/en/examples/multidimensional-indexing/',
  },
  {
    pairId: 'ex04',
    factCheckDate: '2026-08-26',
    structure: 'purpose,project,scenario-contract,error-lifecycle,indexing-kernels,host-verification,build,compatibility,evidence,expected-observations,sources',
    resourceKind: 'runnable-example',
    unitId: 'EX04',
    prerequisites: 'F05',
    relatedUnits: 'F03,F04,F05,LAB03',
    exampleIds: 'EX04',
    canonicalExample: 'EX04',
    canonicalRanges: 'error-lifecycle,indexing-kernels,host-verification',
    hardwareGate: 'Build: x86-64 CPU with a host C++17 compiler for host-test and the selected CUDA Toolkit for CUDA build stages; runtime: native Linux, one CUDA GPU with compute capability 7.5 or newer, with at most 140 bytes of declared problem allocation and under 8 GB',
    evidenceRuntime: 'Pending Hardware Verification',
    expectedObservations: '4 declared expectations',
    sourceCount: '12',
    sourceVersions: '11.8.0,12.9.2,13.3.1,13.3',
    zh: '/examples/error-handling-lifecycle/',
    en: '/en/examples/error-handling-lifecycle/',
  },
  {
    pairId: 'ex05',
    factCheckDate: '2026-08-27',
    structure: 'purpose,project,scenario-contract,access-kernel,scenario-loop,host-reference,build,compatibility,evidence,expected-observations,sources',
    resourceKind: 'runnable-example',
    unitId: 'EX05',
    prerequisites: 'M02',
    relatedUnits: 'VIS04',
    exampleIds: 'EX05',
    canonicalExample: 'EX05',
    canonicalRanges: 'access-kernel,scenario-loop',
    hardwareGate: 'Build: x86-64 CPU with a host C++17 compiler for host-test and the selected CUDA Toolkit for CUDA build stages; runtime: native Linux, one CUDA GPU with compute capability 7.5 or newer, with at most 3,068 bytes of declared device allocation and under 8 GB',
    evidenceCompilation: 'none',
    evidenceRuntime: 'Pending Hardware Verification',
    expectedObservations: '3 declared expectations',
    recordedObservations: 'none',
    sourceCount: '7',
    sourceVersions: '11.8.0,12.9.2,13.3.1,13.3',
    zh: '/examples/coalesced-strided-access/',
    en: '/en/examples/coalesced-strided-access/',
  },
  {
    pairId: 'ex06',
    factCheckDate: '2026-08-27',
    structure: 'purpose,project,layout-contract,shared-layouts,tiled-kernels,host-model,build,compatibility,evidence,expected-observations,sources',
    resourceKind: 'runnable-example',
    unitId: 'EX06',
    prerequisites: 'M03,M04',
    relatedUnits: 'VIS05',
    exampleIds: 'EX06',
    canonicalExample: 'EX06',
    canonicalRanges: 'shared-layouts,tiled-kernels',
    hardwareGate: 'Build: x86-64 CPU with a host C++17 compiler for host-test and the selected CUDA Toolkit for CUDA build stages; runtime: native Linux, one CUDA GPU with compute capability 7.5 or newer, with a conservative 8,576-byte global-plus-shared problem bound and under 8 GB',
    evidenceCompilation: 'none',
    evidenceRuntime: 'Pending Hardware Verification',
    expectedObservations: '3 declared expectations',
    recordedObservations: 'none',
    sourceCount: '7',
    sourceVersions: '11.8.0,12.9.2,13.3.1,13.3',
    zh: '/examples/shared-memory-tile-bank-padding/',
    en: '/en/examples/shared-memory-tile-bank-padding/',
  },
  {
    pairId: 'ex16',
    factCheckDate: '2026-08-28',
    structure: 'purpose,project,scenario-contract,memcheck,racecheck,initcheck,synccheck,host-utility,build,compatibility,evidence,expected-observations,sources',
    resourceKind: 'runnable-example',
    unitId: 'EX16',
    prerequisites: 'Q03,Q04',
    relatedUnits: 'LAB07',
    exampleIds: 'EX16',
    canonicalExample: 'EX16',
    canonicalRanges: 'memcheck-defect,memcheck-corrected,racecheck-defect,racecheck-corrected,initcheck-defect,initcheck-corrected,synccheck-defect,synccheck-corrected',
    hardwareGate: 'Build: x86-64 CPU with a host C++17 compiler for host-test and the selected CUDA Toolkit for all eight CUDA binaries; runtime: Native Linux only, one CUDA GPU with compute capability 7.5 or newer, with at most 128 bytes of declared global-plus-shared problem memory and under 8 GB',
    toolGate: 'Use Compute Sanitizer from the selected Toolkit Lane; run memcheck first; run each tool only against its matching one-case executable in a separate process',
    evidenceRuntime: 'Pending Hardware Verification',
    expectedObservations: '4 declared expectations',
    toolkitLanes: 'cuda-11.8,cuda-12.9,cuda-13.3',
    minimumComputeCapability: '7.5',
    maximumProblemMemoryBytes: '128',
    gpuCount: '1',
    permissions: 'one CUDA device; compiler, make, binary, and Compute Sanitizer execution; EX16 build/evidence-directory write/delete',
    sourceCount: '2',
    sourceVersions: '11.8.0,2026.2.1',
    zh: '/examples/sanitizer-defect-suite/',
    en: '/en/examples/sanitizer-defect-suite/',
  },
  {
    pairId: 'labs-index',
    factCheckDate: '2026-08-28',
    structure: 'scope,published-index,sequence,evidence-boundary',
    zh: '/labs/',
    en: '/en/labs/',
  },
  {
    pairId: 'lab01',
    factCheckDate: '2026-08-26',
    structure: 'contract,prerequisites,prepare,capture,build,inventory,reconcile,tier,compatibility,candidate-decision,evidence,cleanup,sources',
    resourceKind: 'lab',
    unitId: 'LAB01',
    prerequisites: 'O03,O08',
    relatedUnits: 'O02,O05,EX01',
    exampleIds: 'EX01',
    canonicalExample: 'EX01',
    canonicalRanges: 'observation-model,version-query,device-inventory',
    hardwareGate: 'Native Linux; one selected CUDA-capable NVIDIA GPU with compute capability 7.5 or newer for a Reference Environment candidate; preparation and build may be completed without a GPU',
    evidenceRuntime: 'Pending Hardware Verification',
    expectedObservations: '2 declared expectations',
    estimatedMinutes: '60',
    difficulty: 'introductory',
    toolkitLanes: 'cuda-11.8,cuda-12.9,cuda-13.3',
    minimumComputeCapability: '7.5',
    maximumProblemMemoryBytes: '0',
    gpuCount: '1',
    permissions: 'OS and NVIDIA driver metadata read; shell tools, nvidia-smi, NVCC, host compiler, make, and EX01 execution; local capture-record write/delete; no performance counters',
    sourceCount: '15',
    sourceVersions: '11.8.0,12.9.2,13.3.1,13.3,261.2,5.3,9.11,4.4.1',
    zh: '/labs/record-cuda-environment/',
    en: '/en/labs/record-cuda-environment/',
  },
  {
    pairId: 'lab02',
    structure: 'contract,prerequisites,prepare,predict,build,run,verify,observations,evidence,cleanup,sources',
    resourceKind: 'lab',
    unitId: 'LAB02',
    prerequisites: 'O03,F01',
    relatedUnits: 'O02,EX02,VIS01,VIS02',
    exampleIds: 'EX02',
    canonicalExample: 'EX02',
    canonicalRanges: 'error-checking,kernel,cpu-reference',
    hardwareGate: 'Native Linux; one CUDA GPU with compute capability 7.5 or newer; workload below 8 GB',
    evidenceCompilation: 'Compile-Checked',
    evidenceRuntime: 'Pending Hardware Verification',
    expectedObservations: '2 declared expectations',
    estimatedMinutes: '45',
    difficulty: 'introductory',
    toolkitLanes: 'cuda-11.8,cuda-12.9,cuda-13.3',
    minimumComputeCapability: '7.5',
    maximumProblemMemoryBytes: '1610612736',
    gpuCount: '1',
    permissions: 'CUDA device; compiler and binary execution; EX02 build-directory write/delete',
    sourceCount: '4',
    sourceVersions: '11.8.0,12.9.2,13.3.1',
    zh: '/labs/vector-addition/',
    en: '/en/labs/vector-addition/',
  },
  {
    pairId: 'lab03',
    factCheckDate: '2026-08-26',
    structure: 'contract,prerequisites,prepare,predict,build,fail,repair,verify,observations,evidence,cleanup,sources',
    resourceKind: 'lab',
    unitId: 'LAB03',
    prerequisites: 'F03,F05',
    relatedUnits: 'EX04,F08',
    exampleIds: 'EX04',
    canonicalExample: 'EX04',
    canonicalRanges: 'indexing-kernels,host-verification',
    hardwareGate: 'Native Linux only; one CUDA GPU with compute capability 7.5 or newer; fixed 7 x 5 indexing extent; one 35-element uint32_t output allocation of 140 bytes; workload below 8 GB',
    evidenceRuntime: 'Pending Hardware Verification',
    expectedObservations: '4 declared expectations',
    estimatedMinutes: '60',
    difficulty: 'intermediate',
    toolkitLanes: 'cuda-11.8,cuda-12.9,cuda-13.3',
    minimumComputeCapability: '7.5',
    maximumProblemMemoryBytes: '140',
    gpuCount: '1',
    permissions: 'CUDA device; compiler, make, and binary execution; EX04 build/evidence-directory write/delete',
    sourceCount: '7',
    sourceVersions: '11.8.0,12.9.2,13.3.1,13.3',
    zh: '/labs/break-and-repair-indexing/',
    en: '/en/labs/break-and-repair-indexing/',
  },
  {
    pairId: 'lab04',
    factCheckDate: '2026-08-28',
    structure: 'contract,prerequisites,canonical-project,manifest,source-review,build,correctness,measurement-plan,profiler-gate,collect,interpret,observations,evidence,cleanup,sources',
    resourceKind: 'lab',
    unitId: 'LAB04',
    prerequisites: 'M02,Q05',
    relatedUnits: 'EX05',
    exampleIds: 'EX05',
    canonicalExample: 'EX05',
    canonicalRanges: 'access-kernel,scenario-loop',
    hardwareGate: 'Native Linux only; one CUDA GPU with compute capability 7.5 or newer; Nsight Compute CLI and authorized performance-counter access; at most 3,068 bytes of problem allocation',
    evidenceRuntime: 'Pending Hardware Verification',
    expectedObservations: '3 declared expectations',
    estimatedMinutes: '90',
    difficulty: 'intermediate',
    toolkitLanes: 'cuda-11.8,cuda-12.9,cuda-13.3',
    minimumComputeCapability: '7.5',
    maximumProblemMemoryBytes: '3068',
    gpuCount: '1',
    permissions: 'CUDA device; compiler, make, binary, and ncu execution; build/report/log writes; administrator-approved performance-counter access',
    sourceCount: '8',
    sourceVersions: '11.8.0,12.9.2,13.3.1,2022.3.0,2025.2.1,2026.2.1,13.3',
    zh: '/labs/observe-coalescing/',
    en: '/en/labs/observe-coalescing/',
  },
  {
    pairId: 'lab05',
    factCheckDate: '2026-08-28',
    structure: 'contract,prerequisites,canonical-project,manifest,source-review,build,correctness,measurement-plan,profiler-gate,collect,interpret,observations,evidence,cleanup,sources',
    resourceKind: 'lab',
    unitId: 'LAB05',
    prerequisites: 'M04,Q05',
    relatedUnits: 'EX06',
    exampleIds: 'EX06',
    canonicalExample: 'EX06',
    canonicalRanges: 'shared-layouts,tiled-kernels',
    hardwareGate: 'Native Linux only; one CUDA GPU with compute capability 7.5 or newer; Nsight Compute CLI and authorized performance-counter access; at most 8,576 bytes of conservative global-plus-shared problem memory',
    evidenceRuntime: 'Pending Hardware Verification',
    expectedObservations: '3 declared expectations',
    estimatedMinutes: '90',
    difficulty: 'intermediate',
    toolkitLanes: 'cuda-11.8,cuda-12.9,cuda-13.3',
    minimumComputeCapability: '7.5',
    maximumProblemMemoryBytes: '8576',
    gpuCount: '1',
    permissions: 'CUDA device; compiler, make, binary, and ncu execution; build/report/log writes; administrator-approved performance-counter access',
    sourceCount: '8',
    sourceVersions: '11.8.0,12.9.2,13.3.1,2022.3.0,2025.2.1,2026.2.1,13.3',
    zh: '/labs/remove-shared-memory-bank-conflicts/',
    en: '/en/labs/remove-shared-memory-bank-conflicts/',
  },
  {
    pairId: 'lab07',
    factCheckDate: '2026-08-28',
    structure: 'contract,prerequisites,canonical-project,manifest,source-pairs,build,tool-gate,report-classes,correctness,isolated-runs,interpret,observations,evidence,cleanup,sources',
    resourceKind: 'lab',
    unitId: 'LAB07',
    prerequisites: 'Q03,Q04',
    relatedUnits: 'EX16',
    exampleIds: 'EX16',
    canonicalExample: 'EX16',
    canonicalRanges: 'memcheck-defect,memcheck-corrected,racecheck-defect,racecheck-corrected,initcheck-defect,initcheck-corrected,synccheck-defect,synccheck-corrected',
    hardwareGate: 'Native Linux only; one CUDA GPU with compute capability 7.5 or newer; the selected Toolkit Lane must provide Compute Sanitizer with all four required tools; at most 128 bytes of problem memory per process',
    evidenceRuntime: 'Pending Hardware Verification',
    expectedObservations: '4 declared expectations',
    estimatedMinutes: '120',
    difficulty: 'intermediate',
    toolkitLanes: 'cuda-11.8,cuda-12.9,cuda-13.3',
    minimumComputeCapability: '7.5',
    maximumProblemMemoryBytes: '128',
    gpuCount: '1',
    permissions: 'CUDA device; compiler, make, eight binaries, shell, and compute-sanitizer execution; one-process instrumentation; separate log/status writes; no performance counters',
    sourceCount: '5',
    sourceVersions: '11.8.0,12.9.2,13.3.1,2022.3,2025.2.1,2026.2.1',
    zh: '/labs/diagnose-four-sanitizer-failures/',
    en: '/en/labs/diagnose-four-sanitizer-failures/',
  },
  {
    pairId: 'visuals-index',
    factCheckDate: '2026-08-28',
    structure: 'scope,published-index,sequence,evidence-boundary',
    zh: '/visuals/',
    en: '/en/visuals/',
  },
  {
    pairId: 'vis01',
    structure: 'purpose,model,controls,scheduling-boundary,static-sequence,evidence-boundary,sources',
    resourceKind: 'visual-explainer',
    unitId: 'VIS01',
    prerequisites: 'none',
    relatedUnits: 'O01,O02,F01,F02',
    hardwareGate: 'None: deterministic browser model; no CUDA-capable system required',
    sourceCount: '9',
    sourceVersions: '13.3,7.2.4,0.41.7,2026-08-21,2026-01-12',
    zh: '/visuals/kernel-journey/',
    en: '/en/visuals/kernel-journey/',
  },
  {
    pairId: 'vis02',
    structure: 'purpose,model,dimensions,equations,bounds,static-examples,evidence-boundary,sources',
    resourceKind: 'visual-explainer',
    unitId: 'VIS02',
    prerequisites: 'none',
    relatedUnits: 'O01,O02,F01,F02,F03',
    hardwareGate: 'None: deterministic browser model; no CUDA-capable system required',
    sourceCount: '7',
    sourceVersions: '13.3,7.2.4,0.41.7,2026-08-21,2026-01-12',
    zh: '/visuals/indexing/',
    en: '/en/visuals/indexing/',
  },
  {
    pairId: 'vis03',
    factCheckDate: '2026-08-28',
    structure: 'purpose,predicate-masks,path-trace,independent-thread-scheduling,static-fallback,evidence-boundary,sources',
    resourceKind: 'visual-explainer',
    unitId: 'VIS03',
    prerequisites: 'none',
    relatedUnits: 'M06',
    hardwareGate: 'None: deterministic browser model; no CUDA-capable system required',
    evidenceCompilation: 'none',
    evidenceRuntime: 'none',
    expectedObservations: 'none',
    recordedObservations: 'none',
    sourceCount: '3',
    sourceVersions: '13.3,11.8.0,12.9.1',
    zh: '/visuals/warp-divergence/',
    en: '/en/visuals/warp-divergence/',
  },
  {
    pairId: 'vis04',
    factCheckDate: '2026-08-27',
    structure: 'purpose,input-contract,segment-model,accounting,static-fallback,evidence-boundary,sources',
    resourceKind: 'visual-explainer',
    unitId: 'VIS04',
    prerequisites: 'none',
    relatedUnits: 'M02,EX05',
    hardwareGate: 'None: deterministic browser model; no CUDA-capable system required',
    evidenceCompilation: 'none',
    evidenceRuntime: 'none',
    expectedObservations: 'none',
    recordedObservations: 'none',
    sourceCount: '4',
    sourceVersions: '13.3,13.3.1,11.8.0',
    zh: '/visuals/memory-transactions/',
    en: '/en/visuals/memory-transactions/',
  },
  {
    pairId: 'vis05',
    factCheckDate: '2026-08-27',
    structure: 'purpose,mapping-model,classification,padding,static-fallback,evidence-boundary,sources',
    resourceKind: 'visual-explainer',
    unitId: 'VIS05',
    prerequisites: 'none',
    relatedUnits: 'M04,EX06',
    hardwareGate: 'None: deterministic browser model; no CUDA-capable system required',
    evidenceCompilation: 'none',
    evidenceRuntime: 'none',
    expectedObservations: 'none',
    recordedObservations: 'none',
    sourceCount: '4',
    sourceVersions: '13.3,13.3.1,11.8.0',
    zh: '/visuals/shared-memory-banks/',
    en: '/en/visuals/shared-memory-banks/',
  },
  {
    pairId: 'vis06',
    factCheckDate: '2026-08-27',
    structure: 'purpose,catalog,filters,address-space-boundaries,static-fallback,evidence-boundary,sources',
    resourceKind: 'visual-explainer',
    unitId: 'VIS06',
    prerequisites: 'none',
    relatedUnits: 'M01',
    hardwareGate: 'None: deterministic browser model; no CUDA-capable system required',
    evidenceCompilation: 'none',
    evidenceRuntime: 'none',
    expectedObservations: 'none',
    recordedObservations: 'none',
    sourceCount: '4',
    sourceVersions: '13.3,13.3.1,11.8.0',
    zh: '/visuals/memory-hierarchy-lifetime/',
    en: '/en/visuals/memory-hierarchy-lifetime/',
  },
  {
    pairId: 'vis07',
    factCheckDate: '2026-08-28',
    structure: 'purpose,stream-order,event-dependencies,deterministic-trace,event-timing,static-fallback,evidence-boundary,sources',
    resourceKind: 'visual-explainer',
    unitId: 'VIS07',
    prerequisites: 'none',
    relatedUnits: 'M07,M08',
    hardwareGate: 'None: deterministic browser model; no CUDA-capable system required',
    evidenceCompilation: 'none',
    evidenceRuntime: 'none',
    expectedObservations: 'none',
    recordedObservations: 'none',
    sourceCount: '5',
    sourceVersions: '13.3,13.3.1,11.8.0,12.9.1',
    zh: '/visuals/stream-event-dependencies/',
    en: '/en/visuals/stream-event-dependencies/',
  },
  {
    pairId: 'practice-bank',
    factCheckDate: '2026-08-28',
    structure: 'use,lookup-index,entry-pb-r0-001,entry-pb-r0-002,entry-pb-r0-003,entry-pb-r0-004,entry-pb-r0-005,entry-pb-r1-001,entry-pb-r1-002,entry-pb-r1-003,entry-pb-r1-004,entry-pb-r1-005,entry-pb-r1-006,entry-pb-r1-007,entry-pb-r1-008,entry-pb-r1-009,entry-pb-r1-010,entry-pb-r1-011,entry-pb-r1-012,entry-pb-r1-013,entry-pb-r1-014,entry-pb-r1-015,entry-pb-r1-016,entry-pb-r1-017,entry-pb-r1-018,entry-pb-r1-019,entry-pb-r1-020,entry-pb-r1-021,entry-pb-r1-022,entry-pb-r1-023,entry-pb-r1-024,review',
    resourceKind: 'practice-bank',
    unitId: 'PB-R0',
    prerequisites: 'O02,O03,F01,F02,F03,F04,F05,F06,F07,F08,O04,O05,O06,O07,O08,M01,M02,M03,M04,M05,M06,M07,M08,Q01,Q03,Q04,Q05',
    relatedUnits: 'O02,O03,F01,F02,F03,F04,F05,F06,F07,F08,O04,O05,O06,O07,O08,M01,M02,M03,M04,M05,M06,M07,M08,Q01,Q03,Q04,Q05',
    zh: '/practice/',
    en: '/en/practice/',
  },
  {
    pairId: 'glossary',
    factCheckDate: '2026-08-28',
    structure: 'use,lookup-index,entries,maintenance',
    zh: '/glossary/',
    en: '/en/glossary/',
  },
  {
    pairId: 'sources-and-versions',
    factCheckDate: '2026-08-28',
    structure: 'scope,lookup-index,verified-interfaces,content-sources,review-record',
    zh: '/sources-and-versions/',
    en: '/en/sources-and-versions/',
  },
  {
    pairId: 'about',
    factCheckDate: '2026-08-28',
    structure: 'purpose,scope,author,feedback',
    zh: '/about/',
    en: '/en/about/',
  },
];

function metadata(document: Document, name: string) {
  return document.querySelector(`meta[name="${name}"]`)?.getAttribute('content');
}

describe('Publication Pairs', () => {
  it.each(
    publicationPairs.flatMap(({ pairId, factCheckDate = '2026-08-24', structure, zh, en, ...contract }) => [
      { route: zh, lang: 'zh-CN', counterpart: en, pairId, factCheckDate, structure, ...contract },
      { route: en, lang: 'en', counterpart: zh, pairId, factCheckDate, structure, ...contract },
    ]),
  )('publishes $route with aligned metadata and a direct counterpart', async ({ route, lang, counterpart, pairId, factCheckDate, structure, resourceKind, unitId, prerequisites, relatedUnits, exampleIds, canonicalExample, canonicalRanges, hardwareGate, toolGate, evidenceCompilation = 'none', evidenceRuntime = 'none', expectedObservations, recordedObservations = 'none', estimatedMinutes, difficulty, toolkitLanes, minimumComputeCapability, maximumProblemMemoryBytes, gpuCount, permissions, sourceCount, sourceVersions }) => {
    const document = await readRoute(route);

    expect(document.documentElement.lang).toBe(lang);
    expect(document.querySelector(`[data-locale-counterpart][href="${counterpart}"]`)).not.toBeNull();
    expect(metadata(document, 'cuda:pair-id')).toBe(pairId);
    expect(metadata(document, 'cuda:fact-check-date')).toBe(factCheckDate);
    expect(metadata(document, 'cuda:license')).toBe('CC-BY-4.0');
    expect(metadata(document, 'cuda:structure')).toBe(structure);
    if (resourceKind) expect(metadata(document, 'cuda:resource-kind')).toBe(resourceKind);
    if (unitId) expect(metadata(document, 'cuda:unit-id')).toBe(unitId);
    if (prerequisites) expect(metadata(document, 'cuda:prerequisites')).toBe(prerequisites);
    if (relatedUnits) expect(metadata(document, 'cuda:related-units')).toBe(relatedUnits);
    if (exampleIds) expect(metadata(document, 'cuda:example-ids')).toBe(exampleIds);
    if (canonicalExample) expect(metadata(document, 'cuda:canonical-example')).toBe(canonicalExample);
    if (canonicalRanges) expect(metadata(document, 'cuda:canonical-ranges')).toBe(canonicalRanges);
    if (hardwareGate) expect(metadata(document, 'cuda:hardware-gate')).toBe(hardwareGate);
    if (toolGate) expect(metadata(document, 'cuda:tool-gate')).toBe(toolGate);
    if (estimatedMinutes) expect(metadata(document, 'cuda:estimated-minutes')).toBe(estimatedMinutes);
    if (difficulty) expect(metadata(document, 'cuda:difficulty')).toBe(difficulty);
    if (toolkitLanes) expect(metadata(document, 'cuda:toolkit-lanes')).toBe(toolkitLanes);
    if (minimumComputeCapability) expect(metadata(document, 'cuda:minimum-compute-capability')).toBe(minimumComputeCapability);
    if (maximumProblemMemoryBytes) expect(metadata(document, 'cuda:maximum-problem-memory-bytes')).toBe(maximumProblemMemoryBytes);
    if (gpuCount) expect(metadata(document, 'cuda:gpu-count')).toBe(gpuCount);
    if (permissions) expect(metadata(document, 'cuda:permissions')).toBe(permissions);
    if (sourceCount) expect(metadata(document, 'cuda:source-count')).toBe(sourceCount);
    if (sourceVersions) expect(metadata(document, 'cuda:source-versions')).toBe(sourceVersions);
    if (resourceKind) {
      expect(metadata(document, 'cuda:evidence-compilation')).toBe(evidenceCompilation);
      expect(metadata(document, 'cuda:evidence-runtime')).toBe(evidenceRuntime);
      if (expectedObservations) expect(metadata(document, 'cuda:expected-observations')).toBe(expectedObservations);
      expect(metadata(document, 'cuda:recorded-observations')).toBe(recordedObservations);
    }
    expect(document.querySelector('link[rel="canonical"]')?.getAttribute('href')).toBe(`${siteOrigin}${route}`);

    const alternateLinks = new Map(
      [...document.querySelectorAll('link[rel="alternate"][hreflang]')].map((link) => [
        link.getAttribute('hreflang'),
        link.getAttribute('href'),
      ]),
    );
    const pair = publicationPairs.find((candidate) => candidate.pairId === pairId);
    expect(alternateLinks.get('zh-CN')).toBe(`${siteOrigin}${pair?.zh}`);
    expect(alternateLinks.get('en')).toBe(`${siteOrigin}${pair?.en}`);
    expect(alternateLinks.get('x-default')).toBe(`${siteOrigin}${pair?.zh}`);
  });

  it('discovers every source and built page as a complete pair', async () => {
    const sourceFiles = (await readdir(path.join(projectRoot, 'src/content/docs'), { recursive: true }))
      .map((file) => file.split(path.sep).join('/'))
      .filter((file) => /\.(?:md|mdx)$/.test(file));
    const rootFiles = sourceFiles.filter((file) => !file.startsWith('en/'));
    const englishFiles = sourceFiles.filter((file) => file.startsWith('en/')).map((file) => file.slice(3));

    expect(new Set(englishFiles)).toEqual(new Set(rootFiles));

    const sourceRoutes = new Set(
      sourceFiles.map((file) => {
        const stem = file.replace(/\.(?:md|mdx)$/, '').replace(/(?:^|\/)index$/, '');
        return stem ? `/${stem}/` : '/';
      }),
    );
    const builtRoutes = new Set(
      (await readdir(path.join(projectRoot, 'dist'), { recursive: true }))
        .map((file) => file.split(path.sep).join('/'))
        .filter((file) => file.endsWith('.html'))
        .map((file) => {
          const stem = file.replace(/(?:^|\/)index\.html$/, '').replace(/\.html$/, '');
          return stem ? `/${stem}/` : '/';
        }),
    );

    expect(builtRoutes).toEqual(sourceRoutes);
    expect(publicationPairs).toHaveLength(109);
    expect(sourceRoutes.size).toBe(218);
    expect(sourceRoutes.size).toBe(publicationPairs.length * 2);
    const publishedUnitIds = publicationPairs.flatMap(({ unitId }) => (unitId ? [unitId] : []));
    for (const absentUnitId of ['Q02', 'LAB06', 'EX07', 'EX08', 'EX09', 'EX10', 'EX11', 'EX12', 'EX13', 'EX14', 'EX15']) {
      expect(publishedUnitIds, absentUnitId).not.toContain(absentUnitId);
    }
  });

  it('publishes the closed, acyclic prerequisite graph with exact curriculum-map edges', async () => {
    const expectedPrerequisites = new Map<string, readonly string[]>([
      ['O01', []],
      ['O02', ['O01']],
      ['O03', ['O01']],
      ['O04', ['O01']],
      ['O05', ['O01']],
      ['O06', ['O01']],
      ['O07', ['O06']],
      ['O08', ['O02', 'O03', 'O05']],
      ['F01', ['O03']],
      ['F02', ['F01']],
      ['F03', ['F02']],
      ['F04', ['F01']],
      ['F05', ['F04']],
      ['F06', ['F02', 'O03']],
      ['F07', ['F04', 'F05']],
      ['F08', ['F02', 'F03', 'F06']],
      ['M01', ['F04', 'F06']],
      ['M02', ['M01', 'F03']],
      ['M03', ['M01', 'M02']],
      ['M04', ['M03']],
      ['M05', ['F02', 'M01']],
      ['M06', ['F02', 'M05']],
      ['M07', ['F05', 'M01']],
      ['M08', ['M07']],
      ['Q01', ['F04', 'O04']],
      ['Q03', ['F05', 'Q01']],
      ['Q04', ['M05', 'M06', 'Q03']],
      ['Q05', ['M08', 'Q01']],
      ['LAB01', ['O03', 'O08']],
      ['LAB02', ['O03', 'F01']],
      ['LAB03', ['F03', 'F05']],
      ['LAB04', ['M02', 'Q05']],
      ['LAB05', ['M04', 'Q05']],
      ['LAB07', ['Q03', 'Q04']],
      ['EX01', []],
      ['EX02', []],
      ['EX03', ['F03']],
      ['EX04', ['F05']],
      ['EX05', ['M02']],
      ['EX06', ['M03', 'M04']],
      ['EX16', ['Q03', 'Q04']],
      ['VIS01', []],
      ['VIS02', []],
      ['VIS03', []],
      ['VIS04', []],
      ['VIS05', []],
      ['VIS06', []],
      ['VIS07', []],
    ]);
    const publishedIds = new Set(publicationPairs.flatMap(({ unitId }) => (unitId ? [unitId] : [])));
    const graph = new Map<string, string[]>();

    for (const pair of publicationPairs.filter(({ unitId }) => expectedPrerequisites.has(unitId ?? ''))) {
      const document = await readRoute(pair.zh);
      const rawPrerequisites = metadata(document, 'cuda:prerequisites');
      const prerequisites = !rawPrerequisites || rawPrerequisites === 'none' ? [] : rawPrerequisites.split(',');

      expect(prerequisites, pair.unitId).toEqual(expectedPrerequisites.get(pair.unitId ?? ''));
      for (const prerequisite of prerequisites) expect(publishedIds, prerequisite).toContain(prerequisite);
      graph.set(pair.unitId ?? '', prerequisites);
    }

    const visited = new Set<string>();
    const active = new Set<string>();
    const visit = (unitId: string) => {
      expect(active, `cycle reaches ${unitId}`).not.toContain(unitId);
      if (visited.has(unitId)) return;
      active.add(unitId);
      for (const prerequisite of graph.get(unitId) ?? []) visit(prerequisite);
      active.delete(unitId);
      visited.add(unitId);
    };

    for (const unitId of graph.keys()) visit(unitId);
    expect(visited).toEqual(new Set(expectedPrerequisites.keys()));
  });
});

describe('published navigation', () => {
  it.each([
    {
      route: '/start/using-the-learning-site/',
      expected: [
        '/start/using-the-learning-site/',
        '/start/evidence-status/',
        '/start/environment-manifest/',
        '/start/cpp17-for-cuda/',
        '/start/linux-command-line/',
        '/start/architecture-refresher/',
        '/start/programmable-gpus/',
        '/start/reference-environment-candidate/',
        '/foundations/first-cuda-kernel/',
        '/foundations/execution-hierarchy/',
        '/foundations/multidimensional-indexing/',
        '/foundations/host-device-lifecycle/',
        '/foundations/asynchronous-errors/',
        '/foundations/compute-capability/',
        '/foundations/runtime-driver-api/',
        '/foundations/launch-geometry/',
        '/memory/address-spaces/',
        '/memory/coalescing-transactions/',
        '/memory/shared-memory-tiling/',
        '/memory/bank-conflicts-layouts/',
        '/memory/synchronization-scopes/',
        '/memory/warp-divergence-reconvergence/',
        '/memory/stream-ordering/',
        '/memory/event-dependencies-timing/',
        '/correctness/cpu-references-tolerances-invariants/',
        '/correctness/memcheck-invalid-memory-access/',
        '/correctness/racecheck-initcheck-synccheck/',
        '/correctness/timing-asynchronous-gpu-work/',
        '/examples/environment-report/',
        '/examples/vector-addition/',
        '/examples/multidimensional-indexing/',
        '/examples/error-handling-lifecycle/',
        '/examples/coalesced-strided-access/',
        '/examples/shared-memory-tile-bank-padding/',
        '/examples/sanitizer-defect-suite/',
        '/labs/',
        '/labs/record-cuda-environment/',
        '/labs/vector-addition/',
        '/labs/break-and-repair-indexing/',
        '/labs/observe-coalescing/',
        '/labs/remove-shared-memory-bank-conflicts/',
        '/labs/diagnose-four-sanitizer-failures/',
        '/visuals/',
        '/visuals/kernel-journey/',
        '/visuals/indexing/',
        '/visuals/warp-divergence/',
        '/visuals/memory-transactions/',
        '/visuals/shared-memory-banks/',
        '/visuals/memory-hierarchy-lifetime/',
        '/visuals/stream-event-dependencies/',
        '/practice/',
        '/glossary/',
        '/sources-and-versions/',
        '/about/',
      ],
    },
    {
      route: '/en/start/using-the-learning-site/',
      expected: [
        '/en/start/using-the-learning-site/',
        '/en/start/evidence-status/',
        '/en/start/environment-manifest/',
        '/en/start/cpp17-for-cuda/',
        '/en/start/linux-command-line/',
        '/en/start/architecture-refresher/',
        '/en/start/programmable-gpus/',
        '/en/start/reference-environment-candidate/',
        '/en/foundations/first-cuda-kernel/',
        '/en/foundations/execution-hierarchy/',
        '/en/foundations/multidimensional-indexing/',
        '/en/foundations/host-device-lifecycle/',
        '/en/foundations/asynchronous-errors/',
        '/en/foundations/compute-capability/',
        '/en/foundations/runtime-driver-api/',
        '/en/foundations/launch-geometry/',
        '/en/memory/address-spaces/',
        '/en/memory/coalescing-transactions/',
        '/en/memory/shared-memory-tiling/',
        '/en/memory/bank-conflicts-layouts/',
        '/en/memory/synchronization-scopes/',
        '/en/memory/warp-divergence-reconvergence/',
        '/en/memory/stream-ordering/',
        '/en/memory/event-dependencies-timing/',
        '/en/correctness/cpu-references-tolerances-invariants/',
        '/en/correctness/memcheck-invalid-memory-access/',
        '/en/correctness/racecheck-initcheck-synccheck/',
        '/en/correctness/timing-asynchronous-gpu-work/',
        '/en/examples/environment-report/',
        '/en/examples/vector-addition/',
        '/en/examples/multidimensional-indexing/',
        '/en/examples/error-handling-lifecycle/',
        '/en/examples/coalesced-strided-access/',
        '/en/examples/shared-memory-tile-bank-padding/',
        '/en/examples/sanitizer-defect-suite/',
        '/en/labs/',
        '/en/labs/record-cuda-environment/',
        '/en/labs/vector-addition/',
        '/en/labs/break-and-repair-indexing/',
        '/en/labs/observe-coalescing/',
        '/en/labs/remove-shared-memory-bank-conflicts/',
        '/en/labs/diagnose-four-sanitizer-failures/',
        '/en/visuals/',
        '/en/visuals/kernel-journey/',
        '/en/visuals/indexing/',
        '/en/visuals/warp-divergence/',
        '/en/visuals/memory-transactions/',
        '/en/visuals/shared-memory-banks/',
        '/en/visuals/memory-hierarchy-lifetime/',
        '/en/visuals/stream-event-dependencies/',
        '/en/practice/',
        '/en/glossary/',
        '/en/sources-and-versions/',
        '/en/about/',
      ],
    },
  ])('exposes only complete destinations from $route', async ({ route, expected }) => {
    const document = await readRoute(route);
    const hrefs = [...document.querySelectorAll('nav a[href]')].map((link) => link.getAttribute('href'));

    for (const href of expected) expect(hrefs).toContain(href);
  });

  it('contains no empty destinations or broken internal page and fragment links', async () => {
    const publishedRoutes = new Set(publicationPairs.flatMap(({ zh, en }) => [zh, en]));
    const documents = new Map<string, Document>();
    const destinationDocument = async (route: string) => {
      const cached = documents.get(route);
      if (cached) return cached;
      const document = await readRoute(route);
      documents.set(route, document);
      return document;
    };

    for (const route of publishedRoutes) {
      const document = await destinationDocument(route);
      const links = [...document.querySelectorAll('a[href]')].map((link) => link.getAttribute('href') ?? '');

      for (const href of links) {
        expect(href.trim(), `${route} contains an empty link`).not.toBe('');
        expect(href, `${route} contains a placeholder link`).not.toBe('#');
        if (!href.startsWith('/') && !href.startsWith('#')) continue;

        const destination = new URL(href, `${siteOrigin}${route}`);
        expect(publishedRoutes, `${route} links to ${destination.pathname}`).toContain(destination.pathname);
        if (!destination.hash) continue;

        const fragment = decodeURIComponent(destination.hash.slice(1));
        const target = await destinationDocument(destination.pathname);
        expect(target.getElementById(fragment), `${route} links to missing #${fragment} in ${destination.pathname}`).not.toBeNull();
      }
    }
  }, 15_000);

  it('uses valid HTTPS URLs for every external content link', async () => {
    for (const route of publicationPairs.flatMap(({ zh, en }) => [zh, en])) {
      const document = await readRoute(route);
      const externalLinks = [...document.querySelectorAll('a[href]')]
        .map((link) => link.getAttribute('href'))
        .filter((href): href is string => Boolean(href && !href.startsWith('/') && !href.startsWith('#')));

      for (const href of externalLinks) {
        const url = new URL(href);
        expect(url.protocol, href).toBe('https:');
        expect(url.hostname, href).not.toMatch(/^(?:localhost|127\.0\.0\.1)$/);
      }
    }
  });

  it('resolves every built page asset and metadata link', async () => {
    for (const route of publicationPairs.flatMap(({ zh, en }) => [zh, en])) {
      const document = await readRoute(route);
      const assetLinks = [
        ...document.querySelectorAll('script[src], link[href]'),
      ]
        .map((element) => element.getAttribute('src') ?? element.getAttribute('href'))
        .filter((href): href is string => Boolean(href?.startsWith('/')))
        .map((href) => href.split(/[?#]/)[0]);

      for (const href of assetLinks) {
        const target = path.join(projectRoot, 'dist', href.slice(1));
        await expect(readFile(target), `${route} references ${href}`).resolves.toBeInstanceOf(Buffer);
      }
    }
  });
});

describe('O01 content boundary', () => {
  it.each([
    {
      route: '/start/using-the-learning-site/',
      terms: ['学习单元', '可运行示例', '实验', '练习', '练习题库', '可视化讲解', '术语表'],
    },
    {
      route: '/en/start/using-the-learning-site/',
      terms: ['Learning Unit', 'Runnable Example', 'Lab', 'Exercise', 'Practice Bank', 'Visual Explainer', 'Glossary'],
    },
  ])('distinguishes resource types and points to the controlled evidence contract from $route', async ({ route, terms }) => {
    const document = await readRoute(route);
    const text = document.querySelector('main')?.textContent ?? '';

    for (const term of terms) expect(text).toContain(term);
    expect(text).toMatch(/O02/);
    expect(text).toMatch(/does not grant CUDA evidence|不会授予 CUDA 证据状态/);
  });
});

describe('search readiness', () => {
  it('builds independent Chinese and English Pagefind indexes', async () => {
    const entry = JSON.parse(
      await readFile(path.join(projectRoot, 'dist/pagefind/pagefind-entry.json'), 'utf8'),
    ) as { version: string; languages: Record<string, { page_count: number }> };

    expect(entry.version).toBe('1.5.2');
    expect(Object.keys(entry.languages).sort()).toEqual(['en', 'zh-cn']);
    expect(entry.languages.en.page_count).toBe(publicationPairs.length);
    expect(entry.languages['zh-cn'].page_count).toBe(publicationPairs.length);
  });
});
