// SPDX-License-Identifier: Apache-2.0
import {
  PUBLISHED_DESTINATIONS,
  type LocalizedText,
  type ResourceIndexRecord,
  type ResourceType,
} from './resource-index-model';

const localized = (zh: string, en: string): LocalizedText => ({ 'zh-CN': zh, en });
const same = (value: string): LocalizedText => localized(value, value);
const noHardware = localized('无；仅浏览静态记录。', 'None; static record lookup only.');
const noCudaHardware = localized('无；浏览器教学模型不需要 CUDA-capable 系统。', 'None; the browser teaching model requires no CUDA-capable system.');

function glossaryRecord(
  planningId: string,
  title: string,
  resourceType: ResourceType,
  relatedUnits: readonly string[],
  versionZh: string,
  versionEn: string,
  reviewedOn = '2026-08-26',
): ResourceIndexRecord {
  const anchor = planningId.toLowerCase();
  return {
    planningId,
    group: 'glossary',
    title: same(title),
    href: localized(`/glossary/#${anchor}`, `/en/glossary/#${anchor}`),
    resourceType,
    prerequisites: [],
    relatedUnits,
    hardwareGate: noHardware,
    versionGate: localized(versionZh, versionEn),
    reviewedOn,
  };
}

function sourceRecord(
  planningId: string,
  title: LocalizedText,
  resourceType: 'publishing-interface' | 'cuda-version-record' | 'cpp-language-record' | 'linux-tool-record' | 'architecture-record' | 'historical-record',
  relatedUnits: readonly string[],
  versionGate: LocalizedText,
  reviewedOn = '2026-08-24',
  sourceAccessDate = '2026-08-24',
): ResourceIndexRecord {
  const anchor = planningId.toLowerCase();
  return {
    planningId,
    group: 'sources',
    title,
    href: localized(`/sources-and-versions/#${anchor}`, `/en/sources-and-versions/#${anchor}`),
    resourceType,
    prerequisites: [],
    relatedUnits,
    hardwareGate: noHardware,
    versionGate,
    reviewedOn,
    sourceAccessDate,
  };
}

const lab01Destination = PUBLISHED_DESTINATIONS.LAB01;
const lab02Destination = PUBLISHED_DESTINATIONS.LAB02;
const lab03Destination = PUBLISHED_DESTINATIONS.LAB03;
const lab04Destination = PUBLISHED_DESTINATIONS.LAB04;
const lab05Destination = PUBLISHED_DESTINATIONS.LAB05;
const lab07Destination = PUBLISHED_DESTINATIONS.LAB07;
const vis01Destination = PUBLISHED_DESTINATIONS.VIS01;
const vis02Destination = PUBLISHED_DESTINATIONS.VIS02;
const vis03Destination = PUBLISHED_DESTINATIONS.VIS03;
const vis04Destination = PUBLISHED_DESTINATIONS.VIS04;
const vis05Destination = PUBLISHED_DESTINATIONS.VIS05;
const vis06Destination = PUBLISHED_DESTINATIONS.VIS06;
const vis07Destination = PUBLISHED_DESTINATIONS.VIS07;
const vis19Destination = PUBLISHED_DESTINATIONS.VIS19;
const vis20Destination = PUBLISHED_DESTINATIONS.VIS20;
const vis21Destination = PUBLISHED_DESTINATIONS.VIS21;
const vis22Destination = PUBLISHED_DESTINATIONS.VIS22;

const labs: readonly ResourceIndexRecord[] = [
  {
    planningId: 'LAB01',
    group: 'labs',
    title: lab01Destination.title,
    href: lab01Destination.href,
    resourceType: 'guided-lab',
    difficulty: 'introductory',
    prerequisites: lab01Destination.prerequisites,
    relatedUnits: ['O02', 'O05', 'EX01'],
    hardwareGate: localized(
      '原生 Linux；候选配置需要 1 个 compute capability 7.5 或更新的 CUDA-capable NVIDIA GPU；准备和构建不需要 GPU。',
      'Native Linux; a candidate needs one CUDA-capable NVIDIA GPU with compute capability 7.5 or newer; preparation and build need no GPU.',
    ),
    versionGate: localized(
      'CUDA Toolkit Lane 11.8.0、12.9.2 或 13.3.1；C++17。',
      'CUDA Toolkit Lane 11.8.0, 12.9.2, or 13.3.1; C++17.',
    ),
    evidence: {
      compilation: [],
      runtime: ['Pending Hardware Verification'],
    },
    reviewedOn: '2026-08-26',
    keywords: localized('环境清单 EX01 兼容性 GPU 能力层级 候选配置', 'Environment Manifest EX01 compatibility GPU Capability Tier candidate'),
  },
  {
    planningId: 'LAB02',
    group: 'labs',
    title: lab02Destination.title,
    href: lab02Destination.href,
    resourceType: 'guided-lab',
    difficulty: 'introductory',
    prerequisites: lab02Destination.prerequisites,
    relatedUnits: ['O02', 'EX02', 'VIS01', 'VIS02'],
    hardwareGate: localized(
      '原生 Linux；1 个 compute capability 7.5 或更新的 CUDA GPU；工作负载低于 8 GB。',
      'Native Linux; one CUDA GPU with compute capability 7.5 or newer; workload below 8 GB.',
    ),
    versionGate: localized(
      'CUDA Toolkit Lane 11.8.0、12.9.2 或 13.3.1；C++17。',
      'CUDA Toolkit Lane 11.8.0, 12.9.2, or 13.3.1; C++17.',
    ),
    evidence: {
      compilation: ['Compile-Checked'],
      runtime: ['Pending Hardware Verification'],
    },
    reviewedOn: '2026-08-24',
    keywords: localized('向量加法 manifest CPU reference 容差', 'vector addition manifest CPU reference tolerance'),
  },
  {
    planningId: 'LAB03',
    group: 'labs',
    title: lab03Destination.title,
    href: lab03Destination.href,
    resourceType: 'guided-lab',
    difficulty: 'intermediate',
    prerequisites: lab03Destination.prerequisites,
    relatedUnits: ['EX04', 'F08'],
    hardwareGate: localized(
      '原生 Linux；1 个 compute capability 7.5 或更新的 CUDA GPU；固定 7 x 5、35 个 uint32_t 的问题，共 140 bytes，低于 8 GB。',
      'Native Linux; one CUDA GPU with compute capability 7.5 or newer; fixed 7 x 5 problem of 35 uint32_t values (140 bytes), below 8 GB.',
    ),
    versionGate: localized(
      'CUDA Toolkit Lane 11.8.0、12.9.2 或 13.3.1；C++17。',
      'CUDA Toolkit Lane 11.8.0, 12.9.2, or 13.3.1; C++17.',
    ),
    evidence: {
      compilation: [],
      runtime: ['Pending Hardware Verification'],
    },
    reviewedOn: '2026-08-26',
    keywords: localized('错误生命周期 索引修复 host comparison EX04', 'error lifecycle indexing repair host comparison EX04'),
  },
  {
    planningId: 'LAB04',
    group: 'labs',
    title: lab04Destination.title,
    href: lab04Destination.href,
    resourceType: 'guided-lab',
    difficulty: 'intermediate',
    prerequisites: lab04Destination.prerequisites,
    relatedUnits: ['EX05'],
    hardwareGate: localized(
      '仅限原生 Linux；1 个 compute capability 7.5 或更新的 CUDA GPU；Nsight Compute CLI 与获准的性能计数器访问；问题 allocation 最多 3,068 bytes。',
      'Native Linux only; one CUDA GPU with compute capability 7.5 or newer; Nsight Compute CLI and authorized performance-counter access; at most 3,068 bytes of problem allocation.',
    ),
    versionGate: localized(
      'CUDA Toolkit Lane 11.8.0、12.9.2 或 13.3.1；C++17；匹配的 Nsight Compute 2022.3.0、2025.2.1 或 2026.2.1。',
      'CUDA Toolkit Lane 11.8.0, 12.9.2, or 13.3.1; C++17; matching Nsight Compute 2022.3.0, 2025.2.1, or 2026.2.1.',
    ),
    evidence: {
      compilation: [],
      runtime: ['Pending Hardware Verification'],
    },
    reviewedOn: '2026-08-28',
    keywords: localized('EX05 合并访问 Nsight Compute profiler 原始样本', 'EX05 coalescing Nsight Compute profiler raw samples'),
  },
  {
    planningId: 'LAB05',
    group: 'labs',
    title: lab05Destination.title,
    href: lab05Destination.href,
    resourceType: 'guided-lab',
    difficulty: 'intermediate',
    prerequisites: lab05Destination.prerequisites,
    relatedUnits: ['EX06'],
    hardwareGate: localized(
      '仅限原生 Linux；1 个 compute capability 7.5 或更新的 CUDA GPU；Nsight Compute CLI 与获准的性能计数器访问；保守计算的全局加共享问题内存最多 8,576 bytes。',
      'Native Linux only; one CUDA GPU with compute capability 7.5 or newer; Nsight Compute CLI and authorized performance-counter access; at most 8,576 bytes of conservative global-plus-shared problem memory.',
    ),
    versionGate: localized(
      'CUDA Toolkit Lane 11.8.0、12.9.2 或 13.3.1；C++17；匹配的 Nsight Compute 2022.3.0、2025.2.1 或 2026.2.1。',
      'CUDA Toolkit Lane 11.8.0, 12.9.2, or 13.3.1; C++17; matching Nsight Compute 2022.3.0, 2025.2.1, or 2026.2.1.',
    ),
    evidence: {
      compilation: [],
      runtime: ['Pending Hardware Verification'],
    },
    reviewedOn: '2026-08-28',
    keywords: localized('EX06 shared memory bank conflict padding Nsight Compute', 'EX06 shared memory bank conflict padding Nsight Compute'),
  },
  {
    planningId: 'LAB07',
    group: 'labs',
    title: lab07Destination.title,
    href: lab07Destination.href,
    resourceType: 'guided-lab',
    difficulty: 'intermediate',
    prerequisites: lab07Destination.prerequisites,
    relatedUnits: ['EX16'],
    hardwareGate: localized(
      '仅限原生 Linux；1 个 compute capability 7.5 或更新的 CUDA GPU；selected Toolkit Lane 必须提供全部四种 Compute Sanitizer tool；每个进程的问题内存最多 128 bytes。',
      'Native Linux only; one CUDA GPU with compute capability 7.5 or newer; the selected Toolkit Lane must provide Compute Sanitizer with all four required tools; at most 128 bytes of problem memory per process.',
    ),
    versionGate: localized(
      'CUDA Toolkit Lane 11.8.0、12.9.2 或 13.3.1；C++17；Compute Sanitizer 2022.3、2025.2.1 或 2026.2.1。',
      'CUDA Toolkit Lane 11.8.0, 12.9.2, or 13.3.1; C++17; Compute Sanitizer 2022.3, 2025.2.1, or 2026.2.1.',
    ),
    evidence: {
      compilation: [],
      runtime: ['Pending Hardware Verification'],
    },
    reviewedOn: '2026-08-28',
    keywords: localized('EX16 memcheck racecheck initcheck synccheck 隔离日志', 'EX16 memcheck racecheck initcheck synccheck isolated logs'),
  },
];

const practice: readonly ResourceIndexRecord[] = [
  {
    planningId: 'PB-R0-001',
    group: 'practice',
    title: localized('修复 Evidence Status 记录', 'Repair an Evidence Status record'),
    href: localized('/practice/#pb-r0-001', '/en/practice/#pb-r0-001'),
    resourceType: 'mental-model',
    difficulty: 'foundational',
    prerequisites: ['O02'],
    relatedUnits: ['O02'],
    hardwareGate: localized('无；只分析文本记录。', 'None; analyse a text record only.'),
    versionGate: localized('O02 证据合同；NVCC 13.3.1 编译与运行阶段。', 'O02 evidence contract; NVCC 13.3.1 compile and run phases.'),
    reviewedOn: '2026-08-26',
  },
  {
    planningId: 'PB-R0-002',
    group: 'practice',
    title: localized('补全 manifest 并修复支持边界', 'Complete a manifest and repair a support claim'),
    href: localized('/practice/#pb-r0-002', '/en/practice/#pb-r0-002'),
    resourceType: 'correctness-debugging',
    difficulty: 'foundational',
    prerequisites: ['O03'],
    relatedUnits: ['O03'],
    hardwareGate: localized('无；使用假设记录，不运行 CUDA。', 'None; use a hypothetical record and run no CUDA.'),
    versionGate: localized('O03 支持合同；CUDA 11+ 组件版本与兼容性边界。', 'O03 support contract; CUDA 11+ component versioning and compatibility boundaries.'),
    reviewedOn: '2026-08-26',
  },
  {
    planningId: 'PB-R0-003',
    group: 'practice',
    title: localized('在运行前审查索引预测', 'Review an indexing prediction before execution'),
    href: localized('/practice/#pb-r0-003', '/en/practice/#pb-r0-003'),
    resourceType: 'concepts-implementation',
    difficulty: 'foundational',
    prerequisites: ['F01'],
    relatedUnits: ['F01', 'VIS02'],
    hardwareGate: localized('无；只做静态推理。', 'None; use static reasoning only.'),
    versionGate: localized('CUDA Programming Guide v13.3 索引模型。', 'CUDA Programming Guide v13.3 indexing model.'),
    reviewedOn: '2026-08-26',
  },
  {
    planningId: 'PB-R0-004',
    group: 'practice',
    title: localized('修复不完整的错误与正确性边界', 'Repair incomplete error and correctness boundaries'),
    href: localized('/practice/#pb-r0-004', '/en/practice/#pb-r0-004'),
    resourceType: 'correctness-debugging',
    difficulty: 'foundational',
    prerequisites: ['F01'],
    relatedUnits: ['F01', 'O02', 'EX02'],
    hardwareGate: localized('无；审查假设执行流程。', 'None; review a hypothetical execution flow.'),
    versionGate: localized('EX02 正确性合同；CUDA Runtime API 13.3.1。', 'EX02 correctness contract; CUDA Runtime API 13.3.1.'),
    reviewedOn: '2026-08-26',
  },
  {
    planningId: 'PB-R0-005',
    group: 'practice',
    title: localized('审查一份 LAB02 证据申请', 'Review a LAB02 evidence request'),
    href: localized('/practice/#pb-r0-005', '/en/practice/#pb-r0-005'),
    resourceType: 'evidence-review',
    difficulty: 'foundational',
    prerequisites: ['O02', 'O03', 'F01'],
    relatedUnits: ['F01', 'O02', 'O03', 'LAB02'],
    hardwareGate: localized('无；审查文本记录，不运行 CUDA。', 'None; review a text record and run no CUDA.'),
    versionGate: localized('LAB02 的 CUDA 11.8、12.9 与 13.3 Toolkit Lane。', 'LAB02 CUDA 11.8, 12.9, and 13.3 Toolkit Lanes.'),
    reviewedOn: '2026-08-26',
  },
  {
    planningId: 'PB-R1-001',
    group: 'practice',
    title: localized('修复生命周期、构建与错误边界', 'Repair lifetime, build, and error boundaries'),
    href: localized('/practice/#pb-r1-001', '/en/practice/#pb-r1-001'),
    resourceType: 'correctness-debugging',
    difficulty: 'intermediate',
    prerequisites: ['O04'],
    relatedUnits: ['O04'],
    hardwareGate: localized('无；只审查 source 与 build design。', 'None; review source and build design only.'),
    versionGate: localized('ISO C++17；CUDA C++ v13.3 host/device 与 error boundary。', 'ISO C++17; CUDA C++ v13.3 host/device and error boundaries.'),
    reviewedOn: '2026-08-26',
  },
  {
    planningId: 'PB-R1-002',
    group: 'practice',
    title: localized('修复隐藏 producer failure 的构建记录', 'Repair a build record that hides producer failure'),
    href: localized('/practice/#pb-r1-002', '/en/practice/#pb-r1-002'),
    resourceType: 'correctness-debugging',
    difficulty: 'intermediate',
    prerequisites: ['O05'],
    relatedUnits: ['O05', 'LAB01'],
    hardwareGate: localized('无；只设计记录。', 'None; design the record only.'),
    versionGate: localized('GNU Bash 5.3；Coreutils 9.11；GNU Make 4.4.1。', 'GNU Bash 5.3; Coreutils 9.11; GNU Make 4.4.1.'),
    reviewedOn: '2026-08-26',
  },
  {
    planningId: 'PB-R1-003',
    group: 'practice',
    title: localized('辨析架构声明并计算有边界的算术强度', 'Classify architecture claims and calculate bounded arithmetic intensity'),
    href: localized('/practice/#pb-r1-003', '/en/practice/#pb-r1-003'),
    resourceType: 'concepts-implementation',
    difficulty: 'intermediate',
    prerequisites: ['O06'],
    relatedUnits: ['O06', 'O07'],
    hardwareGate: localized('无；只做静态分类与算术。', 'None; use static classification and arithmetic only.'),
    versionGate: localized('CUDA Programming Guide 与 Best Practices Guide v13.3；2009 Roofline model。', 'CUDA Programming Guide and Best Practices Guide v13.3; 2009 Roofline model.'),
    reviewedOn: '2026-08-26',
  },
  {
    planningId: 'PB-R1-004',
    group: 'practice',
    title: localized('用抽象历史替换产品年表', 'Replace a product chronology with abstraction history'),
    href: localized('/practice/#pb-r1-004', '/en/practice/#pb-r1-004'),
    resourceType: 'mental-model',
    difficulty: 'intermediate',
    prerequisites: ['O07'],
    relatedUnits: ['O06', 'O07'],
    hardwareGate: localized('无；只重写概念并标注来源。', 'None; rewrite concepts and attribute sources only.'),
    versionGate: localized('Khronos ARB program specs；BrookGPU 2004；CUDA 2008 primary source。', 'Khronos ARB program specs; BrookGPU 2004; CUDA 2008 primary source.'),
    reviewedOn: '2026-08-26',
  },
  {
    planningId: 'PB-R1-005',
    group: 'practice',
    title: localized('审查不完整的基准环境候选配置', 'Triage an incomplete Reference Environment candidate'),
    href: localized('/practice/#pb-r1-005', '/en/practice/#pb-r1-005'),
    resourceType: 'evidence-review',
    difficulty: 'intermediate',
    prerequisites: ['O08'],
    relatedUnits: ['O02', 'O03', 'O05', 'O08', 'EX01', 'LAB01'],
    hardwareGate: localized('无；审查候选材料，不运行 CUDA。', 'None; review candidate material and run no CUDA.'),
    versionGate: localized('CUDA 11.8.0、12.9.2、13.3.1 selected Lane compatibility facts。', 'Selected CUDA 11.8.0, 12.9.2, and 13.3.1 Lane compatibility facts.'),
    reviewedOn: '2026-08-26',
  },
  {
    planningId: 'PB-R1-006',
    group: 'practice',
    title: localized('预测二维 thread 所有权与 warp/lane 身份', 'Predict 2D thread ownership and warp/lane identity'),
    href: localized('/practice/#pb-r1-006', '/en/practice/#pb-r1-006'),
    resourceType: 'concepts-implementation',
    difficulty: 'intermediate',
    prerequisites: ['F02'],
    relatedUnits: ['F02', 'VIS01', 'VIS02', 'EX03'],
    hardwareGate: localized('无；只做静态推理。', 'None; use static reasoning only.'),
    versionGate: localized('CUDA Programming Guide v13.3 execution hierarchy。', 'CUDA Programming Guide v13.3 execution hierarchy.'),
    reviewedOn: '2026-08-26',
  },
  {
    planningId: 'PB-R1-007',
    group: 'practice',
    title: localized('修复三维 bounds 与展平缺陷', 'Repair 3D bounds and flattening defects'),
    href: localized('/practice/#pb-r1-007', '/en/practice/#pb-r1-007'),
    resourceType: 'correctness-debugging',
    difficulty: 'intermediate',
    prerequisites: ['F03'],
    relatedUnits: ['F03', 'VIS02', 'EX03'],
    hardwareGate: localized('无；host-only 检查不运行 CUDA。', 'None; host-only checks run no CUDA.'),
    versionGate: localized('CUDA Programming Guide v13.3；EX03 C++17 correctness contract。', 'CUDA Programming Guide v13.3; EX03 C++17 correctness contract.'),
    reviewedOn: '2026-08-26',
  },
  {
    planningId: 'PB-R1-008',
    group: 'practice',
    title: localized('修复资源生命周期与证据声明', 'Repair resource lifecycle and evidence claims'),
    href: localized('/practice/#pb-r1-008', '/en/practice/#pb-r1-008'),
    resourceType: 'evidence-review',
    difficulty: 'intermediate',
    prerequisites: ['F04'],
    relatedUnits: ['F04', 'O02', 'O04', 'EX03'],
    hardwareGate: localized('无；审查静态 lifecycle 与 evidence record。', 'None; review a static lifecycle and evidence record.'),
    versionGate: localized('CUDA Runtime API 13.3.1；EX03 runtime 待硬件验证。', 'CUDA Runtime API 13.3.1; EX03 runtime remains Pending Hardware Verification.'),
    reviewedOn: '2026-08-26',
  },
  {
    planningId: 'PB-R1-009',
    group: 'practice',
    title: localized('修复 stale、immediate 与 deferred error 归因', 'Repair stale, immediate, and deferred error attribution'),
    href: localized('/practice/#pb-r1-009', '/en/practice/#pb-r1-009'),
    resourceType: 'correctness-debugging',
    difficulty: 'intermediate',
    prerequisites: ['F05'],
    relatedUnits: ['F05', 'VIS19', 'EX04', 'LAB03'],
    hardwareGate: localized('无；只审查静态 error-lifecycle 记录。', 'None; review a static error-lifecycle record only.'),
    versionGate: localized('Runtime API 11.8.0、12.9.2 archive/页面标签 12.9.1 与 13.3.1。', 'Runtime API 11.8.0, 12.9.2 archive/page label 12.9.1, and 13.3.1.'),
    reviewedOn: '2026-08-26',
  },
  {
    planningId: 'PB-R1-010',
    group: 'practice',
    title: localized('重建 capability 到 compiler target 的决策', 'Rebuild a capability-to-compiler-target decision'),
    href: localized('/practice/#pb-r1-010', '/en/practice/#pb-r1-010'),
    resourceType: 'concepts-implementation',
    difficulty: 'intermediate',
    prerequisites: ['F06'],
    relatedUnits: ['F06', 'VIS20', 'O03', 'F08'],
    hardwareGate: localized('无；只审查 capability、limit 与 target 记录。', 'None; review capability, limit, and target records only.'),
    versionGate: localized('CUDA Programming Guide v13.3；NVCC 11.8.0、12.9.2 与 13.3.1。', 'CUDA Programming Guide v13.3; NVCC 11.8.0, 12.9.2, and 13.3.1.'),
    reviewedOn: '2026-08-26',
  },
  {
    planningId: 'PB-R1-011',
    group: 'practice',
    title: localized('修复 Runtime/Driver 所有权与错误边界', 'Repair Runtime/Driver ownership and error boundaries'),
    href: localized('/practice/#pb-r1-011', '/en/practice/#pb-r1-011'),
    resourceType: 'correctness-debugging',
    difficulty: 'intermediate',
    prerequisites: ['F07'],
    relatedUnits: ['F04', 'F05', 'F07', 'VIS21', 'EX04'],
    hardwareGate: localized('无；只审查混合 API 设计，不运行 CUDA。', 'None; review a mixed-API design and run no CUDA.'),
    versionGate: localized('Runtime/Driver API 11.8.0、12.9.2 archive/页面标签 12.9.1 与 13.3.1。', 'Runtime/Driver APIs 11.8.0, 12.9.2 archive/page label 12.9.1, and 13.3.1.'),
    reviewedOn: '2026-08-26',
  },
  {
    planningId: 'PB-R1-012',
    group: 'practice',
    title: localized('在测量前选择合法 block shape', 'Select legal block shapes before measurement'),
    href: localized('/practice/#pb-r1-012', '/en/practice/#pb-r1-012'),
    resourceType: 'concepts-implementation',
    difficulty: 'intermediate',
    prerequisites: ['F08'],
    relatedUnits: ['F03', 'F06', 'F08', 'VIS22', 'LAB03'],
    hardwareGate: localized('无；只做静态 geometry 与 resource 检查。', 'None; perform static geometry and resource checks only.'),
    versionGate: localized('CUDA Programming Guide v13.3；Runtime API 13.3.1 device/function properties。', 'CUDA Programming Guide v13.3; Runtime API 13.3.1 device/function properties.'),
    reviewedOn: '2026-08-26',
  },
  {
    planningId: 'PB-R1-013',
    group: 'practice',
    title: localized('按所有权、作用域与生命周期分类六种 memory object', 'Classify six memory objects by ownership, scope, and lifetime'),
    href: localized('/practice/#pb-r1-013', '/en/practice/#pb-r1-013'),
    resourceType: 'mental-model',
    difficulty: 'intermediate',
    prerequisites: ['M01'],
    relatedUnits: ['M01', 'VIS06', 'F04', 'F06'],
    hardwareGate: localized('无；只审查静态 object inventory。', 'None; review a static object inventory only.'),
    versionGate: localized(
      'Programming Guide v13.3 与 Runtime API 13.3.1；11.8.0 和 12.9.1 owner 文档用于 selected Lane 边界。',
      'Programming Guide v13.3 and Runtime API 13.3.1; 11.8.0 and 12.9.1 owner documentation bound the selected Lanes.',
    ),
    reviewedOn: '2026-08-27',
  },
  {
    planningId: 'PB-R1-014',
    group: 'practice',
    title: localized('推导 aligned、offset 与 stride 的 segment set', 'Derive aligned, offset, and stride segment sets'),
    href: localized('/practice/#pb-r1-014', '/en/practice/#pb-r1-014'),
    resourceType: 'concepts-implementation',
    difficulty: 'intermediate',
    prerequisites: ['M02'],
    relatedUnits: ['M02', 'VIS04', 'EX05', 'F03'],
    hardwareGate: localized('无；只做静态 address 与 segment 算术。', 'None; perform static address and segment arithmetic only.'),
    versionGate: localized(
      'CC 6.0+ 的 naturally aligned 32-byte segment 模型；本站 Stable Curriculum 为 CC 7.5+。',
      'Naturally aligned 32-byte segment model for CC 6.0+; the site Stable Curriculum is CC 7.5+.',
    ),
    reviewedOn: '2026-08-27',
  },
  {
    planningId: 'PB-R1-015',
    group: 'practice',
    title: localized('修复 edge tile 的 barrier participation 与 reuse', 'Repair edge-tile barrier participation and reuse'),
    href: localized('/practice/#pb-r1-015', '/en/practice/#pb-r1-015'),
    resourceType: 'correctness-debugging',
    difficulty: 'intermediate',
    prerequisites: ['M03'],
    relatedUnits: ['M03', 'EX06', 'M01', 'M02'],
    hardwareGate: localized('无；只审查和修复源码，不运行 CUDA。', 'None; review and repair source without running CUDA.'),
    versionGate: localized('Programming Guide v13.3 的 shared-memory 与 thread-block synchronization 合同；portable C++17。', 'Programming Guide v13.3 shared-memory and thread-block synchronization contract; portable C++17.'),
    reviewedOn: '2026-08-27',
  },
  {
    planningId: 'PB-R1-016',
    group: 'practice',
    title: localized('区分 broadcast、bank conflict 与 padding transform', 'Distinguish broadcast, bank conflicts, and padding transforms'),
    href: localized('/practice/#pb-r1-016', '/en/practice/#pb-r1-016'),
    resourceType: 'concepts-implementation',
    difficulty: 'intermediate',
    prerequisites: ['M04'],
    relatedUnits: ['M04', 'VIS05', 'EX06', 'M03'],
    hardwareGate: localized('无；只做静态 word-address 与 bank 映射。', 'None; perform static word-address and bank mapping only.'),
    versionGate: localized('Best Practices Guide v13.3；selected CC 7.5+ 的 32-bank、32-bit word 教学 fixture。', 'Best Practices Guide v13.3; selected CC 7.5+ teaching fixture with 32 banks and 32-bit words.'),
    reviewedOn: '2026-08-27',
  },
  {
    planningId: 'PB-R1-017',
    group: 'practice',
    title: localized('按参与者与通信范围选择同步作用域', 'Select synchronization scope from participants and communication'),
    href: localized('/practice/#pb-r1-017', '/en/practice/#pb-r1-017'),
    resourceType: 'concepts-implementation',
    difficulty: 'intermediate',
    prerequisites: ['M05'],
    relatedUnits: ['F02', 'M01', 'M05'],
    hardwareGate: localized('无；只审查静态同步协议，不运行 CUDA。', 'None; review a static synchronization protocol and run no CUDA.'),
    versionGate: localized(
      'CUDA Programming Guide v13.3；11.8.0 与 12.9.1 archive 用于 scope 与 fence 边界。',
      'CUDA Programming Guide v13.3; the 11.8.0 and 12.9.1 archives bound scope and fence semantics.',
    ),
    reviewedOn: '2026-08-28',
  },
  {
    planningId: 'PB-R1-018',
    group: 'practice',
    title: localized('修复不安全的 warp collective', 'Repair an unsafe warp collective'),
    href: localized('/practice/#pb-r1-018', '/en/practice/#pb-r1-018'),
    resourceType: 'correctness-debugging',
    difficulty: 'intermediate',
    prerequisites: ['M06'],
    relatedUnits: ['F02', 'M05', 'M06', 'VIS03'],
    hardwareGate: localized('无；只推导 predicate、mask 与同步边，不运行 CUDA。', 'None; derive predicates, masks, and synchronization edges without running CUDA.'),
    versionGate: localized(
      'CUDA Programming Guide v13.3 与 CC 7.0+ Independent Thread Scheduling；11.8.0/12.9.1 archive 交叉核对。',
      'CUDA Programming Guide v13.3 and CC 7.0+ Independent Thread Scheduling, cross-checked at the 11.8.0 and 12.9.1 archives.',
    ),
    reviewedOn: '2026-08-28',
  },
  {
    planningId: 'PB-R1-019',
    group: 'practice',
    title: localized('修复两条 stream 的 partial order 与 lifetime', 'Repair a two-stream partial order and lifetime'),
    href: localized('/practice/#pb-r1-019', '/en/practice/#pb-r1-019'),
    resourceType: 'correctness-debugging',
    difficulty: 'intermediate',
    prerequisites: ['M07'],
    relatedUnits: ['F05', 'M01', 'M07', 'VIS07'],
    hardwareGate: localized('无；只审查静态 stream graph 与 allocation lifetime。', 'None; review a static stream graph and allocation lifetime.'),
    versionGate: localized(
      'CUDA Programming Guide v13.3、Runtime API v13.3.1，以及 11.8.0/12.9.1 stream owner documentation。',
      'CUDA Programming Guide v13.3, Runtime API v13.3.1, and 11.8.0/12.9.1 stream owner documentation.',
    ),
    reviewedOn: '2026-08-28',
  },
  {
    planningId: 'PB-R1-020',
    group: 'practice',
    title: localized('审查 event dependency 与 device-time evidence', 'Review event dependencies and device-time evidence'),
    href: localized('/practice/#pb-r1-020', '/en/practice/#pb-r1-020'),
    resourceType: 'evidence-review',
    difficulty: 'intermediate',
    prerequisites: ['M08'],
    relatedUnits: ['O02', 'M07', 'M08', 'VIS07'],
    hardwareGate: localized('无；只审查 event generation、依赖与计时证据。', 'None; review event generations, dependencies, and timing evidence only.'),
    versionGate: localized(
      'CUDA Programming Guide v13.3、Runtime API v13.3.1，以及 11.8.0/12.9.1 event owner documentation。',
      'CUDA Programming Guide v13.3, Runtime API v13.3.1, and 11.8.0/12.9.1 event owner documentation.',
    ),
    reviewedOn: '2026-08-28',
  },
  {
    planningId: 'PB-R1-021',
    group: 'practice',
    title: localized('设计独立 CPU reference、容差与不变量', 'Design an independent CPU reference, tolerances, and invariants'),
    href: localized('/practice/#pb-r1-021', '/en/practice/#pb-r1-021'),
    resourceType: 'correctness-debugging',
    difficulty: 'intermediate',
    prerequisites: ['Q01'],
    relatedUnits: ['F04', 'O04', 'Q01'],
    hardwareGate: localized('无；只设计和审查静态 correctness oracle，不运行 CUDA。', 'None; design and review a static correctness oracle without running CUDA.'),
    versionGate: localized(
      'CUDA C++ Best Practices Guide 与 Floating Point and IEEE 754 的 current v13.3、11.8.0 和 12.9.1 owner documentation。',
      'Current v13.3, 11.8.0, and 12.9.1 owner documentation for the CUDA C++ Best Practices Guide and Floating Point and IEEE 754.',
    ),
    reviewedOn: '2026-08-28',
    keywords: localized('CPU reference absolute tolerance relative tolerance invariant correctness oracle', 'CPU reference absolute tolerance relative tolerance invariant correctness oracle'),
  },
  {
    planningId: 'PB-R1-022',
    group: 'practice',
    title: localized('审查 lane-safe memcheck 计划', 'Audit a lane-safe memcheck plan'),
    href: localized('/practice/#pb-r1-022', '/en/practice/#pb-r1-022'),
    resourceType: 'correctness-debugging',
    difficulty: 'intermediate',
    prerequisites: ['Q03'],
    relatedUnits: ['F05', 'Q01', 'Q03', 'EX16', 'LAB07'],
    hardwareGate: localized('无；只审查命令、覆盖范围与预期 report class，不运行 Compute Sanitizer。', 'None; review commands, coverage, and expected report classes without running Compute Sanitizer.'),
    versionGate: localized(
      'Compute Sanitizer 2026.2.1，以及 CUDA Toolkit 11.8.0 与 12.9.2 Lane 的 archive owner documentation。',
      'Compute Sanitizer 2026.2.1 plus archive owner documentation for the CUDA Toolkit 11.8.0 and 12.9.2 Lanes.',
    ),
    reviewedOn: '2026-08-28',
    keywords: localized('memcheck invalid memory access leak executed path clean report', 'memcheck invalid memory access leak executed path clean report'),
  },
  {
    planningId: 'PB-R1-023',
    group: 'practice',
    title: localized('为四类缺陷选择正确的 Sanitizer', 'Select the right Sanitizer for four defect classes'),
    href: localized('/practice/#pb-r1-023', '/en/practice/#pb-r1-023'),
    resourceType: 'correctness-debugging',
    difficulty: 'intermediate',
    prerequisites: ['Q04'],
    relatedUnits: ['Q03', 'Q04', 'EX16', 'LAB07'],
    hardwareGate: localized('无；只分类静态 defect scenarios，不运行 Compute Sanitizer。', 'None; classify static defect scenarios without running Compute Sanitizer.'),
    versionGate: localized(
      'Compute Sanitizer 2026.2.1 与 CUDA Toolkit 11.8.0 archive；selected Lane 的实际 tool version 必须另行记录。',
      'Compute Sanitizer 2026.2.1 and the CUDA Toolkit 11.8.0 archive; the selected Lane\'s actual tool version must be recorded separately.',
    ),
    reviewedOn: '2026-08-28',
    keywords: localized('memcheck racecheck initcheck synccheck tool selection clean report', 'memcheck racecheck initcheck synccheck tool selection clean report'),
  },
  {
    planningId: 'PB-R1-024',
    group: 'practice',
    title: localized('修复一次异步 GPU 工作计时声明', 'Repair a one-shot asynchronous GPU timing claim'),
    href: localized('/practice/#pb-r1-024', '/en/practice/#pb-r1-024'),
    resourceType: 'evidence-review',
    difficulty: 'intermediate',
    prerequisites: ['Q05'],
    relatedUnits: ['O03', 'M08', 'Q01', 'Q05', 'LAB04', 'LAB05'],
    hardwareGate: localized('无；只审查 measurement plan、raw samples 与 claim boundary，不运行 benchmark。', 'None; review a measurement plan, raw samples, and claim boundaries without running a benchmark.'),
    versionGate: localized(
      'Best Practices Guide v13.3、Runtime API v13.3.1、11.8.0/12.9.1 archive，以及 selected Lane 的 Nsight Compute documentation。',
      'Best Practices Guide v13.3, Runtime API v13.3.1, the 11.8.0/12.9.1 archives, and Nsight Compute documentation for the selected Lane.',
    ),
    reviewedOn: '2026-08-28',
    keywords: localized('correctness warm-up synchronization CUDA events raw samples median Environment Manifest', 'correctness warm-up synchronization CUDA events raw samples median Environment Manifest'),
  },
];

const visuals: readonly ResourceIndexRecord[] = [
  {
    planningId: 'VIS01',
    group: 'visuals',
    title: vis01Destination.title,
    href: vis01Destination.href,
    resourceType: 'execution-model',
    prerequisites: vis01Destination.prerequisites,
    relatedUnits: ['O01', 'O02', 'F01', 'F02'],
    hardwareGate: localized('无；确定性浏览器模型，不需要 CUDA-capable system。', 'None; deterministic browser model with no CUDA-capable system required.'),
    versionGate: localized('CUDA Programming Guide v13.3；概念模型不承诺固定硬件调度。', 'CUDA Programming Guide v13.3; the conceptual model promises no fixed hardware schedule.'),
    reviewedOn: '2026-08-24',
    keywords: localized('launch grid block warp 内存事务 同步', 'launch grid block warp memory transaction synchronization'),
  },
  {
    planningId: 'VIS02',
    group: 'visuals',
    title: vis02Destination.title,
    href: vis02Destination.href,
    resourceType: 'indexing-model',
    prerequisites: vis02Destination.prerequisites,
    relatedUnits: ['O01', 'O02', 'F01', 'F02', 'F03'],
    hardwareGate: localized('无；确定性浏览器模型，不需要 CUDA-capable system。', 'None; deterministic browser model with no CUDA-capable system required.'),
    versionGate: localized('CUDA Programming Guide v13.3；1D/2D/3D 索引与本站声明的 row-major extent。', 'CUDA Programming Guide v13.3; 1D/2D/3D indexing with site-declared row-major extents.'),
    reviewedOn: '2026-08-24',
    keywords: localized('gridDim blockDim blockIdx threadIdx bounds row-major', 'gridDim blockDim blockIdx threadIdx bounds row-major'),
  },
  {
    planningId: 'VIS03',
    group: 'visuals',
    title: vis03Destination.title,
    href: vis03Destination.href,
    resourceType: 'mental-model',
    prerequisites: vis03Destination.prerequisites,
    relatedUnits: ['M06'],
    hardwareGate: noCudaHardware,
    versionGate: localized(
      'CUDA Programming Guide v13.3；CC 7.0+ Independent Thread Scheduling，另以 11.8.0 与 12.9.1 archive 复核。',
      'CUDA Programming Guide v13.3; CC 7.0+ Independent Thread Scheduling, with 11.8.0 and 12.9.1 archive review.',
    ),
    reviewedOn: '2026-08-28',
    keywords: localized('warp divergence active mask reconvergence logical join', 'warp divergence active mask reconvergence logical join'),
  },
  {
    planningId: 'VIS04',
    group: 'visuals',
    title: vis04Destination.title,
    href: vis04Destination.href,
    resourceType: 'mental-model',
    prerequisites: vis04Destination.prerequisites,
    relatedUnits: ['M02', 'EX05'],
    hardwareGate: noCudaHardware,
    versionGate: localized(
      'Programming Guide 与 Best Practices Guide v13.3；CC 6.0+ 的 32-byte segment 教学模型，不是 transaction 或 timing measurement。',
      'Programming Guide and Best Practices Guide v13.3; a CC 6.0+ 32-byte segment teaching model, not a transaction or timing measurement.',
    ),
    reviewedOn: '2026-08-27',
    keywords: localized('active lane byte range aligned segment coalescing', 'active lane byte range aligned segment coalescing'),
  },
  {
    planningId: 'VIS05',
    group: 'visuals',
    title: vis05Destination.title,
    href: vis05Destination.href,
    resourceType: 'mental-model',
    prerequisites: vis05Destination.prerequisites,
    relatedUnits: ['M04', 'EX06'],
    hardwareGate: noCudaHardware,
    versionGate: localized(
      'Best Practices Guide v13.3；selected CC 7.5+ 的 32-bank、32-bit word 教学 fixture，不推断 timing。',
      'Best Practices Guide v13.3; a selected CC 7.5+ teaching fixture with 32 banks and 32-bit words, with no timing inference.',
    ),
    reviewedOn: '2026-08-27',
    keywords: localized('shared memory bank broadcast conflict padding stride', 'shared memory bank broadcast conflict padding stride'),
  },
  {
    planningId: 'VIS06',
    group: 'visuals',
    title: vis06Destination.title,
    href: vis06Destination.href,
    resourceType: 'mental-model',
    prerequisites: vis06Destination.prerequisites,
    relatedUnits: ['M01'],
    hardwareGate: noCudaHardware,
    versionGate: localized(
      'Programming Guide v13.3 与 Runtime API 13.3.1；selected Lane 使用 11.8.0 和 12.9.1 owner 文档交叉核对。',
      'Programming Guide v13.3 and Runtime API 13.3.1; selected Lanes are cross-checked against 11.8.0 and 12.9.1 owner documentation.',
    ),
    reviewedOn: '2026-08-27',
    keywords: localized('address space owner scope lifetime release cache', 'address space owner scope lifetime release cache'),
  },
  {
    planningId: 'VIS07',
    group: 'visuals',
    title: vis07Destination.title,
    href: vis07Destination.href,
    resourceType: 'execution-model',
    prerequisites: vis07Destination.prerequisites,
    relatedUnits: ['M07', 'M08'],
    hardwareGate: noCudaHardware,
    versionGate: localized(
      'CUDA Programming Guide v13.3 与 Runtime API v13.3.1；11.8.0 和 12.9.1 archive 复核 stream/event 边界。',
      'CUDA Programming Guide v13.3 and Runtime API v13.3.1; the 11.8.0 and 12.9.1 archives bound stream and event semantics.',
    ),
    reviewedOn: '2026-08-28',
    keywords: localized('stream event dependency ready set timing browser pacing', 'stream event dependency ready set timing browser pacing'),
  },
  {
    planningId: 'VIS19',
    group: 'visuals',
    title: vis19Destination.title,
    href: vis19Destination.href,
    resourceType: 'execution-model',
    prerequisites: vis19Destination.prerequisites,
    relatedUnits: ['F05', 'EX04', 'LAB03', 'F07'],
    hardwareGate: noCudaHardware,
    versionGate: localized(
      'CUDA Runtime API 11.8.0、12.9.2 archive/页面标签 12.9.1 与 13.3.1。',
      'CUDA Runtime API 11.8.0, 12.9.2 archive/page label 12.9.1, and 13.3.1.',
    ),
    reviewedOn: '2026-08-26',
    keywords: localized('异步错误 last-error launch completion 时间线', 'asynchronous error last-error launch completion timeline'),
  },
  {
    planningId: 'VIS20',
    group: 'visuals',
    title: vis20Destination.title,
    href: vis20Destination.href,
    resourceType: 'mental-model',
    prerequisites: vis20Destination.prerequisites,
    relatedUnits: ['F06', 'F08'],
    hardwareGate: noCudaHardware,
    versionGate: localized(
      'CUDA Programming Guide v13.3；NVCC 11.8.0、12.9.2 archive 与 selected Toolkit 13.3.1（页面标签 NVCC 13.3）。',
      'CUDA Programming Guide v13.3; NVCC 11.8.0, the 12.9.2 archive, and selected Toolkit 13.3.1 (page label NVCC 13.3).',
    ),
    reviewedOn: '2026-08-26',
    keywords: localized('compute capability feature set compiler target filter', 'compute capability feature set compiler target filter'),
  },
  {
    planningId: 'VIS21',
    group: 'visuals',
    title: vis21Destination.title,
    href: vis21Destination.href,
    resourceType: 'mental-model',
    prerequisites: vis21Destination.prerequisites,
    relatedUnits: ['F07', 'EX04'],
    hardwareGate: noCudaHardware,
    versionGate: localized(
      'CUDA Runtime/Driver API 11.8.0、12.9.2 archive/页面标签 12.9.1 与 13.3.1。',
      'CUDA Runtime and Driver APIs 11.8.0, 12.9.2 archive/page label 12.9.1, and 13.3.1.',
    ),
    reviewedOn: '2026-08-26',
    keywords: localized('Runtime Driver context module function ownership boundary', 'Runtime Driver context module function ownership boundary'),
  },
  {
    planningId: 'VIS22',
    group: 'visuals',
    title: vis22Destination.title,
    href: vis22Destination.href,
    resourceType: 'indexing-model',
    prerequisites: vis22Destination.prerequisites,
    relatedUnits: ['F08', 'LAB03'],
    hardwareGate: noCudaHardware,
    versionGate: localized(
      'CUDA Programming Guide v13.3；Runtime API 13.3.1 device/function properties。',
      'CUDA Programming Guide v13.3; Runtime API 13.3.1 device and function properties.',
    ),
    reviewedOn: '2026-08-26',
    keywords: localized('block shape launch geometry limits grid fringe', 'block shape launch geometry limits grid fringe'),
  },
];

const glossary: readonly ResourceIndexRecord[] = [
  glossaryRecord('TERM-001', 'Learning Site · 学习站', 'resource-vocabulary', ['O01'], '不受特定 Toolkit 版本约束。', 'Not tied to a Toolkit version.'),
  glossaryRecord('TERM-002', 'Stable Curriculum · 稳定课程', 'resource-vocabulary', ['O01'], '持续维护，不按 Toolkit 复制课程。', 'Maintained continuously rather than copied per Toolkit.'),
  glossaryRecord('TERM-003', 'Learning Unit · 学习单元', 'resource-vocabulary', ['O01'], '资源类型本身不受版本约束。', 'The resource type is version-independent.'),
  glossaryRecord('TERM-004', 'Publication Pair · 双语发布对', 'resource-vocabulary', ['O01'], '适用于每次发布。', 'Applies to every release.'),
  glossaryRecord('TERM-005', 'Runnable Example · 可运行示例', 'resource-vocabulary', ['O01', 'F01'], '每个项目单独声明版本边界。', 'Each project declares its own version boundary.'),
  glossaryRecord('TERM-006', 'Lab · 实验', 'resource-vocabulary', ['O01', 'LAB02'], '每个 Lab 单独声明环境要求。', 'Each Lab declares its environment requirements.'),
  glossaryRecord('TERM-007', 'Exercise · 练习', 'resource-vocabulary', ['O01'], '资源类型本身不受版本约束。', 'The resource type is version-independent.'),
  glossaryRecord('TERM-008', 'Practice Bank · 练习题库', 'resource-vocabulary', ['O01'], '具体条目按需声明版本边界。', 'Individual entries declare version boundaries as needed.'),
  glossaryRecord('TERM-009', 'Visual Explainer · 可视化讲解', 'resource-vocabulary', ['O01', 'VIS01', 'VIS02', 'VIS03', 'VIS04', 'VIS05', 'VIS06', 'VIS07', 'VIS19', 'VIS20', 'VIS21', 'VIS22'], '概念模型与硬件行为必须分开。', 'Conceptual models remain separate from hardware behavior.'),
  glossaryRecord('TERM-010', 'Glossary · 术语表', 'resource-vocabulary', ['O01'], '随课程复核，不暗示接口兼容性。', 'Reviewed with the curriculum without implying interface compatibility.'),
  glossaryRecord('TERM-011', 'Evidence Status · 证据状态', 'evidence-vocabulary', ['O02'], '状态绑定对象、环境、标准和日期。', 'Status is scoped to a subject, environment, criteria, and date.'),
  glossaryRecord('TERM-012', 'Compile-Checked · 编译已检查', 'evidence-vocabulary', ['O02', 'O03'], '每项声明绑定精确 Toolkit Lane。', 'Every claim binds to an exact Toolkit Lane.'),
  glossaryRecord('TERM-013', 'Community-Observed · 社区已观察', 'evidence-vocabulary', ['O02', 'O03'], '可与 Pending Hardware Verification 并存。', 'May coexist with Pending Hardware Verification.'),
  glossaryRecord('TERM-014', 'Runtime-Verified · 运行已验证', 'evidence-vocabulary', ['O02', 'O03'], '只覆盖记录的环境与方法坐标。', 'Covers only the recorded environment and method coordinates.'),
  glossaryRecord('TERM-015', 'Pending Hardware Verification · 待硬件验证', 'evidence-vocabulary', ['O02'], '编译或社区观察不会自动移除。', 'Compilation or community observation does not remove it automatically.'),
  glossaryRecord('TERM-016', 'Runtime-Not-Applicable · 无需运行验证', 'evidence-vocabulary', ['O02'], '只能用于不要求 GPU 行为的验收。', 'Only for acceptance that requires no GPU behavior.'),
  glossaryRecord('TERM-017', 'Environment Manifest · 环境清单', 'environment-vocabulary', ['O03'], '新证据必须记录新坐标和日期。', 'New evidence records new coordinates and a date.'),
  glossaryRecord('TERM-018', 'Supported Environment · 受支持环境', 'environment-vocabulary', ['O03'], '上游支持不会自动扩大本站责任。', 'Upstream support does not expand site responsibility automatically.'),
  glossaryRecord('TERM-019', 'Reference Environment · 基准环境', 'environment-vocabulary', ['O03'], '当前尚未声明 Reference Environment。', 'No Reference Environment is currently declared.'),
  glossaryRecord('TERM-020', 'Toolkit Lane · 工具包通道', 'environment-vocabulary', ['O03'], 'Lane 是编译证据目标，不是课程副本。', 'A Lane is a compile-evidence target, not a curriculum copy.'),
  glossaryRecord('TERM-021', 'GPU Capability Tier · GPU 能力层级', 'environment-vocabulary', ['O03'], '型号或显存不能单独决定层级。', 'A model name or memory size cannot select a tier alone.'),
  glossaryRecord('TERM-022', 'Baseline GPU Capability Tier · 基础 GPU 能力层级', 'environment-vocabulary', ['O03'], 'Compute capability 7.5+；问题规模可放入 8 GB。', 'Compute capability 7.5+ with problem sizes that fit within 8 GB.'),
  glossaryRecord('TERM-023', 'Modern Single-GPU Capability Tier · 现代单 GPU 能力层级', 'environment-vocabulary', ['O03'], 'Compute capability 8.0+ 且至少 8 GB。', 'Compute capability 8.0+ and at least 8 GB.'),
  glossaryRecord('TERM-024', 'CUDA Toolkit · CUDA 工具包', 'environment-vocabulary', ['O03'], 'Toolkit Lane 使用精确 X.Y.Z 坐标。', 'Toolkit Lanes use exact X.Y.Z coordinates.'),
  glossaryRecord('TERM-025', 'compute capability · 计算能力', 'environment-vocabulary', ['O03', 'F06'], '型号映射、功能、限制与编译目标按当前 NVIDIA 文档复核。', 'Model mappings, features, limits, and compiler targets require current NVIDIA documentation.'),
  glossaryRecord('TERM-026', 'kernel · 核函数', 'kernel-vocabulary', ['F01', 'F02', 'F04', 'LAB02', 'EX03'], 'F01-F04 使用 CUDA Programming Guide v13.3。', 'F01-F04 use CUDA Programming Guide v13.3.'),
  glossaryRecord('TERM-027', 'execution configuration · 执行配置', 'kernel-vocabulary', ['F01', 'F02', 'F03', 'VIS02', 'EX03'], '执行配置不自动定义逻辑数据范围。', 'Execution configuration does not define logical data extent automatically.'),
  glossaryRecord('TERM-028', 'grid · 网格', 'kernel-vocabulary', ['F01', 'F02', 'F03', 'VIS01', 'VIS02', 'EX03'], 'Grid 坐标不保证 block 调度顺序。', 'Grid coordinates do not guarantee block scheduling order.'),
  glossaryRecord('TERM-029', 'thread block · 线程块', 'kernel-vocabulary', ['F01', 'F02', 'F03', 'VIS01', 'VIS02', 'EX03'], 'F01 使用一维 block；F02/F03 与 VIS02 覆盖多维关系。', 'F01 uses 1D blocks; F02/F03 and VIS02 cover multidimensional relationships.'),
  glossaryRecord('TERM-030', 'thread · 线程', 'kernel-vocabulary', ['F01', 'F02', 'F03', 'VIS02', 'EX03'], 'Launch thread 可超出逻辑 extent。', 'A launched thread may lie beyond logical extent.'),
  glossaryRecord('TERM-031', 'host and device · 主机与设备', 'kernel-vocabulary', ['F01', 'F04', 'LAB02', 'EX03'], 'F04 与 EX03 使用 Runtime API 13.3.1 复核 lifecycle。', 'F04 and EX03 review the lifecycle against Runtime API 13.3.1.'),
  glossaryRecord('TERM-032', 'bounds check · 边界判断', 'kernel-vocabulary', ['F01', 'F03', 'VIS02', 'LAB02', 'EX02', 'EX03'], 'EX03 在展平前逐轴检查 bounds。', 'EX03 checks each axis before flattening.'),
  glossaryRecord('TERM-033', 'CPU reference · CPU 参考实现', 'kernel-vocabulary', ['F01', 'LAB02', 'EX02'], 'Host-only test 不授予 GPU runtime evidence。', 'A host-only test grants no GPU runtime evidence.'),
  glossaryRecord('TERM-034', 'tolerance · 容差', 'kernel-vocabulary', ['F01', 'LAB02', 'EX02'], 'EX02 使用绝对或相对 1e-5 接受规则。', 'EX02 uses an absolute-or-relative 1e-5 acceptance rule.'),
  glossaryRecord('TERM-035', 'RAII · 资源获取即初始化', 'kernel-vocabulary', ['O04'], '适用于 ISO C++17 host code；device 可用接口须按 Toolkit 核对。', 'Applies to ISO C++17 host code; device-callable interfaces require Toolkit review.'),
  glossaryRecord('TERM-036', 'undefined behavior · 未定义行为', 'kernel-vocabulary', ['O04'], '定义来自 WG21 N4659；工具只能覆盖执行到的受支持检查。', 'Defined by WG21 N4659; tools cover only supported checks on executed paths.'),
  glossaryRecord('TERM-037', 'translation unit · 翻译单元', 'kernel-vocabulary', ['O04'], 'O04 使用 ISO C++17 与 NVCC v13.3 compilation trajectory。', 'O04 uses ISO C++17 and the NVCC v13.3 compilation trajectory.'),
  glossaryRecord('TERM-038', 'reproducible command record · 可复现命令记录', 'environment-vocabulary', ['O05', 'LAB01'], 'GNU Bash 5.3、Coreutils 9.11 与 GNU Make 4.4.1。', 'GNU Bash 5.3, Coreutils 9.11, and GNU Make 4.4.1.'),
  glossaryRecord('TERM-039', 'latency · 延迟', 'kernel-vocabulary', ['O06'], '必须绑定具体操作、路径与计时边界。', 'Must bind to a named operation, path, and timing boundary.'),
  glossaryRecord('TERM-040', 'throughput · 吞吐量', 'kernel-vocabulary', ['O06', 'O07'], '峰值 issue rate 不等于应用实际吞吐量。', 'Peak issue rate is not achieved application throughput.'),
  glossaryRecord('TERM-041', 'bandwidth · 带宽', 'kernel-vocabulary', ['O06'], '必须记录 memory path、单位与 theoretical/effective/actual 口径。', 'Requires a memory path, units, and theoretical/effective/actual convention.'),
  glossaryRecord('TERM-042', 'concurrency · 并发', 'kernel-vocabulary', ['O06', 'M07', 'VIS07'], '必须说明 resident work、kernel、stream、copy/compute 或 host/device scope。', 'Must name resident-work, kernel, stream, copy/compute, or host/device scope.'),
  glossaryRecord('TERM-043', 'arithmetic intensity · 算术强度', 'kernel-vocabulary', ['O06'], '工作计数与 memory-traffic boundary 决定数值。', 'The work count and memory-traffic boundary determine the value.'),
  glossaryRecord('TERM-044', 'occupancy · 占用率', 'kernel-vocabulary', ['O06'], 'Occupancy 不是 utilization，也不是性能目标值。', 'Occupancy is neither utilization nor a target performance value.'),
  glossaryRecord('TERM-045', 'programmable shader stage · 可编程着色器阶段', 'kernel-vocabulary', ['O07'], '历史接口仍受 graphics pipeline input/output 约束。', 'Historical interfaces remain constrained by graphics-pipeline inputs and outputs.'),
  glossaryRecord('TERM-046', 'GPGPU · 通用 GPU 计算', 'kernel-vocabulary', ['O07'], '历史 GPGPU mapping 不等同于 CUDA programming model。', 'Historical GPGPU mappings are not the CUDA programming model.'),
  glossaryRecord('TERM-047', 'compatibility assessment · 兼容性评估', 'environment-vocabulary', ['O08'], '只输出 documented-path、not-documented 或 indeterminate，不授予证据状态。', 'Produces only documented-path, not-documented, or indeterminate and grants no Evidence Status.'),
  glossaryRecord('TERM-048', 'Reference Environment candidate · 基准环境候选配置', 'environment-vocabulary', ['O08', 'LAB01'], '候选配置不是声明；仍需 maintainer control 与成功 baseline run。', 'A candidate is not a declaration; maintainer control and a successful baseline run remain required.'),
  glossaryRecord('TERM-049', 'streaming multiprocessor (SM) · 流式多处理器', 'kernel-vocabulary', ['F02', 'VIS01'], 'CUDA Programming Guide v13.3；SM 是硬件资源，不是 launch 坐标。', 'CUDA Programming Guide v13.3; an SM is a hardware resource, not a launch coordinate.'),
  glossaryRecord('TERM-050', 'warp · 线程束', 'kernel-vocabulary', ['F02', 'VIS01', 'VIS02', 'M05', 'M06', 'VIS03'], 'CUDA Programming Guide v13.3；当前 warp 包含 32 个 lane。', 'CUDA Programming Guide v13.3; a current warp contains 32 lanes.'),
  glossaryRecord('TERM-051', 'lane · 通道', 'kernel-vocabulary', ['F02', 'VIS02', 'M06', 'VIS03'], 'Lane 是 warp 内位置，不是全局数据索引或时间顺序。', 'A lane is a position within a warp, not a global data index or time order.'),
  glossaryRecord('TERM-052', 'dim3 · 三分量 launch 配置类型', 'kernel-vocabulary', ['F03', 'EX03'], 'CUDA Programming Guide v13.3；省略的分量默认为 1。', 'CUDA Programming Guide v13.3; omitted components default to 1.'),
  glossaryRecord('TERM-053', 'logical extent · 逻辑范围', 'kernel-vocabulary', ['F03', 'VIS02', 'EX03'], 'Extent 由应用声明，不由 execution geometry 自动推断。', 'The application declares its extent; execution geometry does not infer it.'),
  glossaryRecord('TERM-054', 'row-major layout · 行主序布局', 'kernel-vocabulary', ['F03', 'VIS02', 'EX03'], 'EX03 显式声明 x-fastest layout；CUDA launch geometry 不声明数据布局。', 'EX03 explicitly declares an x-fastest layout; CUDA launch geometry declares no data layout.'),
  glossaryRecord('TERM-055', 'resource lifecycle · 资源生命周期', 'kernel-vocabulary', ['F04', 'O04', 'EX03'], 'CUDA Runtime API 13.3.1；ownership、last use 与 release 必须分开记录。', 'CUDA Runtime API 13.3.1; ownership, last use, and release remain distinct.'),
  glossaryRecord('TERM-056', 'asynchronous error · 异步错误', 'kernel-vocabulary', ['F05', 'F07', 'EX04', 'LAB03'], 'Runtime API 11.8.0、12.9.2 archive/页面标签 12.9.1 与 13.3.1。', 'Runtime API 11.8.0, 12.9.2 archive/page label 12.9.1, and 13.3.1.'),
  glossaryRecord('TERM-057', 'last-error state · 末次错误状态', 'kernel-vocabulary', ['F05', 'EX04', 'LAB03'], '三个 selected Runtime API 版本共享 getter reset/peek non-reset 合同。', 'All three selected Runtime API versions share getter-reset and peek-non-reset semantics.'),
  glossaryRecord('TERM-058', 'CUDA Runtime API · CUDA 运行时 API', 'kernel-vocabulary', ['F04', 'F05', 'F07', 'EX04', 'LAB03'], '11.8.0、12.9.2 archive/页面标签 12.9.1 与 13.3.1 的角色按版本核对。', 'Roles are reviewed by version at 11.8.0, 12.9.2 archive/page label 12.9.1, and 13.3.1.'),
  glossaryRecord('TERM-059', 'CUDA Driver API · CUDA 驱动 API', 'kernel-vocabulary', ['F07'], '11.8.0、12.9.2 archive/页面标签 12.9.1 与 13.3.1 的 handle/interop 合同按版本核对。', 'Handle and interoperability contracts are reviewed by version at 11.8.0, 12.9.2 archive/page label 12.9.1, and 13.3.1.'),
  glossaryRecord('TERM-060', 'virtual architecture target · 虚拟架构目标', 'environment-vocabulary', ['F06'], 'NVCC 11.8.0、12.9.2 与 selected Toolkit 13.3.1 的 accepted targets。', 'Accepted targets are versioned across NVCC 11.8.0, 12.9.2, and selected Toolkit 13.3.1.'),
  glossaryRecord('TERM-061', 'real architecture target · 实际架构目标', 'environment-vocabulary', ['F06'], '每个 real target 必须实现 paired virtual target 的 feature assumptions。', 'Each real target must implement the paired virtual target feature assumptions.'),
  glossaryRecord('TERM-062', 'architecture-specific feature set · 架构特定功能集', 'environment-vocabulary', ['F06'], 'CUDA Programming Guide v13.3；从 compute capability 9.0 开始。', 'CUDA Programming Guide v13.3; available beginning with compute capability 9.0.'),
  glossaryRecord('TERM-063', 'family-specific feature set · 系列特定功能集', 'environment-vocabulary', ['F06'], 'CUDA Programming Guide v13.3；从 compute capability 10.0 开始。', 'CUDA Programming Guide v13.3; available beginning with compute capability 10.0.'),
  glossaryRecord('TERM-064', 'launch geometry · 启动几何', 'kernel-vocabulary', ['F02', 'F03', 'F08', 'LAB03'], 'Programming Guide v13.3 与 Runtime API 13.3.1 device/function limits。', 'Programming Guide v13.3 and Runtime API 13.3.1 device/function limits.'),
  glossaryRecord('TERM-065', 'block shape · 线程块形状', 'kernel-vocabulary', ['F08', 'LAB03'], '轴向、总 thread 与 kernel-specific limit 必须分开核对。', 'Per-axis, aggregate-thread, and kernel-specific limits require separate checks.'),
  glossaryRecord('TERM-066', 'address space · 地址空间', 'kernel-vocabulary', ['M01', 'VIS06'], 'M01 按 Programming Guide v13.3、11.8.0 与 12.9.1 owner 文档复核。', 'M01 reviews Programming Guide v13.3 and the 11.8.0 and 12.9.1 owner documentation.', '2026-08-27'),
  glossaryRecord('TERM-067', 'global memory · 全局内存', 'kernel-vocabulary', ['M01', 'M02', 'VIS04', 'EX05'], '语义合同按 selected 11.8.0、12.9.1 与 current v13.3 坐标复核。', 'The semantic contract is reviewed at selected 11.8.0, 12.9.1, and current v13.3 coordinates.', '2026-08-27'),
  glossaryRecord('TERM-068', 'constant memory · 常量内存', 'kernel-vocabulary', ['M01', 'VIS06'], '声明、symbol copy 与 lifetime 按 selected Programming Guide/Runtime 文档复核。', 'Declaration, symbol-copy, and lifetime details are reviewed in selected Programming Guide and Runtime documentation.', '2026-08-27'),
  glossaryRecord('TERM-069', 'shared memory · 共享内存', 'kernel-vocabulary', ['M01', 'M03', 'M04', 'VIS05', 'EX06'], 'M01/M03/M04 使用 selected 11.8.0、12.9.1 与 current v13.3 owner 文档。', 'M01/M03/M04 use selected 11.8.0, 12.9.1, and current v13.3 owner documentation.', '2026-08-27'),
  glossaryRecord('TERM-070', 'local memory · 本地内存', 'kernel-vocabulary', ['M01', 'VIS06'], 'Local address space 是 thread-private，但 physical placement 与 cache behavior 必须按 architecture 复核。', 'The local address space is thread-private, while physical placement and cache behavior require architecture-specific review.', '2026-08-27'),
  glossaryRecord('TERM-071', 'register · 寄存器', 'kernel-vocabulary', ['M01', 'VIS06'], 'Register allocation 与 spill 由 compiler/target 决定，不能从 source spelling 保证。', 'Register allocation and spilling depend on the compiler and target and are not guaranteed by source spelling.', '2026-08-27'),
  glossaryRecord('TERM-072', 'memory transaction · 内存事务', 'kernel-vocabulary', ['M02', 'VIS04', 'EX05'], 'M02 的 CC 6.0+ fixture 只推导 naturally aligned 32-byte segment coverage。', 'The M02 CC 6.0+ fixture derives only naturally aligned 32-byte segment coverage.', '2026-08-27'),
  glossaryRecord('TERM-073', 'coalescing · 合并访问', 'kernel-vocabulary', ['M02', 'VIS04', 'EX05'], '规则随 compute capability 与 access size 变化；M02 明确限定到 selected 32-byte segment model。', 'Rules vary with compute capability and access size; M02 is explicitly limited to the selected 32-byte segment model.', '2026-08-27'),
  glossaryRecord('TERM-074', 'shared-memory bank · 共享内存存储体', 'kernel-vocabulary', ['M04', 'VIS05', 'EX06'], 'M04 使用 selected CC 7.5+ 的 32-bank、32-bit word fixture；其他 architecture 必须重新核对。', 'M04 uses a selected CC 7.5+ fixture with 32 banks and 32-bit words; other architectures require renewed review.', '2026-08-27'),
  glossaryRecord('TERM-075', 'bank conflict · 存储体冲突', 'kernel-vocabulary', ['M04', 'VIS05', 'EX06'], 'Conflict classification 绑定 selected bank mapping；same-address read broadcast 单独处理。', 'Conflict classification is bound to the selected bank mapping; same-address read broadcast is handled separately.', '2026-08-27'),
  glossaryRecord('TERM-076', 'tiling · 分块', 'kernel-vocabulary', ['M03', 'M04', 'EX06'], 'M03 教授 portable C++17 synchronous baseline；未来 async interface 不向当前 Lane 倒推。', 'M03 teaches the portable C++17 synchronous baseline; future asynchronous interfaces are not projected backward into current Lanes.', '2026-08-27'),
  glossaryRecord('TERM-077', 'synchronization scope · 同步作用域', 'kernel-vocabulary', ['M05'], 'Programming Guide v13.3；11.8.0 与 12.9.1 archive 用于核对 durable scope boundary。', 'Programming Guide v13.3, with 11.8.0 and 12.9.1 archives bounding durable scope semantics.', '2026-08-28'),
  glossaryRecord('TERM-078', 'memory visibility · 内存可见性', 'kernel-vocabulary', ['M05'], 'Visibility 必须绑定 documented ordering、scope 与可访问 storage。', 'Visibility must bind to documented ordering, scope, and accessible storage.', '2026-08-28'),
  glossaryRecord('TERM-079', 'active mask · 活动掩码', 'kernel-vocabulary', ['F02', 'M06', 'VIS03'], 'CC 7.0+ Independent Thread Scheduling 下不能把某时刻 active mask 当作永久参与组。', 'Under CC 7.0+ Independent Thread Scheduling, a momentary active mask is not a permanent participant group.', '2026-08-28'),
  glossaryRecord('TERM-080', 'divergence · 分支发散', 'kernel-vocabulary', ['M06', 'VIS03'], 'Programming Guide v13.3；VIS03 不模拟 exact issue order 或 latency。', 'Programming Guide v13.3; VIS03 models neither exact issue order nor latency.', '2026-08-28'),
  glossaryRecord('TERM-081', 'reconvergence · 重汇合', 'kernel-vocabulary', ['M06', 'VIS03'], 'Source-level logical join 不等于 memory synchronization，hardware reconvergence 仍属 implementation detail。', 'A source-level logical join is not memory synchronization; hardware reconvergence remains an implementation detail.', '2026-08-28'),
  glossaryRecord('TERM-082', 'warp-safe reasoning · 线程束安全推理', 'kernel-vocabulary', ['M05', 'M06', 'VIS03'], 'Participant mask、source-lane validity 与 ordering 必须按所用 intrinsic 和 architecture contract 复核。', 'Participant masks, source-lane validity, and ordering require review against the selected intrinsic and architecture contract.', '2026-08-28'),
  glossaryRecord('TERM-083', 'stream · 流', 'kernel-vocabulary', ['F05', 'M07', 'VIS07'], 'Programming Guide v13.3 与 Runtime API v13.3.1；default-stream relationship 取决于 mode 与 flags。', 'Programming Guide v13.3 and Runtime API v13.3.1; default-stream relationships depend on mode and flags.', '2026-08-28'),
  glossaryRecord('TERM-084', 'event · 事件', 'kernel-vocabulary', ['M08', 'VIS07'], 'Runtime API v13.3.1；recorded generation、creation flags 与 completion state 都属于 event contract。', 'Runtime API v13.3.1; recorded generation, creation flags, and completion state all belong to the event contract.', '2026-08-28'),
  glossaryRecord('TERM-085', 'event dependency · 事件依赖', 'kernel-vocabulary', ['M07', 'M08', 'VIS07'], 'Record/wait semantics 按 Runtime API 13.3.1 及 11.8.0/12.9.1 archive 复核；dependency 不证明 overlap。', 'Record/wait semantics are reviewed in Runtime API 13.3.1 and the 11.8.0/12.9.1 archives; a dependency does not prove overlap.', '2026-08-28'),
  glossaryRecord('TERM-086', 'device-time measurement · 设备时间测量', 'kernel-vocabulary', ['O06', 'M08', 'VIS07'], 'Timing-enabled recorded events、完成边界与 Environment Manifest 缺一不可；browser pacing 不是 device time。', 'Timing-enabled recorded events, completion boundaries, and an Environment Manifest are all required; browser pacing is not device time.', '2026-08-28'),
  glossaryRecord('TERM-087', 'CPU reference · CPU 参考实现', 'kernel-vocabulary', ['Q01'], 'Q01 按 current v13.3 与 11.8.0/12.9.1 owner documentation 复核；host-only result 不授予 GPU runtime evidence。', 'Q01 is reviewed against current v13.3 and 11.8.0/12.9.1 owner documentation; a host-only result grants no GPU runtime evidence.', '2026-08-28'),
  glossaryRecord('TERM-088', 'tolerance · 容差', 'kernel-vocabulary', ['Q01'], 'Threshold 必须按数据 scale、precision、operation structure 与 domain requirement 声明；不存在通用 epsilon。', 'Thresholds must be declared from data scale, precision, operation structure, and domain requirements; there is no universal epsilon.', '2026-08-28'),
  glossaryRecord('TERM-089', 'invariant · 不变量', 'kernel-vocabulary', ['Q01'], 'Invariant 必须独立于被比较实现的共同结构，且只能覆盖它实际检查的 property。', 'An invariant must be independent of structure shared by the compared implementations and covers only the property it checks.', '2026-08-28'),
  glossaryRecord('TERM-090', 'memcheck · 内存检查工具', 'kernel-vocabulary', ['Q03', 'EX16', 'LAB07'], 'Tool scope 按 selected Lane 的 Compute Sanitizer version 复核；clean executed-path report 不是程序正确性证明。', 'Tool scope is reviewed for the selected Lane\'s Compute Sanitizer version; a clean executed-path report is not proof of program correctness.', '2026-08-28'),
  glossaryRecord('TERM-091', 'racecheck · 数据访问危害检查工具', 'kernel-vocabulary', ['Q04', 'EX16', 'LAB07'], 'Stable baseline 检查 shared-memory data access hazard；不应改写成任意 global-memory race proof。', 'The stable baseline checks shared-memory data access hazards and must not be rewritten as proof against arbitrary global-memory races.', '2026-08-28'),
  glossaryRecord('TERM-092', 'initcheck · 未初始化读取检查工具', 'kernel-vocabulary', ['Q04', 'EX16', 'LAB07'], 'Stable cross-Lane baseline 是 uninitialized device global-memory read；shared-memory extension 按版本隔离。', 'The stable cross-Lane baseline is uninitialized device-global-memory reads; the shared-memory extension is version-gated.', '2026-08-28'),
  glossaryRecord('TERM-093', 'synccheck · 同步原语检查工具', 'kernel-vocabulary', ['Q04', 'EX16', 'LAB07'], 'Report class 与 coverage 按 selected Compute Sanitizer version 复核；clean run 只描述 executed path。', 'Report classes and coverage are reviewed for the selected Compute Sanitizer version; a clean run describes only the executed path.', '2026-08-28'),
  glossaryRecord('TERM-094', 'warm-up · 预热', 'kernel-vocabulary', ['Q05', 'LAB04', 'LAB05'], 'Warm-up work 必须在 measurement plan 中声明并排除在 retained samples 外；次数不是跨 workload 的通用常量。', 'Warm-up work must be declared in the measurement plan and excluded from retained samples; its count is not a universal cross-workload constant.', '2026-08-28'),
  glossaryRecord('TERM-095', 'measurement statistic · 测量统计量', 'evidence-vocabulary', ['Q05', 'LAB04', 'LAB05'], 'Statistic 与 spread 必须在采集前声明并与全部 raw retained samples 一起报告；单次值不构成 distribution summary。', 'The statistic and spread must be declared before collection and reported with every retained raw sample; one value is not a distribution summary.', '2026-08-28'),
];

const sources: readonly ResourceIndexRecord[] = [
  sourceRecord('SRC-WEB-001', same('Astro'), 'publishing-interface', ['O01'], same('Astro 7.2.4'), '2026-08-25'),
  sourceRecord('SRC-WEB-002', same('Starlight'), 'publishing-interface', ['O01'], same('Starlight 0.41.7'), '2026-08-25'),
  sourceRecord('SRC-WEB-003', same('Pagefind'), 'publishing-interface', ['O01'], same('Pagefind 1.5.2'), '2026-08-25'),
  sourceRecord(
    'SRC-WEB-004',
    localized('Cloudflare 静态发布', 'Cloudflare static release'),
    'publishing-interface',
    ['O01'],
    localized('Wrangler 4.125.0；compatibility date 2026-08-24', 'Wrangler 4.125.0; compatibility date 2026-08-24'),
  ),
  sourceRecord(
    'SRC-WEB-005',
    localized('Playwright 与 axe', 'Playwright and axe'),
    'publishing-interface',
    ['O01'],
    same('Playwright 1.62.1; @axe-core/playwright 4.13.0'),
  ),
  sourceRecord(
    'SRC-WEB-006',
    localized('浏览器接口与 CSS 媒体', 'Browser APIs and CSS media'),
    'publishing-interface',
    ['O01', 'VIS01', 'VIS02', 'VIS03', 'VIS04', 'VIS05', 'VIS06', 'VIS07', 'VIS19', 'VIS20', 'VIS21', 'VIS22'],
    localized('WHATWG Living Standard、WCAG 2.2 技术与当前 CSS 规范', 'WHATWG Living Standard, WCAG 2.2 techniques, and current CSS specifications'),
  ),
  sourceRecord(
    'SRC-WEB-007',
    localized('Docker Engine 与 Buildx', 'Docker Engine and Buildx'),
    'publishing-interface',
    ['EX02', 'EX03', 'EX04', 'EX05', 'EX06'],
    localized('每条编译记录保存 runner 实际版本', 'Each compile record captures the runner-provided versions'),
  ),
  sourceRecord(
    'SRC-CUDA-001',
    localized('CUDA 11.8 Lane 来源', 'CUDA 11.8 Lane sources'),
    'cuda-version-record',
    ['O03', 'EX02', 'EX03', 'EX04', 'EX05', 'EX06', 'LAB02'],
    localized('Toolkit 11.8.0；Ubuntu 22.04 x86-64；C++17', 'Toolkit 11.8.0; Ubuntu 22.04 x86-64; C++17'),
  ),
  sourceRecord(
    'SRC-CUDA-002',
    localized('CUDA 12.9 Lane 来源', 'CUDA 12.9 Lane sources'),
    'cuda-version-record',
    ['O03', 'EX02', 'EX03', 'EX04', 'EX05', 'EX06', 'LAB02'],
    localized('Toolkit 12.9.2；Ubuntu 24.04 x86-64；C++17/C++20', 'Toolkit 12.9.2; Ubuntu 24.04 x86-64; C++17/C++20'),
  ),
  sourceRecord(
    'SRC-CUDA-003',
    localized('CUDA 13.3 Lane 来源', 'CUDA 13.3 Lane sources'),
    'cuda-version-record',
    ['O03', 'EX02', 'EX03', 'EX04', 'EX05', 'EX06', 'LAB02'],
    localized('Toolkit 13.3.1；Ubuntu 24.04 x86-64；C++17/C++20 与 C++23 probe', 'Toolkit 13.3.1; Ubuntu 24.04 x86-64; C++17/C++20 plus a C++23 probe'),
  ),
  sourceRecord(
    'SRC-CUDA-004',
    localized('编译与运行阶段', 'Compilation and running phases'),
    'cuda-version-record',
    ['O02'],
    same('NVCC 13.3.1'),
  ),
  sourceRecord(
    'SRC-CUDA-005',
    same('compute capability'),
    'cuda-version-record',
    ['O03'],
    same('CUDA Programming Guide 13.3.1'),
  ),
  sourceRecord(
    'SRC-CUDA-006',
    localized('VIS01 execution model', 'VIS01 execution model'),
    'cuda-version-record',
    ['VIS01'],
    localized('CUDA Programming Guide v13.3；2026-05-27 更新', 'CUDA Programming Guide v13.3; updated 2026-05-27'),
  ),
  sourceRecord(
    'SRC-CUDA-007',
    localized('VIS02 indexing model', 'VIS02 indexing model'),
    'cuda-version-record',
    ['VIS02', 'F02', 'F03'],
    localized('CUDA Programming Guide v13.3；2026-05-27 更新', 'CUDA Programming Guide v13.3; updated 2026-05-27'),
  ),
  sourceRecord(
    'SRC-CUDA-008',
    localized('F01 first-kernel model', 'F01 first-kernel model'),
    'cuda-version-record',
    ['F01'],
    localized('CUDA Programming Guide v13.3；CUDA Runtime API 13.3.1', 'CUDA Programming Guide v13.3; CUDA Runtime API 13.3.1'),
  ),
  sourceRecord(
    'SRC-CUDA-009',
    localized('LAB02 runtime contract', 'LAB02 runtime contract'),
    'cuda-version-record',
    ['LAB02', 'EX02'],
    localized('Runtime API 11.8.0、12.9.2/页面标签 12.9.1、13.3.1', 'Runtime API 11.8.0, 12.9.2/page label 12.9.1, and 13.3.1'),
  ),
  sourceRecord(
    'SRC-CUDA-010',
    localized('容器身份', 'Container identities'),
    'cuda-version-record',
    ['EX02', 'EX03', 'EX04', 'EX05', 'EX06'],
    same('11.8.0-devel-ubuntu22.04; 12.9.2-devel-ubuntu24.04; 13.3.1-devel-ubuntu24.04'),
  ),
  sourceRecord(
    'SRC-CPP-001',
    localized('C++17 abstract machine 与 guidance', 'C++17 abstract machine and guidance'),
    'cpp-language-record',
    ['O04'],
    localized('WG21 N4659/N4661；C++ Core Guidelines 2026-06-14。', 'WG21 N4659/N4661; C++ Core Guidelines dated 2026-06-14.'),
    '2026-08-26',
    '2026-08-26',
  ),
  sourceRecord(
    'SRC-CPP-002',
    localized('Host/CUDA C++ build 与检查接口', 'Host/CUDA C++ build and checking interfaces'),
    'cpp-language-record',
    ['O04', 'EX01'],
    localized('GCC 13.3.0；CUDA Programming Guide/NVCC v13.3；Compute Sanitizer 2026.2.1。', 'GCC 13.3.0; CUDA Programming Guide/NVCC v13.3; Compute Sanitizer 2026.2.1.'),
    '2026-08-26',
    '2026-08-26',
  ),
  sourceRecord(
    'SRC-LINUX-001',
    localized('Shell、路径、日志与哈希接口', 'Shell, path, log, and hash interfaces'),
    'linux-tool-record',
    ['O05', 'LAB01'],
    localized('GNU Bash 5.3；GNU Coreutils 9.11；native Linux。', 'GNU Bash 5.3; GNU Coreutils 9.11; native Linux.'),
    '2026-08-26',
    '2026-08-26',
  ),
  sourceRecord(
    'SRC-LINUX-002',
    localized('Build、process 与 OS identity 接口', 'Build, process, and OS identity interfaces'),
    'linux-tool-record',
    ['O05', 'LAB01'],
    localized('GNU Make 4.4.1；procps-ng 4.0.6；Linux 6.8；systemd 261.2。', 'GNU Make 4.4.1; procps-ng 4.0.6; Linux 6.8; systemd 261.2.'),
    '2026-08-26',
    '2026-08-26',
  ),
  sourceRecord(
    'SRC-ARCH-001',
    localized('当前 CUDA architecture、bandwidth 与 occupancy', 'Current CUDA architecture, bandwidth, and occupancy'),
    'architecture-record',
    ['O06'],
    localized('CUDA Programming Guide 与 Best Practices Guide v13.3。', 'CUDA Programming Guide and Best Practices Guide v13.3.'),
    '2026-08-26',
    '2026-08-26',
  ),
  sourceRecord(
    'SRC-ARCH-002',
    localized('Roofline 与 profiler terminology', 'Roofline and profiler terminology'),
    'architecture-record',
    ['O06'],
    localized('2009 Roofline technical report；Nsight Compute 2026.2.1。', '2009 Roofline technical report; Nsight Compute 2026.2.1.'),
    '2026-08-26',
    '2026-08-26',
  ),
  sourceRecord(
    'SRC-HIST-001',
    localized('Programmable graphics stage primary sources', 'Programmable graphics-stage primary sources'),
    'historical-record',
    ['O07'],
    localized('Khronos ARB Extension 26/27；SIGGRAPH 2001；Cg 2003。', 'Khronos ARB Extensions 26/27; SIGGRAPH 2001; Cg 2003.'),
    '2026-08-26',
    '2026-08-26',
  ),
  sourceRecord(
    'SRC-HIST-002',
    localized('BrookGPU 与 CUDA primary sources', 'BrookGPU and CUDA primary sources'),
    'historical-record',
    ['O07'],
    localized('BrookGPU 2004；Scalable Parallel Programming with CUDA 2008。', 'BrookGPU 2004; Scalable Parallel Programming with CUDA 2008.'),
    '2026-08-26',
    '2026-08-26',
  ),
  sourceRecord(
    'SRC-CUDA-011',
    localized('EX01 Runtime query contract', 'EX01 Runtime query contract'),
    'cuda-version-record',
    ['O03', 'O08', 'EX01', 'LAB01'],
    localized('Runtime API 11.8.0、12.9.2/页面标签 12.9.1、13.3.1；Programming Guide v13.3。', 'Runtime API 11.8.0, 12.9.2/page label 12.9.1, and 13.3.1; Programming Guide v13.3.'),
    '2026-08-26',
    '2026-08-26',
  ),
  sourceRecord(
    'SRC-CUDA-012',
    localized('CUDA compatibility 与 selected Lane facts', 'CUDA compatibility and selected Lane facts'),
    'cuda-version-record',
    ['O08', 'LAB01'],
    localized('Why/Minor/Forward Compatibility；Toolkit 11.8.0、12.9.2、13.3.1。', 'Why/Minor/Forward Compatibility; Toolkit 11.8.0, 12.9.2, and 13.3.1.'),
    '2026-08-26',
    '2026-08-26',
  ),
  sourceRecord(
    'SRC-CUDA-013',
    localized('F02/F03 执行层级与多维索引', 'F02/F03 execution hierarchy and multidimensional indexing'),
    'cuda-version-record',
    ['F02', 'F03', 'VIS02', 'EX03'],
    localized('CUDA Programming Guide v13.3；2026-05-27 更新。', 'CUDA Programming Guide v13.3; updated 2026-05-27.'),
    '2026-08-26',
    '2026-08-26',
  ),
  sourceRecord(
    'SRC-CUDA-014',
    localized('F04/EX03 lifecycle 与兼容性', 'F04/EX03 lifecycle and compatibility'),
    'cuda-version-record',
    ['F04', 'EX03'],
    localized('Runtime/NVCC 11.8.0、12.9.2/页面标签 12.9.1、13.3.1；C++17。', 'Runtime/NVCC 11.8.0, 12.9.2/page label 12.9.1, and 13.3.1; C++17.'),
    '2026-08-26',
    '2026-08-26',
  ),
  sourceRecord(
    'SRC-CUDA-015',
    localized('F05/F07/EX04/LAB03 错误与 Runtime/Driver API', 'F05/F07/EX04/LAB03 errors and Runtime/Driver APIs'),
    'cuda-version-record',
    ['F05', 'F07', 'VIS19', 'VIS21', 'EX04', 'LAB03'],
    localized('Programming Guide v13.3；Runtime/Driver API 11.8.0、12.9.2 archive/页面标签 12.9.1 与 13.3.1。', 'Programming Guide v13.3; Runtime/Driver APIs 11.8.0, 12.9.2 archive/page label 12.9.1, and 13.3.1.'),
    '2026-08-26',
    '2026-08-26',
  ),
  sourceRecord(
    'SRC-CUDA-016',
    localized('F06/F08 capability、compiler target 与 launch limit', 'F06/F08 capability, compiler targets, and launch limits'),
    'cuda-version-record',
    ['F06', 'F08', 'VIS20', 'VIS22'],
    localized('Programming Guide v13.3；NVCC 11.8.0、12.9.2、selected Toolkit 13.3.1；Runtime API 13.3.1。', 'Programming Guide v13.3; NVCC 11.8.0, 12.9.2, and selected Toolkit 13.3.1; Runtime API 13.3.1.'),
    '2026-08-26',
    '2026-08-26',
  ),
  sourceRecord(
    'SRC-CUDA-017',
    localized('M01/VIS06 memory space、ownership 与 Runtime lifetime', 'M01/VIS06 memory spaces, ownership, and Runtime lifetime'),
    'cuda-version-record',
    ['F04', 'M01', 'VIS06'],
    localized(
      'Programming Guide v13.3；Runtime API 13.3.1；11.8.0 与 12.9.1 owner 文档。',
      'Programming Guide v13.3; Runtime API 13.3.1; 11.8.0 and 12.9.1 owner documentation.',
    ),
    '2026-08-27',
    '2026-08-27',
  ),
  sourceRecord(
    'SRC-CUDA-018',
    localized('M02/VIS04/EX05 global request segment 与 coalescing', 'M02/VIS04/EX05 global request segments and coalescing'),
    'cuda-version-record',
    ['F03', 'M02', 'VIS04', 'EX05'],
    localized(
      'Programming Guide 与 Best Practices Guide v13.3；11.8.0 与 12.9.1 owner guide。',
      'Programming Guide and Best Practices Guide v13.3; 11.8.0 and 12.9.1 owner guides.',
    ),
    '2026-08-27',
    '2026-08-27',
  ),
  sourceRecord(
    'SRC-CUDA-019',
    localized('M03/M04/VIS05/EX06 shared-memory tiling 与 bank', 'M03/M04/VIS05/EX06 shared-memory tiling and banks'),
    'cuda-version-record',
    ['M03', 'M04', 'VIS05', 'EX06'],
    localized(
      'Programming Guide 与 Best Practices Guide v13.3；11.8.0 与 12.9.1 owner guide。',
      'Programming Guide and Best Practices Guide v13.3; 11.8.0 and 12.9.1 owner guides.',
    ),
    '2026-08-27',
    '2026-08-27',
  ),
  sourceRecord(
    'SRC-CUDA-020',
    localized('M05/M06/VIS03 synchronization、warp 与 Independent Thread Scheduling', 'M05/M06/VIS03 synchronization, warps, and Independent Thread Scheduling'),
    'cuda-version-record',
    ['F02', 'M05', 'M06', 'VIS03'],
    localized(
      'CUDA Programming Guide v13.3；11.8.0 与 12.9.1 archived synchronization/SIMT owner documentation。',
      'CUDA Programming Guide v13.3; archived 11.8.0 and 12.9.1 synchronization and SIMT owner documentation.',
    ),
    '2026-08-28',
    '2026-08-28',
  ),
  sourceRecord(
    'SRC-CUDA-021',
    localized('M07/M08/VIS07 stream、event dependency 与 timing', 'M07/M08/VIS07 streams, event dependencies, and timing'),
    'cuda-version-record',
    ['F05', 'M07', 'M08', 'VIS07'],
    localized(
      'CUDA Programming Guide v13.3；Runtime API v13.3.1；11.8.0 与 12.9.1 archived stream/event owner documentation。',
      'CUDA Programming Guide v13.3; Runtime API v13.3.1; archived 11.8.0 and 12.9.1 stream and event owner documentation.',
    ),
    '2026-08-28',
    '2026-08-28',
  ),
  sourceRecord(
    'SRC-CUDA-022',
    localized('Q01 correctness oracle 与数值比较', 'Q01 correctness oracles and numerical comparison'),
    'cuda-version-record',
    ['F04', 'O04', 'Q01'],
    localized(
      'CUDA C++ Best Practices Guide 与 Floating Point and IEEE 754 的 current v13.3、11.8.0 和 12.9.1 owner documentation。',
      'Current v13.3, 11.8.0, and 12.9.1 owner documentation for the CUDA C++ Best Practices Guide and Floating Point and IEEE 754.',
    ),
    '2026-08-28',
    '2026-08-28',
  ),
  sourceRecord(
    'SRC-CUDA-023',
    localized('Q03/Q04/EX16/LAB07 Compute Sanitizer', 'Q03/Q04/EX16/LAB07 Compute Sanitizer'),
    'cuda-version-record',
    ['Q03', 'Q04', 'EX16', 'LAB07'],
    localized(
      'Compute Sanitizer 2026.2.1；CUDA Toolkit 11.8.0 archive；12.9.1 documentation 与 12.9.2 Lane component coordinates。',
      'Compute Sanitizer 2026.2.1; CUDA Toolkit 11.8.0 archive; 12.9.1 documentation and 12.9.2 Lane component coordinates.',
    ),
    '2026-08-28',
    '2026-08-28',
  ),
  sourceRecord(
    'SRC-CUDA-024',
    localized('Q05/LAB04/LAB05 诚实计时与 profiling', 'Q05/LAB04/LAB05 honest timing and profiling'),
    'cuda-version-record',
    ['O03', 'M08', 'Q01', 'Q05', 'EX05', 'EX06', 'LAB04', 'LAB05'],
    localized(
      'Best Practices Guide v13.3、Runtime API v13.3.1、Programming Guide v13.3、12.2 release notes、11.8.0/12.9.1 archive，以及 Nsight Compute 2022.3.0、2025.2.1 和 2026.2.1。',
      'Best Practices Guide v13.3, Runtime API v13.3.1, Programming Guide v13.3, the 12.2 release notes, the 11.8.0/12.9.1 archives, and Nsight Compute 2022.3.0, 2025.2.1, and 2026.2.1.',
    ),
    '2026-08-28',
    '2026-08-28',
  ),
];

export const RESOURCE_INDEX_RECORDS: readonly ResourceIndexRecord[] = [
  ...labs,
  ...practice,
  ...visuals,
  ...glossary,
  ...sources,
];
