// SPDX-License-Identifier: Apache-2.0
export const architectureEvolutionCopy = {
  en: {
    title: 'VIS15 · From implicit timing to explicit contracts',
    notice: 'Source-reviewed capability comparison. No GPU detection, CUDA execution, timing or speed ranking.',
    controls: 'Filter documented capabilities', capability: 'Exact compute capability', feature: 'Required feature',
    all: 'All reviewed states', reset: 'Reset filters', count: 'Matching CC states',
    empty: 'No reviewed state matches both filters. Change a filter or reset; keep the portable baseline.',
    invalid: 'Unknown filter rejected. The previous selection is retained.',
    static: 'Complete static comparison', baseline: 'Portable baseline first',
    baselineText: 'CC 7.5+ within the site scope: ordinary loads/stores, explicit warp/block synchronization and FP32 SIMT arithmetic. One GPU; bound problem memory below 8 GB. A kernel still needs a compatible build and device.',
    architecture: 'Architecture / CC', target: 'Virtual / real target', shared: 'Shared memory limit per block',
    features: 'Reviewed features', yes: 'Available', no: 'Not available',
    memory: 'Limits are KiB (1024 B). Above 48 KiB requires dynamic allocation and opt-in; CC 10.7 also requires the oversized-shared-memory mode for the 328 KiB configuration. CC 10.7 is a documented comparison, outside EX25’s pinned 13.3.1 build targets. Limits are not device memory capacity or occupancy.',
    scopes: 'Suffix a is exact-CC only. Family targets are bounded sets: 100f → 10.0/10.3/10.7; 103f → 10.3/10.7; 107f → 10.7; 110f → 11.0; 120f → 12.0/12.1; 121f → 12.1. These documented scopes do not authorize a build or run. H05/H06 and EX25 additionally gate compiler, image, API, layout and resources; FP4 availability does not authorize reduced precision.',
    fallback: 'Query actual L2 capacity and persistence limits; CC does not set a cache size. MIG disables L2 set-aside; MPS controls its size at server startup. For clusters, query supported dimensions and occupancy (portable ceiling 8, possibly lower on a partition); keep every block alive through remote accesses. TMA needs direction-specific completion, aligned storage and safe reuse, not necessarily a cluster. H03/H04 specify the gates. If a gate fails, revalidate ordinary loads/stores or global scratch plus ordered kernels. No cache, cluster or TMA speedup is implied.',
    labels: { its: 'Independent thread scheduling', 'async-copy': 'Hardware global → shared copy', 'split-barrier': 'Hardware split arrive/wait', fp16: 'FP16 Tensor Core inputs', bf16: 'BF16 Tensor Core inputs', tf32: 'TF32 Tensor Core inputs', fp64: 'Native FP64 Tensor Core inputs', 'l2-policy': 'L2 persistence policy (environment-gated)', clusters: 'Thread block clusters', dsm: 'Distributed shared memory (within cluster)', tma: 'TMA bulk / tensor copies', 'family-target': 'Family-scoped target support', fp4: 'FP4 Tensor Core inputs (precision-gated)' },
  },
  'zh-CN': {
    title: 'VIS15 · 从隐式时序到显式契约',
    notice: '基于来源核对的能力对照。不检测 GPU，不执行 CUDA，不提供时间或速度排名。',
    controls: '筛选已核对的能力', capability: '精确计算能力', feature: '所需功能',
    all: '全部已核对状态', reset: '重置筛选', count: '匹配的 CC 状态数',
    empty: '没有已核对状态同时满足两个筛选条件。请修改条件或重置，并保留可移植基线。',
    invalid: '已拒绝未知筛选值，保留之前的选择。',
    static: '完整静态对照', baseline: '先确定可移植基线',
    baselineText: '本站范围内 CC 7.5+：普通加载／存储、显式线程束／线程块同步与 FP32 SIMT 运算。单 GPU，问题内存限定在 8 GB 内。内核仍需兼容的构建与设备。',
    architecture: '架构／CC', target: '虚拟／真实目标', shared: '每线程块共享内存上限',
    features: '已核对功能', yes: '具备', no: '不具备',
    memory: '单位为 KiB（1024 B）。超过 48 KiB 需动态分配并显式启用；CC 10.7 的 328 KiB 配置还需启用超额共享内存模式。CC 10.7 仅为文档对照，不属于 EX25 固定的 13.3.1 构建目标。上限不代表显存容量或占用率。',
    scopes: '后缀 a 只适用于精确 CC。家族目标是有界集合：100f → 10.0/10.3/10.7；103f → 10.3/10.7；107f → 10.7；110f → 11.0；120f → 12.0/12.1；121f → 12.1。文档范围不能授权构建或运行。H05/H06 和 EX25 还检查编译器、镜像、API、布局与资源；FP4 可用不代表可以降低精度。',
    fallback: '查询实际 L2 容量与持久化限制，CC 不能确定缓存大小。MIG 禁用 L2 预留区，MPS 在服务启动时控制大小。集群需查询支持维度与占用率（可移植上限 8，分区上可能更低），远端访问结束前所有块保持存活。TMA 需按方向区分完成、存储对齐与安全复用，并不总需集群。H03/H04 列出门槛。不满足时重新验证普通加载／存储，或全局暂存加有序内核。这里不推断缓存、集群或 TMA 加速比。',
    labels: { its: '独立线程调度', 'async-copy': '硬件全局 → 共享拷贝', 'split-barrier': '硬件分离到达／等待', fp16: 'FP16 Tensor Core 输入', bf16: 'BF16 Tensor Core 输入', tf32: 'TF32 Tensor Core 输入', fp64: '原生 FP64 Tensor Core 输入', 'l2-policy': 'L2 持久化策略（受环境门槛约束）', clusters: '线程块集群', dsm: '分布式共享内存（集群内）', tma: 'TMA 批量／张量拷贝', 'family-target': '家族范围目标支持', fp4: 'FP4 Tensor Core 输入（受精度门槛约束）' },
  },
} as const;
