// SPDX-License-Identifier: Apache-2.0
import type { MemoryTransactionIssue } from './memory-transaction-model';
import type { SharedMemoryBankClassification, SharedMemoryBankIssue } from './shared-memory-bank-model';
import type {
  MemoryHierarchyRecordId,
  MemoryOperationFilter,
  MemoryScopeFilter,
} from './memory-hierarchy-model';

export type MemoryVisualLocale = 'zh-CN' | 'en';

export const MEMORY_TRANSACTION_COPY = {
  'zh-CN': {
    eyebrow: 'VIS04 · 32-BYTE SEGMENT LEDGER',
    title: '把每个 lane 的请求字节归入自然对齐 segment',
    summary: '改变访问模式、元素宽度、stride、起始 offset 与 active lane，逐项核对 naturally aligned byte range 属于哪些 32-byte segment。',
    conceptualNotice:
      '限定模型处理一个 warp 的一次 global-memory instruction，元素宽度为 1、2、4 或 8 byte，起始 offset 必须按元素宽度自然对齐。Active lane 为从 0 开始的连续 lane，fixture base B=0 且按 32 byte 对齐。它适用于 compute capability 6.0+；本站 Stable Curriculum 从 CC 7.5+ 开始。浏览器只做地址分组，不执行 CUDA，也不观察 cache、hardware transaction、bandwidth 或 speedup。',
    controlsLabel: '内存请求分组控制',
    pattern: '访问模式',
    patterns: { contiguous: '连续（stride 固定为 1）', strided: '按元素 stride' },
    elementSize: '元素宽度（byte）',
    stride: 'Stride（元素）',
    offset: '起始 offset（byte）',
    activeLanes: 'Active lane 数',
    reset: '重置地址分组',
    limits: '只接受界面范围内的规范十进制整数；offset 必须是元素宽度的整数倍，active lane 上限为 32。非法输入不生成部分结果。',
    invalid: '输入无效；地址分组已关闭。请修复标记的字段。',
    result: '当前 byte-range ledger',
    status: '个 lane 的请求归入',
    segmentGroups: '个自然对齐 32-byte segment',
    requestedBytes: '请求 byte',
    coveredBytes: 'Segment 覆盖 byte',
    unusedBytes: '覆盖但未请求 byte',
    segmentList: 'Segment 分组',
    segmentRange: 'Segment byte range',
    laneIds: '涉及 lane',
    bytesInSegment: '本 segment 请求 byte',
    laneTable: 'Lane、地址与 segment 映射',
    laneTableScrollLabel: '可横向滚动的 lane、地址与 segment 映射表',
    lane: 'Lane',
    addressRange: '请求 byte range',
    segmentStarts: 'Segment 起点',
    staticHeading: '无脚本与打印用固定地址账本',
    staticIntro: '四个案例由同一纯模型生成：对齐连续、相对 segment 偏移 4 byte、stride 2，以及只有 5 个 active lane 的 partial warp。',
    staticLabels: {
      'aligned-contiguous': '32 lanes × 4 B，offset 0',
      'offset-four': '32 lanes × 4 B，offset 4',
      'stride-two': '32 lanes × 4 B，stride 2',
      'partial-warp': '5 active lanes × 4 B，offset 0',
    },
    noEvidence:
      '此可视化不编译或运行 CUDA，也不读取 GPU 或 profiler。它不授予 Compile-Checked、Community-Observed 或 Runtime-Verified Evidence Status。',
    issues: {
      'pattern-invalid': '访问模式无效。',
      'element-size-invalid': '元素宽度只能是 1、2、4 或 8 byte。',
      'stride-invalid': 'Stride 必须是 1 到 64 的规范十进制整数。',
      'contiguous-stride-mismatch': '连续模式要求 stride 为 1。',
      'offset-invalid': 'Offset 必须是 0 到 4096 的规范十进制整数。',
      'offset-element-misaligned': 'Offset 必须是所选元素宽度的整数倍。',
      'active-lanes-invalid': 'Active lane 数必须是 1 到 32。',
    } satisfies Record<MemoryTransactionIssue, string>,
  },
  en: {
    eyebrow: 'VIS04 · 32-BYTE SEGMENT LEDGER',
    title: 'Place every lane’s requested bytes into naturally aligned segments',
    summary: 'Change the pattern, element width, stride, starting offset, and active lanes, then inspect which 32-byte segments contain the naturally aligned byte ranges.',
    conceptualNotice:
      'The bounded model handles one global-memory instruction from one warp. Element width is 1, 2, 4, or 8 bytes, and the starting offset must be naturally aligned to that width. Active lanes are consecutive from lane 0, and the fixture base B=0 is aligned to 32 bytes. It applies to compute capability 6.0 and newer; this site’s Stable Curriculum starts at CC 7.5. The browser groups addresses only. It executes no CUDA and observes no cache, hardware transaction, bandwidth, or speedup.',
    controlsLabel: 'Memory-request grouping controls',
    pattern: 'Access pattern',
    patterns: { contiguous: 'Contiguous (stride fixed at 1)', strided: 'Strided by element' },
    elementSize: 'Element width (bytes)',
    stride: 'Stride (elements)',
    offset: 'Starting offset (bytes)',
    activeLanes: 'Active lanes',
    reset: 'Reset address grouping',
    limits: 'Use canonical decimal integers within the displayed ranges. Offset must be a multiple of element width, and active lanes are capped at 32. Invalid input produces no partial result.',
    invalid: 'Invalid input; address grouping is closed. Repair the marked fields.',
    result: 'Current byte-range ledger',
    status: 'lane requests occupy',
    segmentGroups: 'naturally aligned 32-byte segments',
    requestedBytes: 'Requested bytes',
    coveredBytes: 'Segment coverage bytes',
    unusedBytes: 'Covered but unrequested bytes',
    segmentList: 'Segment groups',
    segmentRange: 'Segment byte range',
    laneIds: 'Contributing lanes',
    bytesInSegment: 'Requested bytes in segment',
    laneTable: 'Lane, address, and segment mapping',
    laneTableScrollLabel: 'Scrollable lane, address, and segment mapping table',
    lane: 'Lane',
    addressRange: 'Requested byte range',
    segmentStarts: 'Segment starts',
    staticHeading: 'Fixed address ledgers for no-script and print output',
    staticIntro: 'The same pure model generates four cases: aligned contiguous, a 4-byte segment-relative offset, stride 2, and a partial warp with 5 active lanes.',
    staticLabels: {
      'aligned-contiguous': '32 lanes × 4 B, offset 0',
      'offset-four': '32 lanes × 4 B, offset 4',
      'stride-two': '32 lanes × 4 B, stride 2',
      'partial-warp': '5 active lanes × 4 B, offset 0',
    },
    noEvidence:
      'This visual compiles and runs no CUDA and reads no GPU or profiler. It grants no Compile-Checked, Community-Observed, or Runtime-Verified Evidence Status.',
    issues: {
      'pattern-invalid': 'The access pattern is invalid.',
      'element-size-invalid': 'Element width must be 1, 2, 4, or 8 bytes.',
      'stride-invalid': 'Stride must be a canonical decimal integer from 1 through 64.',
      'contiguous-stride-mismatch': 'Contiguous mode requires stride 1.',
      'offset-invalid': 'Offset must be a canonical decimal integer from 0 through 4096.',
      'offset-element-misaligned': 'Offset must be a multiple of the selected element width.',
      'active-lanes-invalid': 'Active lanes must be from 1 through 32.',
    } satisfies Record<MemoryTransactionIssue, string>,
  },
} as const satisfies Record<MemoryVisualLocale, unknown>;

export const SHARED_MEMORY_BANK_COPY = {
  'zh-CN': {
    eyebrow: 'VIS05 · SHARED-MEMORY BANK ROUTER',
    title: '先映射 address 到 bank，再命名冲突程度',
    summary: '固定 32 个 lane 与 4-byte word，用 wordIndex mod bankCount 展开每个 lane 的地址和 bank。',
    conceptualNotice:
      '这个 read-mapping fixture 的 32 banks、连续 4-byte word 对应声明的 CUDA 规则；其他 bank count 只用于抽象比较。浏览器不执行 CUDA，conflict degree 也不是 timing、bandwidth 或 speedup。',
    controlsLabel: 'Shared-memory bank 映射控制',
    bankCount: 'Bank 数',
    stride: 'Stride（word）',
    padding: 'Padding（word）',
    reset: '重置 bank 映射',
    limits: '地址公式：wordIndex = lane × (stride + padding)，byteAddress = wordIndex × 4，bank = wordIndex mod bankCount。',
    invalid: '输入无效；bank 映射已关闭。请使用界面范围内的规范十进制整数。',
    result: '当前 bank ledger',
    classifications: {
      'conflict-free': 'CONFLICT-FREE',
      'bank-conflict': 'BANK CONFLICT',
      'same-address-broadcast': 'SAME-ADDRESS BROADCAST',
    } satisfies Record<SharedMemoryBankClassification, string>,
    conflictDegree: 'Conflict degree',
    laneStep: 'Lane address step',
    bankGroups: '被访问 bank',
    mappingTable: 'Lane、word address 与 bank 映射',
    mappingTableScrollLabel: '可横向滚动的 lane、word address 与 bank 映射表',
    lane: 'Lane',
    wordIndex: 'Word index',
    byteAddress: 'Byte address',
    bank: 'Bank',
    bankSummary: 'Bank / lanes / distinct addresses',
    distinctAddresses: '个不同地址',
    broadcastNote: '同一次 read 中所有 lane 请求同一个 word 时单独标为 broadcast，不按 32 个不同地址计算；same-address write 不在此模型内。',
    staticHeading: '五种固定映射',
    staticIntro: '同一模型保留 stride 1、stride 2、stride 32、加 1 padding 与 same-address broadcast。',
    staticLabels: {
      'stride-one': 'Stride 1，padding 0',
      'stride-two': 'Stride 2，padding 0',
      'stride-thirty-two': 'Stride 32，padding 0',
      'padded-thirty-three': 'Stride 32，padding 1',
      broadcast: 'Stride 0，padding 0',
    },
    noEvidence:
      '此抽象 mapper 不编译或运行 CUDA，也不观察 latency。它不授予 Compile-Checked、Community-Observed 或 Runtime-Verified Evidence Status。',
    issues: {
      'bank-count-invalid': 'Bank 数必须是 1 到 64。',
      'stride-invalid': 'Stride 必须是 0 到 64。',
      'padding-invalid': 'Padding 必须是 0 到 64。',
    } satisfies Record<SharedMemoryBankIssue, string>,
  },
  en: {
    eyebrow: 'VIS05 · SHARED-MEMORY BANK ROUTER',
    title: 'Map addresses to banks before naming the conflict degree',
    summary: 'Hold 32 lanes and 4-byte words fixed, then expand every lane’s address and bank with wordIndex modulo bankCount.',
    conceptualNotice:
      'This read-mapping fixture uses the declared CUDA rule of 32 banks and successive 4-byte words; other bank counts are abstract comparisons only. The browser executes no CUDA, and conflict degree is not timing, bandwidth, or speedup.',
    controlsLabel: 'Shared-memory bank-mapping controls',
    bankCount: 'Bank count',
    stride: 'Stride (words)',
    padding: 'Padding (words)',
    reset: 'Reset bank mapping',
    limits: 'Address formula: wordIndex = lane × (stride + padding), byteAddress = wordIndex × 4, and bank = wordIndex mod bankCount.',
    invalid: 'Invalid input; bank mapping is closed. Use canonical decimal integers within the displayed ranges.',
    result: 'Current bank ledger',
    classifications: {
      'conflict-free': 'CONFLICT-FREE',
      'bank-conflict': 'BANK CONFLICT',
      'same-address-broadcast': 'SAME-ADDRESS BROADCAST',
    } satisfies Record<SharedMemoryBankClassification, string>,
    conflictDegree: 'Conflict degree',
    laneStep: 'Lane address step',
    bankGroups: 'Banks addressed',
    mappingTable: 'Lane, word address, and bank mapping',
    mappingTableScrollLabel: 'Scrollable lane, word address, and bank mapping table',
    lane: 'Lane',
    wordIndex: 'Word index',
    byteAddress: 'Byte address',
    bank: 'Bank',
    bankSummary: 'Bank / lanes / distinct addresses',
    distinctAddresses: 'distinct addresses',
    broadcastNote: 'When every lane in one read requests the same word, the model labels a broadcast instead of counting 32 distinct addresses. Same-address writes are outside this model.',
    staticHeading: 'Five fixed mappings',
    staticIntro: 'The same model preserves stride 1, stride 2, stride 32, one word of padding, and same-address broadcast.',
    staticLabels: {
      'stride-one': 'Stride 1, padding 0',
      'stride-two': 'Stride 2, padding 0',
      'stride-thirty-two': 'Stride 32, padding 0',
      'padded-thirty-three': 'Stride 32, padding 1',
      broadcast: 'Stride 0, padding 0',
    },
    noEvidence:
      'This abstract mapper compiles and runs no CUDA and observes no latency. It grants no Compile-Checked, Community-Observed, or Runtime-Verified Evidence Status.',
    issues: {
      'bank-count-invalid': 'Bank count must be from 1 through 64.',
      'stride-invalid': 'Stride must be from 0 through 64.',
      'padding-invalid': 'Padding must be from 0 through 64.',
    } satisfies Record<SharedMemoryBankIssue, string>,
  },
} as const satisfies Record<MemoryVisualLocale, unknown>;

type HierarchyRecordCopy = Readonly<{
  title: string;
  ownerAcquisition: string;
  accessibleScope: string;
  lifetime: string;
  releaseEnd: string;
  physicalAddressSpaceCaveat: string;
}>;

export const MEMORY_HIERARCHY_COPY = {
  'zh-CN': {
    eyebrow: 'VIS06 · OWNERSHIP / SCOPE / END',
    title: '用 owner、可见范围和结束条件拆开 CUDA memory 名称',
    summary: '按 accessible scope 与 operation path 筛选 host、global、constant、shared、local 与 register，同时保留六项静态全表。',
    conceptualNotice:
      '这是纯 catalog/filter 模型。它不探测实际 placement、cache hit、latency 或设备资源；cache 层不是 CUDA address space，“local”也不表示 on-chip。',
    controlsLabel: 'Memory scope 与 operation path 筛选',
    scope: '可访问 scope',
    operation: 'Operation path',
    reset: '重置为全部六项',
    scopes: {
      all: '全部 scope', host: 'Host', grid: 'Grid', block: 'Block', thread: 'Thread',
    } satisfies Record<MemoryScopeFilter, string>,
    operations: {
      all: '全部 operation path',
      'host-language': 'Host-language allocation / object',
      'runtime-api': 'CUDA Runtime allocation API',
      'symbol-api': 'CUDA symbol API',
      'kernel-declaration': 'Kernel declaration',
      'compiler-placement': 'Compiler placement',
    } satisfies Record<MemoryOperationFilter, string>,
    result: '筛选结果',
    shown: '项匹配当前 scope 与 operation path',
    empty: '没有记录同时匹配当前 scope 与 operation path。',
    ownerAcquisition: 'Owner / acquisition',
    accessibleScope: 'Accessible scope',
    lifetime: 'Lifetime',
    releaseEnd: 'Release / end',
    caveat: 'Physical / address-space caveat',
    staticHeading: '完整六项静态 catalog',
    staticIntro: '无脚本和打印输出始终包含全部六项。层的位置只组织概念，不是 latency 或 bandwidth 轴。',
    layerLabels: {
      'host-system': 'HOST SYSTEM',
      'device-memory': 'DEVICE MEMORY / ADDRESS SPACES',
      'streaming-multiprocessor': 'STREAMING MULTIPROCESSOR STORAGE',
    },
    noEvidence:
      '此 catalog 不编译、运行或探测 CUDA。筛选结果不授予 Compile-Checked、Community-Observed 或 Runtime-Verified Evidence Status。',
    records: {
      host: {
        title: 'Host memory',
        ownerAcquisition: 'Host application 通过 host-language allocator/object declaration 或 CUDA Runtime host-allocation API（如 cudaMallocHost）取得 storage。',
        accessibleScope: 'Host code；device 访问必须另行声明 mapped 或 managed 机制。',
        lifetime: 'Allocation 或 host object 的 lifetime，不依附于单次 kernel launch。',
        releaseEnd: '匹配的 host-language release、object destruction、cudaFreeHost，或 process 结束。',
        physicalAddressSpaceCaveat: 'Host memory 不是 kernel device address space；映射不会抹去 host ownership。',
      },
      global: {
        title: 'Global memory',
        ownerAcquisition: 'Host 通过 CUDA Runtime allocation API 取得 device allocation storage。',
        accessibleScope: '持有合法 pointer 的 grid thread；host 通过 CUDA API 管理或复制。',
        lifetime: '跨 kernel launch 持续，直到 allocation 释放或 CUDA context 结束。',
        releaseEnd: '匹配的 release（如 cudaFree）、device reset 或 context/application 结束。',
        physicalAddressSpaceCaveat: 'Global 是 device address space；L1/L2 可以服务访问，但 cache 不是替代 address space。',
      },
      constant: {
        title: 'Constant memory',
        ownerAcquisition: 'Module/context 持有 __constant__ symbol；host 通过 symbol API 初始化。',
        accessibleScope: 'Kernel thread 在 grid 范围内只读；host Runtime API 可以定位 symbol。',
        lifetime: '随 module/context 持续，不会为每个 thread block 重新创建。',
        releaseEnd: 'Module unload、context destruction、device reset 或 application 结束。',
        physicalAddressSpaceCaveat: 'Constant 是独立 device address space；constant cache 不创建第二份 object lifetime。',
      },
      shared: {
        title: 'Shared memory',
        ownerAcquisition: '每个 thread block 取得 static declaration 和/或 launch 指定大小的 dynamic shared storage。',
        accessibleScope: 'Owning block 的 thread，并受程序 synchronization 与 ordering 约束。',
        lifetime: 'Owning block 在 kernel execution 期间存在。',
        releaseEnd: 'Owning block 完成时结束；程序不对它调用 cudaFree。',
        physicalAddressSpaceCaveat: 'Shared 是 SM 上由程序管理的 address space；与 L1 共享 physical resource 不会把它变成 cache。',
      },
      local: {
        title: 'Local memory',
        ownerAcquisition: 'Compiler 为每个 thread 的特定 automatic object 与 spill 提供 private local storage。',
        accessibleScope: '只有 owning thread 能通过自己的逻辑地址访问。',
        lifetime: 'Owning thread 在 kernel 中的执行期间。',
        releaseEnd: 'Owning thread/kernel execution 结束；host 不对它调用 cudaFree。',
        physicalAddressSpaceCaveat: 'Local 描述 thread-local scope，不描述 on-chip placement；local memory 位于 device memory。',
      },
      register: {
        title: 'Register storage',
        ownerAcquisition: '资源与 code generation 允许时，compiler 把 per-thread value 分配到 register。',
        accessibleScope: '只有 owning thread；register 不是 block-shared address space。',
        lifetime: 'Owning thread 在 kernel 中的执行期间。',
        releaseEnd: '随 owning thread/kernel execution 结束；取得和结束由 compiler 管理。',
        physicalAddressSpaceCaveat: 'Register 是 on-SM storage；压力可能把 value spill 到物理上位于 device memory 的 local address space。',
      },
    } satisfies Record<MemoryHierarchyRecordId, HierarchyRecordCopy>,
  },
  en: {
    eyebrow: 'VIS06 · OWNERSHIP / SCOPE / END',
    title: 'Separate CUDA memory names by owner, visibility, and end condition',
    summary: 'Filter host, global, constant, shared, local, and register records by accessible scope and operation path while a complete static table remains available.',
    conceptualNotice:
      'This is a pure catalog and filter model. It probes no placement, cache hit, latency, or device resource. Cache layers are not CUDA address spaces, and “local” does not mean on-chip.',
    controlsLabel: 'Memory scope and operation-path filters',
    scope: 'Accessible scope',
    operation: 'Operation path',
    reset: 'Reset to all six records',
    scopes: {
      all: 'All scopes', host: 'Host', grid: 'Grid', block: 'Block', thread: 'Thread',
    } satisfies Record<MemoryScopeFilter, string>,
    operations: {
      all: 'All operation paths',
      'host-language': 'Host-language allocation / object',
      'runtime-api': 'CUDA Runtime allocation API',
      'symbol-api': 'CUDA symbol API',
      'kernel-declaration': 'Kernel declaration',
      'compiler-placement': 'Compiler placement',
    } satisfies Record<MemoryOperationFilter, string>,
    result: 'Filtered records',
    shown: 'records match the current scope and operation path',
    empty: 'No record matches the current scope and operation path.',
    ownerAcquisition: 'Owner / acquisition',
    accessibleScope: 'Accessible scope',
    lifetime: 'Lifetime',
    releaseEnd: 'Release / end',
    caveat: 'Physical / address-space caveat',
    staticHeading: 'Complete static six-record catalog',
    staticIntro: 'No-script and print output always contains all six records. Layer position organizes concepts; it is not a latency or bandwidth axis.',
    layerLabels: {
      'host-system': 'HOST SYSTEM',
      'device-memory': 'DEVICE MEMORY / ADDRESS SPACES',
      'streaming-multiprocessor': 'STREAMING MULTIPROCESSOR STORAGE',
    },
    noEvidence:
      'This catalog compiles, runs, and probes no CUDA. Filter results grant no Compile-Checked, Community-Observed, or Runtime-Verified Evidence Status.',
    records: {
      host: {
        title: 'Host memory',
        ownerAcquisition: 'The host application acquires storage through a host-language allocator/object declaration or a CUDA Runtime host-allocation API such as cudaMallocHost.',
        accessibleScope: 'Host code; device access requires a separately declared mapped or managed mechanism.',
        lifetime: 'The allocation or host object lifetime, independent of any single kernel launch.',
        releaseEnd: 'The matching host-language release, object destruction, cudaFreeHost call, or process termination.',
        physicalAddressSpaceCaveat: 'Host memory is not a kernel device address space; mapping does not erase host ownership.',
      },
      global: {
        title: 'Global memory',
        ownerAcquisition: 'The host acquires device allocation storage through a CUDA Runtime allocation API.',
        accessibleScope: 'Grid threads with a valid pointer; host code manages or copies it through CUDA APIs.',
        lifetime: 'Persists across kernel launches until the allocation is released or the CUDA context ends.',
        releaseEnd: 'A matching release such as cudaFree, device reset, or context/application termination.',
        physicalAddressSpaceCaveat: 'Global is a device address space. L1/L2 may serve accesses, but caches are not replacement address spaces.',
      },
      constant: {
        title: 'Constant memory',
        ownerAcquisition: 'A module/context owns a __constant__ symbol; host code initializes it through symbol APIs.',
        accessibleScope: 'Read-only to kernel threads in a grid; host Runtime APIs can locate the symbol.',
        lifetime: 'Persists with its module/context rather than being recreated per thread block.',
        releaseEnd: 'Module unload, context destruction, device reset, or application termination.',
        physicalAddressSpaceCaveat: 'Constant is a distinct device address space; its cache does not create a second object lifetime.',
      },
      shared: {
        title: 'Shared memory',
        ownerAcquisition: 'Each thread block receives static declarations and/or launch-sized dynamic shared storage.',
        accessibleScope: 'Threads of the owning block, subject to the program’s synchronization and ordering.',
        lifetime: 'Exists for the owning block during kernel execution.',
        releaseEnd: 'Ends when the owning block completes; the program does not cudaFree it.',
        physicalAddressSpaceCaveat: 'Shared is a programmer-managed address space on an SM; sharing a physical resource with L1 does not make it a cache.',
      },
      local: {
        title: 'Local memory',
        ownerAcquisition: 'The compiler gives each thread private local storage for selected automatic objects and spills.',
        accessibleScope: 'Only the owning thread through its private logical addresses.',
        lifetime: 'The owning thread’s execution within the kernel.',
        releaseEnd: 'Ends when the owning thread/kernel execution ends; host code does not cudaFree it.',
        physicalAddressSpaceCaveat: 'Local describes thread-local scope, not on-chip placement; local memory resides in device memory.',
      },
      register: {
        title: 'Register storage',
        ownerAcquisition: 'The compiler assigns per-thread values to registers when resources and code generation permit.',
        accessibleScope: 'Only the owning thread; registers are not a block-shared address space.',
        lifetime: 'The owning thread’s execution within the kernel.',
        releaseEnd: 'Ends with the owning thread/kernel execution; acquisition and release are compiler-managed.',
        physicalAddressSpaceCaveat: 'Registers are on-SM storage; pressure can spill values into the physically off-chip local address space.',
      },
    } satisfies Record<MemoryHierarchyRecordId, HierarchyRecordCopy>,
  },
} as const satisfies Record<MemoryVisualLocale, unknown>;
